### ISSUE TITLE
"jobs = 0" is twice slower than "jobs = 1" when running via "pre-commit"

### ISSUE THREAD

**Issue by AIGeneratedUsername** [PyCQA/pylint#7245] opened 2022-07-31 09:10 UTC
### Bug description

"jobs = 0" is twice slower than "jobs = 1" 

(57 seconds VS  30 seconds)

### Commands

Set `jobs = 0`:
```shell
# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the
# number of processors available to use, and will cap the count on Windows to
# avoid hangs.
jobs = 0
```
Result:
```
time pre-commit run pylint --all-files
pylint...................................................................Passed

real    0m57,423s
user    3m9,893s
sys     0m5,131s
```

Set `jobs = 1`:
```ini
# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the
# number of processors available to use, and will cap the count on Windows to
# avoid hangs.
jobs = 1
```
Result:
```
time pre-commit run pylint --all-files
pylint...................................................................Passed

real    0m30,851s
user    1m39,719s
sys     0m2,460s
```

### Expected behavior

"jobs = 0"  and  "jobs = 1" must have the same execution time when running via "pre-commit"

As the documentation says, jobs can not be < 1, so if I set `jobs = 0`, then pylint must automatically set jobs amount >=1.  In other words, speed with "jobs = 0" can not be lower than "jobs = 1".

### Pylint version

```shell
pylint 2.14.5
astroid 2.11.7
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
```

### OS / Environment

Lubuntu 22.04

**Comment by Pierre-Sassoulas** [comment] 2022-07-31 10:22
Duplicate of #2525

**Closed by Pierre-Sassoulas** 2022-07-31 10:22 UTC
Labels: Needs triage :inbox_tray:
