### ISSUE TITLE
missing-kwoa triggers despite dict-unpacking

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#1111] opened 2016-09-15 20:22 UTC
```
def f(*, a):
    pass
d = dict(a=5)
f(**d)  # Triggers missing-kwoa
```

**Comment by PCManticore** [comment] 2016-09-25 19:21
Does this reproduces on master (pylint & astroid)? I can't reproduce it with the latest code.

**Comment by NeilGirdhar** [comment] 2016-09-25 20:02
Sorry, this triggers it:

```
def f(self, *, a):
    pass

def g(**kwargs):
    f(**kwargs)  # Triggers missing-kwoa

g(a=5)

```

**Comment by PCManticore** [comment] 2016-10-24 15:51
Hi, I still cannot reproduce this using the latest source code. Can you try with the latest astroid and pylint from the repositories and see if it works for you?

**Comment by NeilGirdhar** [comment] 2016-10-24 15:55
```
No config file found, using default configuration
************* Module a
C:  8, 0: Trailing newlines (trailing-newlines)
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Invalid function name "f" (invalid-name)
C:  1, 0: Missing function docstring (missing-docstring)
C:  1, 9: Invalid variable name "a" (invalid-name)
W:  1, 9: Unused variable 'a' (unused-variable)
C:  4, 0: Invalid function name "g" (invalid-name)
C:  4, 0: Missing function docstring (missing-docstring)
+-----------+-------+---------+-----------+
|refactor   |0      |0        |=          |
+-----------+-------+---------+-----------+
|warning    |1      |1        |=          |
+-----------+-------+---------+-----------+
|error      |1      |1        |=          |
+-----------+-------+---------+-----------+



Messages
--------

+------------------+------------+
|message id        |occurrences |
+==================+============+
|missing-docstring |3           |
+------------------+------------+
|invalid-name      |3           |
+------------------+------------+
|unused-variable   |1           |
+------------------+------------+
|trailing-newlines |1           |
+------------------+------------+
|missing-kwoa      |1           |
+------------------+------------+



Global evaluation
-----------------
Your code has been rated at -16.00/10 (previous run: -2.00/10, -14.00)

~/tex/imm/diagrams: pylint a.py | less
~/tex/imm/diagrams: pylint --version
No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 3.5.2 (default, Oct 11 2016, 15:01:25)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

**Comment by NeilGirdhar** [comment] 2016-10-24 16:01
(If you fixed it in master, then I'll await the next version. Thanks.)

**Comment by PCManticore** [comment] 2017-01-22 10:19
Closing this, since I cannot reproduce it with the master branch. But if you find another case of this bug, please reopen it or open a new issue. Thank you for reporting this!

**Comment by NeilGirdhar** [comment] 2018-04-20 11:10
@PCManticore Hi, would you mind reopening this issue?  This is still broken:
```
def some_function(*, a):
    return a + 2

def other_function(**kwargs):
    return some_function(**kwargs)  # Triggers missing-kwoa

other_function(a=2)
```

**Closed** 2018-06-06 14:50 UTC
Labels: bug
