### ISSUE TITLE
Irrefutable pattern doesn't count properly for a calculation of a function return type

### ISSUE THREAD

**Issue by enaydanov** [PyCQA/pylint#7730] opened 2022-11-08 07:25 UTC
### Bug description

```python
# pylint: disable=missing-docstring

def repro(selector: str) -> dict:
    match selector:
        case "a":
            return {"selected": "a"}
        case _:  # can be a simple capture pattern too
            raise ValueError(f"Unknown value: {selector}")


print(repro("a")["selector"])
```

### Command used

```shell
pylint repro.py
```

### Pylint output

```shell
************* Module repro
repro.py:9:6: E1136: Value 'repro('a')' is unsubscriptable (unsubscriptable-object)
```

### Expected behavior

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)

### Pylint version

```shell
pylint 2.15.5
astroid 2.12.12
Python 3.11.0 (main, Nov  2 2022, 05:40:18) [GCC 7.5.0]
```

**Comment by jacobtylerwalls** [comment] 2023-02-26 21:59
Duplicate of #5288

**Closed by jacobtylerwalls** 2023-02-26 21:59 UTC
Labels: Control flow, Duplicate 🐫, False Positive 🦟, python 3.10, Match case
