### ISSUE TITLE
``parse-error`` raised if directory matches standard library name

### ISSUE THREAD

**Issue by whonore** [PyCQA/pylint#4909] opened 2021-08-24 15:36 UTC
### Bug description

`pylint` doesn't seem to like it when a directory has the same name as a standard library module, see the output below. I get the same error with something like `pylint ./tests` too. It works fine if you specify a specific file, like `pylint tests/a.py`.

Possibly related: #4444

### Command used

```shell
mkdir pylint-test; cd pylint-test
mkdir collections math tests dir1 dir2
pylint *
```

### Pylint output

```shell
************* Module math
math/__init__.py:1:0: F0010: error while code parsing: Unable to load file math/__init__.py:
[Errno 2] No such file or directory: 'math/__init__.py' (parse-error)
************* Module collections
collections/__init__.py:1:0: F0010: error while code parsing: Unable to load file collections/__init__.py:
[Errno 2] No such file or directory: 'collections/__init__.py' (parse-error)
************* Module tests
tests/__init__.py:1:0: F0010: error while code parsing: Unable to load file tests/__init__.py:
[Errno 2] No such file or directory: 'tests/__init__.py' (parse-error)
```

### Expected behavior

No output since all the directories are empty.

### Pylint version

```shell
pylint 2.10.2
astroid 2.7.2
Python 3.9.6 (default, Aug 16 2021, 15:13:47) 
[GCC 9.3.0]
```

### OS / Environment

OS (`uname -srvmpio`):
Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Shell:
fish 3.3.1

**Comment by jacobtylerwalls** [comment] 2022-07-03 04:19
Thanks for the clear report. Based on some digging (and a draft patch) I believe this to be a duplicate of #4444.

**Closed by jacobtylerwalls** 2022-07-03 04:19 UTC
Labels: Bug :beetle:, topic-import-system, namespace-package
