### ISSUE TITLE
Checker to suggest keyword argument when using non-meaningfull litterals as positional argument

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5631] opened 2022-01-03 18:03 UTC
### Current problem

Imagine you have the following call:

```python
a = textwrap.TextWrapper(70, "", "", True, True, False, True, True, False, 4)
```      
It's very hard to understand what the code is doing. Instead you'd want to have keyword arguments:

```python
a = textwrap.TextWrapper(
    width=70,
    initial_indent="",
    subsequent_indent="",
    expand_tabs=True,
    replace_whitespace=True,
    fix_sentence_endings=False,
    break_long_words=True,
    drop_whitespace=True,
    break_on_hyphens=False,
    tabsize=4
)           
```
On the contrary for :
```python
a.wrap("my string with some content")
```   
Doing the following do not bring much value: 
```python
a.wrap(text="my string with some content")
```   

### Desired solution

A new checker that would raise ``use-keyword-arguments-for-literals`` (or something better) when we encounter a meaningless literal (not for a string containing characters).

**Comment by DanielNoord** [comment] 2022-01-03 18:39
Duplicate of #385 😉

**Closed** 2022-01-03 19:29 UTC
Labels: Enhancement ✨, Duplicate 🐫
