### ISSUE TITLE
Wrong unused-import warning when redefining import name inside class

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint#900] opened 2016-05-11 05:15 UTC
The following code:

``` python
import foo

class bar(object):
    foo = foo.baz
```

Triggers this pylint warning:

```
W:  1, 0: Unused import foo (unused-import)
```

But should not, because the `foo` module import is used to build `bar.foo`.

**Comment by moylop260** [comment] 2016-05-11 06:34
`pylint --version`

**Comment by PCManticore** [comment] 2016-05-11 10:40
I think this is a duplicate of https://github.com/PyCQA/pylint/issues/848. The gist of it is that Pylint becomes confused by your foo reassignment.

**Comment by federicobond** [comment] 2016-05-11 13:30
````
pylint 1.5.1, 
astroid 1.4.1
````

You are right, it's a duplicate of the issue you mention.

**Comment by PCManticore** [comment] 2017-01-21 14:31
Fixed in master branch.

**Closed by PCManticore** 2017-01-21 14:31 UTC
