### ISSUE TITLE
Wrong 'undefined-variable' in nested lambda parameters

### ISSUE THREAD

**Issue by szymonsobczak** [PyCQA/pylint#1128] opened 2016-10-05 21:40 UTC
Code:

```
data = [(1, (2, 3)), (4, (5, 6))]
map(
    lambda (first, (second, third)): (first, second, third),
    data
)
```

Error:

```
E:  3,45: Undefined variable 'second' (undefined-variable)
E:  3,53: Undefined variable 'third' (undefined-variable)
```

Pylint version:

```
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.10 (default, Sep 23 2015, 04:34:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
```

**Comment by szymonsobczak** [comment] 2016-10-05 21:41
May be related to #905.

**Comment by PCManticore** [comment] 2017-01-22 11:35
Duplicate of https://github.com/PyCQA/pylint/issues/895. This syntax is Python 2 specific and not supported any longer by Pylint (the syntax, not Python 2, but we might drop support for it as well).

**Closed by PCManticore** 2017-01-22 11:35 UTC
Labels: bug, minor
