### ISSUE TITLE
Error with pylint and Python 2.7.12

### ISSUE THREAD

**Issue by laimagine** [PyCQA/pylint#2134] opened 2018-05-22 17:01 UTC
### Steps to reproduce
1. Running with the latest version of pylint in `Python 2.7.12` with the latest version results in an error.

Switching pylint 1.84 works correctly. This _could_ be an issue with `astroid`

### Current behavior
```
Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for ml-api==1.0
+ ./bin/pylint --rcfile .pylintrc api/
Traceback (most recent call last):
  File "./bin/pylint", line 11, in <module>
    load_entry_point('pylint==2.0.0.dev0', 'console_scripts', 'pylint')()
  File "/var/lib/jenkins/workspace/ml-api/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/__init__.py", line 16, in run_pylint
    from pylint.lint import Run
  File "/var/lib/jenkins/workspace/ml-api/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/lint.py", line 66, in <module>
    import astroid
  File "/var/lib/jenkins/workspace/ml-api/lib/python2.7/site-packages/astroid-2.0.0.dev0-py2.7.egg/astroid/__init__.py", line 57, in <module>
    from astroid.nodes import *
  File "/var/lib/jenkins/workspace/ml-api/lib/python2.7/site-packages/astroid-2.0.0.dev0-py2.7.egg/astroid/nodes.py", line 18, in <module>
    from astroid.node_classes import (
  File "/var/lib/jenkins/workspace/ml-api/lib/python2.7/site-packages/astroid-2.0.0.dev0-py2.7.egg/astroid/node_classes.py", line 649
    yield from ()
             ^
SyntaxError: invalid syntax
```

### Expected behavior
Should not error.

### pylint --version output
```
./bin/pylint --version
Problem importing module async.py: No module named builtins
Problem importing module async.pyc: No module named builtins
Problem importing module base.py: No module named builtins
Problem importing module base.pyc: No module named builtins
Problem importing module classes.py: cannot import name zip_longest
Problem importing module classes.pyc: cannot import name zip_longest
Problem importing module design_analysis.py: No module named builtins
Problem importing module design_analysis.pyc: No module named builtins
Problem importing module exceptions.py: No module named builtins
Problem importing module exceptions.pyc: No module named builtins
Problem importing module format.py: No module named builtins
Problem importing module format.pyc: No module named builtins
Problem importing module imports.py: No module named builtins
Problem importing module imports.pyc: No module named builtins
Problem importing module logging.py: No module named builtins
Problem importing module logging.pyc: No module named builtins
Problem importing module newstyle.py: No module named builtins
Problem importing module newstyle.pyc: No module named builtins
Problem importing module python3.py: No module named builtins
Problem importing module python3.pyc: No module named builtins
Problem importing module refactoring.py: No module named builtins
Problem importing module refactoring.pyc: No module named builtins
Problem importing module spelling.py: No module named builtins
Problem importing module spelling.pyc: No module named builtins
Problem importing module stdlib.py: No module named builtins
Problem importing module stdlib.pyc: No module named builtins
Problem importing module strings.py: No module named builtins
Problem importing module strings.pyc: No module named builtins
Traceback (most recent call last):
  File "./bin/pylint", line 9, in <module>
    load_entry_point('pylint==2.0.0.dev0', 'console_scripts', 'pylint')()
  File "/usr/me/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/__init__.py", line 18, in run_pylint
    Run(sys.argv[1:])
  File "/usr/me/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/lint.py", line 1292, in __init__
    linter.load_default_plugins()
  File "/usr/me/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/lint.py", line 488, in load_default_plugins
    checkers.initialize(self)
  File "/usr/me/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/checkers/__init__.py", line 120, in initialize
    register_plugins(linter, __path__[0])
  File "/usr/me/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/utils.py", line 1165, in register_plugins
    module = modutils.load_module_from_file(join(directory, filename))
  File "/usr/local/lib/python2.7/dist-packages/astroid/modutils.py", line 272, in load_module_from_file
    return load_module_from_modpath(modpath, path, use_sys)
  File "/usr/local/lib/python2.7/dist-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/usr/me/lib/python2.7/site-packages/pylint-2.0.0.dev0-py2.7.egg/pylint/checkers/typecheck.py", line 86
    yield from _flatten_container(item)
             ^
SyntaxError: invalid syntax
```

**Comment by PCManticore** [comment] 2018-05-22 17:04
Closing as duplicate of #2133

**Closed as completed by PCManticore** 2018-05-22 17:04 UTC
