### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Project-Magenta** [PyCQA/pylint#1820] opened 2018-01-04 23:06 UTC
### Steps to reproduce
1. `import csv` in code
2. run pylint (from pip)

### Current behavior
It stops halfway reading my file and outputs:
[Error on Pastebin](https://pastebin.com/P6UvzUk0)

### Expected behavior
It outputs PEP 8 stuff

### pylint --version output
No config file found, using default configuration
pylint 1.8.1,
astroid 1.6.0
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]

**Comment by brycepg** [comment] 2018-01-05 02:49
I can't reproduce this from just running pylint against a file containing:

```python
import csv
```

with

```
__main__.py 1.8.1, 
astroid 1.6.0
Python 3.6.3 (default, Oct  9 2017, 12:11:29) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

**Comment by PCManticore** [comment] 2018-01-07 10:58
I presume the code is a bit more convoluted than a simple `import csv`, but I think that this might already been fixed in master branch by [this commit](https://github.com/PyCQA/pylint/commit/dbb2f3e65b9a452cf981e1bda318ec019b43bd8c). Can you test it and let us know if it worked?

**Closed by PCManticore** 2018-01-07 10:58 UTC
