### ISSUE TITLE
random linting in code

### ISSUE THREAD

**Issue by RadiantUwU** [PyCQA/pylint#3990] opened 2020-12-22 22:52 UTC
### Steps to reproduce
1.code
2.code
3.get bug

### Current behavior
![image](https://user-images.githubusercontent.com/69520693/102940293-a7834000-44b8-11eb-839f-33a5e826ce2b.png)
alist is an array object,
newobject is creating a new object
randomizer variable does exist

### Expected behavior
no linting

### pylint --version output
pylint 2.6.0
astroid 2.4.2
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]

**Comment by bvobart** [comment] 2020-12-23 15:53
First of all, your steps to reproduce are not reproducible at all, I hope you can see why.

Secondly, if you're posting code, use a [code block](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks). Code blocks can even give you syntax highlighting, as the link also explains.

Thirdly, while you didn't even state the exact Pylint message that you're getting, it seems to be caused by a simple typo. Notice that you define the variable `randomziers = newObject(...` on line two, yet you try to assign to `randomizers.Value` on line 3. Line 4 contains the same typo, so that's probably why you don't see a linting error there.

**Comment by PCManticore** [comment] 2020-12-26 17:21
Thanks @bvobart for the useful feedback. I think this can be closed as is.

**Closed by PCManticore** 2020-12-26 17:21 UTC
