### ISSUE TITLE
False-positive error for decorator with extra argument

### ISSUE THREAD

**Issue by horomena** [PyCQA/pylint#1652] opened 2017-09-11 05:53 UTC
### Steps to reproduce
def decorator_with_extra_var(func):
    def wrapper(x):
        return func()
    return wrapper

@decorator_with_extra_var
def pylint_error():
    pass
pylint_error("Unused")

### Current behavior
E: 11, 0: Too many positional arguments for function call (too-many-function-args)

### Expected behavior
Not an error. Either warning or refactor because of bad practice.

### pylint --version output
No config file found, using default configuration
pylint 1.7.2, 
astroid 1.5.3
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]

**Comment by PCManticore** [comment] 2017-09-13 22:14
Closed as duplicate of https://github.com/PyCQA/pylint/issues/258. There are multiple issues about the same problem.

**Closed by PCManticore** 2017-09-13 22:14 UTC
