### ISSUE TITLE
Access to a protected member from classmethod

### ISSUE THREAD

**Issue by kczapla** [PyCQA/pylint#2445] opened 2018-08-27 13:54 UTC
### Steps to reproduce
1. Install pylint 2.1.1 
2. `vim test.py`
3. Paste following snippet:
 

```python
class MyClass(object):                 
    @classmethod                                   
    def facotry_method(cls):                        
        f = cls()                                   
        f._private_function()                       

    def _private_function(self):                    
        print('I am private function')
```

3. `python3 -m pylint ./test.py`

### Current behavior

pylint prompts following error:

> test.py:5:8: W0212: Access to a protected member _private_function of a client class (protected-access)

### Expected behavior

No msg.

### pylint --version output

```bash
__main__.py 2.1.1
astroid 2.0.4
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

**Comment by PCManticore** [comment] 2018-08-31 08:15
Duplicate of #1159

**Closed by PCManticore** 2018-08-31 08:15 UTC
