### ISSUE TITLE
Cannot import UnknownMessageError in Pylint 2.4.1

### ISSUE THREAD

**Issue by uy-rrodriguez** [PyCQA/pylint#3142] opened 2019-09-26 11:16 UTC
Dear all,

I'm using Pylint via Django-Pylint for CI linting tests. I've recently identified an error where Pylint can't find the class "UnknownMessageError" in the module "pylint.utils". I thought this could be because of Django-Pylint, but it seems to me the only library that has been updated is the base Pylint.

Until pylint-2.3.1-py3-none-any everything was working fine.

The command I run is a simple pylint --rcfile=<custom rc file> <name of main module>

### Libraries
I'm currently using the following libraries and versions, as logged by pip install:
- Python 3.7.4
- pylint-2.4.1-py3-none-any
- pylint-plugin-utils-0.5
- pylint_django-2.0.11-py3-none-any

### Full error output
The Traceback output is the following:

    Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.7.4/x64/bin/pylint", line 10, in <module>
      sys.exit(run_pylint())
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
      Run(sys.argv[1:])
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint/lint.py", line 1686, in __init__
      linter.load_plugin_modules(plugins)
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint/lint.py", line 660, in load_plugin_modules
      module = modutils.load_module_from_name(modname)
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/astroid/modutils.py", line 198, in load_module_from_name
      return load_module_from_modpath(dotted_name.split("."), path, use_sys)
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/astroid/modutils.py", line 241, in load_module_from_modpath
      module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/imp.py", line 244, in load_module
      return load_package(name, filename)
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/imp.py", line 216, in load_package
      return _load(spec)
    File "<frozen importlib._bootstrap>", line 696, in _load
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint_django/__init__.py", line 6, in <module>
      from pylint_django import plugin
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint_django/plugin.py", line 3, in <module>
      from pylint_plugin_utils import get_checker
    File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 5, in <module>
      from pylint.utils import UnknownMessageError as UnknownMessage
    ImportError: cannot import name 'UnknownMessageError' from 'pylint.utils' 
    (/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/pylint/utils/__init__.py)
    ##[error]Process completed with exit code 1.

**Comment by PCManticore** [comment] 2019-09-26 11:29
Hey thanks for opening an issue. The problem is in https://github.com/PyCQA/pylint-plugin-utils which is not maintained by us. There seems to be a PR opened already at https://github.com/PyCQA/pylint-plugin-utils/issues/15, that might solve the issue once it's merged.

**Closed by PCManticore** 2019-09-26 11:29 UTC
