### ISSUE TITLE
Pylint doesn't respect max-module-lines setting

### ISSUE THREAD

**Issue by rhcu** [PyCQA/pylint#3277] opened 2019-11-28 13:44 UTC
### Steps to reproduce
1. Assign max-module-lines parameter in pylintrc to some value (e.g. 250)
2. Run pylint for Python3 with this config file with files that should produce C0302 error (too-many-lines)

### Current behavior
Nothing is reported

### Expected behavior
C0302 error (too-many-lines) should be shown

### pylint --version output
pylint 2.4.4
astroid 2.3.3
Python 3.7.4
Clang 10.0.1

**Comment by PCManticore** [comment] 2019-11-28 13:47
Thanks for the report. Is `max-module-lines` set in the `FORMAT` section of your config file? I just tried this locally and the error is emitted when the module has more lines than expected. Can you provide a minimal example that reproduces this issue?

**Comment by rhcu** [comment] 2019-11-28 17:50
Hi! Yes, it is in FORMAT section. 

I'm running 'pylint --rcfile=.pylintrc *', and I don't get any errors related to the size of the module even if the max-module-lines set to 10 or some other small number that should be violated for sure. I'm doing this on Mac OS Mojave.

**Comment by PCManticore** [comment] 2019-11-29 15:38
Would you mind submitting an example of a `pylintrc` as well as a minimal file for which this reproduces? I'm trying to do that on my machine but the warning is properly emitted. That would be super helpful in getting this fixed.

**Comment by PCManticore** [comment] 2020-06-17 06:41
Closing this as I could not reproduce it.

**Closed by PCManticore** 2020-06-17 06:41 UTC
Labels: needs reproduction
