### ISSUE TITLE
False unsubscriptable-object positive on typing.Collection with Python 3.6

### ISSUE THREAD

**Issue by scop** [PyCQA/pylint#3292] opened 2019-12-06 15:59 UTC
### Steps to reproduce

```
$ cat t.py

def test(coll: Collection[str]) -> None:
    print(len(coll))
$ pylint t.py | grep unsubscriptable
t.py:3:15: E1136: Value 'Collection' is unsubscriptable (unsubscriptable-object)
$ python --version
Python 3.6.9
```

Curiously, this is not reproducible with at least 3.7.4 or 3.8.0, I see it with 3.6.x (x={1, 9}) only.

Maybe related to #3129, #2849 ?

### Current behavior

False unsubscriptable-object positive on typing.Collection

### Expected behavior

No error

### pylint --version output

pylint 2.5.0-dev1
astroid 2.4.0
Python 3.6.9 (default, Jul 31 2019, 21:07:43) 
[GCC 7.4.0]

**Comment by PCManticore** [comment] 2019-12-12 15:43
Curious that this reproduces only on 3.6.X.

**Comment by Jon-Work** [comment] 2020-11-27 10:23
Dupe of #2377

**Comment by PCManticore** [comment] 2020-12-29 09:03
Thanks @Jon-Work

**Closed by PCManticore** 2020-12-29 09:03 UTC
Labels: bug
