### ISSUE TITLE
`useless-super-delegation` when overriding `Exception` to have different default argument

### ISSUE THREAD

**Issue by jace** [PyCQA/pylint#7319] opened 2022-08-18 09:00 UTC
### Bug description

```python
# pylint: disable=missing-module-docstring,missing-class-docstring
class CustomError(Exception):
    def __init__(self, message="default"):
        super().__init__(message)
```

### Command used

```shell
pylint a.py
```

### Pylint output

```shell
************* Module a
a.py:3:4: W0235: Useless super delegation in method '__init__' (useless-super-delegation)
```

### Expected behavior

No error, because this is not a useless super delegation. The method signature is different. A default value has been introduced. (Also discussed in #839 from which the rule was introduced).

### Pylint version

```shell
pylint 2.14.5
astroid 2.11.7
Python 3.9.13 (main, Aug 11 2022, 13:40:36)
[Clang 13.1.6 (clang-1316.0.21.2.5)]
```

### OS / Environment

macOS 12.4

**Comment by Pierre-Sassoulas** [comment] 2022-08-18 11:39
Thank you for opening the issue. I'm going to close as a duplicate of #7287

**Comment by mbyrnepr2** [comment] 2022-08-20 21:00
Perhaps this one should be treated separately/re-opened because the behaviour looks different to #7287. 
I think it should be ok for the subclass to pass its instance variables to the `Exception` since they are added to the `args` variable in the parent:

```python
(venv310) Marks-MacBook-Air-2:programming markbyrne$ cat ex1.py 
class CustomError(Exception):
    def __init__(self, a="aa", b="bb", c="cc"):
        super().__init__(a, b, c)


print(CustomError().args)
raise CustomError()
(venv310) Marks-MacBook-Air-2:programming markbyrne$ python ex1.py 
('aa', 'bb', 'cc')
Traceback (most recent call last):
  File "/Users/markbyrne/programming/ex1.py", line 7, in <module>
    raise CustomError()
__main__.CustomError: ('aa', 'bb', 'cc')
```

Let me know if any disagreement on re-opening!

**Comment by jacobtylerwalls** [comment] 2022-08-21 00:13
@mbyrnepr2 would you happen to have capacity to have a look if this depends on `Exception` e.g. on built-ins? If so it might be an `astroid` brain problem for those specific builtins.

**Comment by mbyrnepr2** [comment] 2022-08-21 08:02
Sure! I should have time later in the day. However if you have an itch to look into it please feel free.

**Comment by jacobtylerwalls** [comment] 2022-08-21 13:05
(Sorry, I was just on a laptop where I didn't feel like cloning astroid to poke around.)

I think this explains why builtins like `Exception` are causing issues:
https://github.com/PyCQA/astroid/blob/16530f78c13863f584abcd874de9070d6f275072/astroid/nodes/node_classes.py#L625-L631

I can pick it up.

**Closed** 2022-08-21 14:02 UTC
Labels: False Positive 🦟, Needs PR

**Comment by mbyrnepr2** [comment] 2022-08-21 14:04
Fab @jacobtylerwalls!
