### ISSUE TITLE
output-format=colorized broken on cygwin bash in pylint-1.6.4 

### ISSUE THREAD

**Issue by shompol** [PyCQA/pylint#1131] opened 2016-10-11 14:37 UTC
### Steps to reproduce

At cygwin bash prompt: 
1.  pip3 install pylint 
2.  pylint --generate-rcfile > .pylintrc
3.  change output-format=text  to output-format=colorized
4.  pylint hello.py
### Current behavior

pylint output is black and white
### Expected behavior

previous version of pylint produced colorized output. After `pip3 install --upgrade pylint` the output changed to black and white, with the environment and .pylintrc remaining unchanged
### pylint --version output

pylint 1.6.4,
astroid 1.4.8
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

**Comment by y2kbugger** [comment] 2016-10-24 23:21
oops, didn't do my proper searching when I posted #1140, I put in a pull request but I didn't put it toward the 1.6.X branch which may or may not be incorrect

**Comment by rlat** [comment] 2017-03-24 11:20
I am observing this issue as well on Windows 7 in Cygwin's mintty terminal. Easily reproducible with no RC file and just turning on colorized output by the `--output-format="colorized"` switch. It works fine on MacOS and Ubuntu 14.04 LTS.

pylint 1.6.5,
astroid 1.4.9
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]

**Comment by rogalski** [comment] 2017-03-24 12:55
@rlat 5936066d92363451f80283e01b212e9b5332452e is not yet shipped, please wait for 1.7.0 release.

**Comment by rogalski** [comment] 2017-08-11 19:54
Patch was shipped in 1.7.0, closing it.

**Comment by shompol** [comment] 2017-08-11 21:30
Issue still present.

$ pylint --version
pylint 1.7.2,
astroid 1.5.3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

**Comment by rogalski** [comment] 2017-08-11 22:15
Reopened. I'll attempt to take a look at it soon.

**Comment by PCManticore** [comment] 2018-05-26 05:46
Is this still not working? On windows or cygwin? We can probably test it on Windows using AppVeyor but I'm not sure how to do that for cygwin.

**Comment by y2kbugger** [comment] 2018-05-26 15:00
Try this;

    echo $TERM

Do you have it set up for the color terminal or just `xterm`?

Think about setting up in your .bashrc:

    export TERM=xterm-16color

Other than that maybe we should additionally plain `xterm-color` as well.

I've tested this on Windows both on CMD.EXE and on mintty with Git bash and pylint=1.8.2, python=3.6 and everything works and no errors.

**Comment by PCManticore** [comment] 2018-06-06 18:54
@y2kbugger so does this bug reproduces for you or not? Should we close it?

**Comment by y2kbugger** [comment] 2018-06-06 19:12
No, as I said, user error, but they never responded.

**Comment by PCManticore** [comment] 2018-06-06 19:28
Alright, thanks, closing this as it seems to be working now.

**Closed by PCManticore** 2018-06-06 19:28 UTC
Labels: needs-reproduction

**Comment by shompol** [comment] 2018-06-08 14:52
Sorry, I missed the emails earlier. I can assist testing with Cygwin. It is also pretty easy to install it on any Windows distribution.

1. I still observe the issue.
2. I never had it set up on Windows cmd and do not know how to set it up.
3. After export TERM=xterm-16color the output is colorized, but it used to work with TERM=xterm. 

Also, on Debian it works with TERM=xterm, so I don't see why Cygwin should have the additional requirement.

**Comment by y2kbugger** [comment] 2018-06-08 15:09
The problem is if you don't have a color supporting terminal. Then garbage
gets printed. Also Windows CMD and external use different kinds of color
Markup.
