### ISSUE TITLE
try-except-raise and exception subclass

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#2302] opened 2018-07-16 12:43 UTC
With this block of code:

```python
    try:
        config.instance.read_yaml()
    except configexc.ConfigFileErrors:
        raise
    except configexc.Error as e:
        desc = configexc.ConfigErrorDesc("Error", e)
        raise configexc.ConfigFileErrors('autoconfig.yml', [desc])
```

I get a `try-except-raise` error from pylint 2.0 (astroid 2.0).

However, this seems like a valid use-case: I do want to raise `configexc.ConfigFileErrors` (which is a subclass of `configexc.Error`, but handle any other `configexc.Error` exception.

**Comment by PCManticore** [comment] 2018-07-16 12:49
Hey Florian, this is a duplicate of https://github.com/PyCQA/pylint/issues/2284!

**Closed by PCManticore** 2018-07-16 12:49 UTC
