### ISSUE TITLE
Option to dump config file with all warnings disabled

### ISSUE THREAD

**Issue by nickdrozd** [PyCQA/pylint#7781] opened 2022-11-17 00:34 UTC
### Current problem

Say I just started working on a "legacy" codebase. It was written by people who aren't around anymore, and those people didn't use Pylint. The code is all over the place, and I would like to run Pylint against it. But then I am inundated with a huge wall of warnings. It's difficult to tell what's important and what's just opinion, and in any case there's so much stuff that I don't know where to begin.

One way to deal with this to enable warnings gradually. I don't like this because it requires knowing what warnings there are, and that won't help me for problems that I don't know are problems.

### Desired solution

I would like to be able to run Pylint and then, instead of displaying all the warnings, **dump a config file with all triggered warnings disabled**. Then I can look over that list and enable (i.e. cut the disable) warnings one by one. Perhaps these could be sorted by severity or category.

**Comment by Pierre-Sassoulas** [comment] 2022-11-17 08:25
Duplicate of https://github.com/PyCQA/pylint/issues/5403 but the title is not super clear there.

**Closed by Pierre-Sassoulas** 2022-11-17 08:25 UTC
Labels: Enhancement ✨, Discussion 🤔, topic-usability, Needs design proposal :lock:
