### ISSUE TITLE
``ImportError`` when using PEP 420 namespaces

### ISSUE THREAD

**Issue by zacchiro** [PyCQA/pylint#1667] opened 2017-09-20 09:27 UTC
### Steps to reproduce
1. git clone http://forge.softwareheritage.org/source/swh-core.git
2. export PYTHONPATH=$(pwd)/swh-core
3. pylint3 swh.core

### Current behavior

`ImportError: Unable to find module for /tmp/swh-core/swh/core/api.py in /tmp,`

(or equivalent)

### Expected behavior

Should be able to walk the module and pylint it.
Note that both "import swh.core" and manually pylinting the specific module that pylint claims is not loadable (`pylint3 swh.core.api`) work just fine.

I've given more details about this issue on the code-quality at https://mail.python.org/pipermail/code-quality/2017-September/000937.html (no answer yet at the time of filing this).

I've seen there are a number of PEP 420 related issues, but as far as I can tell they are either supposed to be already fixed in the version of pylint I'm using, or the fail in different ways (e.g., with a proper "cannot load module" message instead of a runaway ImportError exception like in my case).

### pylint --version output

pylint3 1.7.2, 
astroid 1.5.3
Python 3.5.4 (default, Aug 12 2017, 14:08:14) 
[GCC 7.1.0]

**Comment by PCManticore** [comment] 2017-09-21 07:47
Thanks for the report! We do have a couple of issues related to PEP 420, I'll have to take a look to see exactly why this is not working as intended. As you mentioned, linting with ``pylint swh/core`` works fine, but it should work with dot syntax as well.

**Comment by PCManticore** [comment] 2017-09-21 07:49
In the meantime, I'm going to assign this for the next release so we could fix all these PEP 420 problems before releasing 1.8.

**Comment by DanielNoord** [comment] 2022-04-20 13:55
I have tried to reproduce this on `main` but was able to lint the package. Are we sure this is still not fixed?

There are many issues with `namespace` packages but I wonder if this one has been fixed already.

**Comment by Pierre-Sassoulas** [comment] 2022-04-20 15:02
I created a label for namespace-package so we can track and close them. There's probably a lot of near-duplicates.

**Comment by jacobtylerwalls** [comment] 2022-07-02 04:36
Fixed in PyCQA/astroid#1576 -- I'll try to get to a regression test tomorrow.

**Closed** 2022-07-18 06:54 UTC
Labels: Bug :beetle:, Astroid, namespace-package
