### ISSUE TITLE
1.5.2: 'AssertionError: Wrong results for file "wrong_import_order"' on py2.7, and DeprecationWarning on py3k

### ISSUE THREAD

**Issue by sandrotosi** [PyCQA/pylint#763] opened 2016-01-03 14:22 UTC
Hello,
when running unittests on pylint 1.5.2, I got this error on py2.7:

```
======================================================================
FAIL: wrong_import_order (test_functional.LintModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pylint-1.5.2/pylint/test/test_functional.py", line 308, in _runTest
    self.fail('\n'.join(msg))
AssertionError: Wrong results for file "wrong_import_order":

Unexpected in testdata:
  10: wrong-import-order

----------------------------------------------------------------------
Ran 352 tests in 18.853s

FAILED (failures=1, skipped=43)
```

on py3k (both 3.4 and 3.5) there are no errors but there are a big chunk of deprecation warnings (summarized here):

```
morph@oracle:~/deb/pbuilder/result$ grep -i depreca pylint_1.5.2-1_amd64.build | cut -d: -f 3- | sort | uniq -c
      2  DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
      2  DeprecationWarning: 'U' mode is deprecated
      6  PendingDeprecationWarning: 'file' is deprecated and will be removed in astroid 2.0, use 'source_file' instead
      4  PendingDeprecationWarning: future_imports is deprecated and will be removed in astroid 2.0, use the function 'future_imports()' instead.
      1  PendingDeprecationWarning: generator 'infer_attribute' raised StopIteration
      1  PendingDeprecationWarning: generator 'wrapped' raised StopIteration
      2  PendingDeprecationWarning: globals is deprecated and will be removed in astroid 2.0, use the function 'get_locals()' instead.
     10  PendingDeprecationWarning: instance_attrs is deprecated and will be removed in astroid 2.0, use the function 'get_attributes()' instead.
      2  PendingDeprecationWarning: 'instanciate_class()' is deprecated and will be removed in astroid 2.0, use 'instantiate_class()' instead
     58  PendingDeprecationWarning: locals is deprecated and will be removed in astroid 2.0, use the function 'get_locals()' instead.
```

**Comment by PCManticore** [comment] 2016-01-03 15:35
Which astroid version and which OS? This seems to use astroid 1.4.2, but I might be wrong. Ignore for now the warnings that Pylint emits, it didn't have the chance to follow all the changes in astroid.

**Comment by sandrotosi** [comment] 2016-01-03 15:54
it's astroid 1.4.3

**Comment by sandrotosi** [comment] 2016-04-25 19:23
pylint 1.5.5 on debian unstable and astroing 1.4.5 generates this untitest errors

python2.7
```
======================================================================
FAIL: wrong_import_order (test_functional.LintModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pylint-1.5.5/pylint/test/test_functional.py", line 308, in _runTest
    self.fail('\n'.join(msg))
AssertionError: Wrong results for file "wrong_import_order":

Unexpected in testdata:
  15: wrong-import-order

======================================================================
FAIL: ungrouped_imports (test_functional.LintModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pylint-1.5.5/pylint/test/test_functional.py", line 308, in _runTest
    self.fail('\n'.join(msg))
AssertionError: Wrong results for file "ungrouped_imports":

Expected in testdata:
  17: ungrouped-imports

----------------------------------------------------------------------
Ran 360 tests in 20.311s

FAILED (failures=2, skipped=46)
```

python 3.5
```
======================================================================
FAIL: ungrouped_imports (test_functional.LintModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pylint-1.5.5/pylint/test/test_functional.py", line 308, in _runTest
    self.fail('\n'.join(msg))
AssertionError: Wrong results for file "ungrouped_imports":

Expected in testdata:
  17: ungrouped-imports

----------------------------------------------------------------------
Ran 357 tests in 21.973s

FAILED (failures=1, skipped=33)
```

**Comment by PCManticore** [comment] 2016-07-14 10:54
Are these import errors still occurring with Pylint 1.6? During developing the new release, we changed the way in which we consider grouping imports and whatnot, so now it should behave more sanely out of the box.

**Comment by sandrotosi** [comment] 2017-01-05 21:17
this is the last status of deprecation warnings with pylint 1.6.4 with astroid 1.4.8

```
morph@oracle:~/deb/pbuilder/result$ grep -i depreca pylint_1.6.4*build | cut -d: -f 3- | sort | uniq -c
      1  DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
      2  DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
      2  DeprecationWarning: 'U' mode is deprecated
      4  PendingDeprecationWarning: 'file' is deprecated and will be removed in astroid 2.0, use 'source_file' instead
      2  PendingDeprecationWarning: future_imports is deprecated and will be removed in astroid 2.0, use the function 'future_imports()' instead.
      1  PendingDeprecationWarning: generator 'infer_attribute' raised StopIteration
      1  PendingDeprecationWarning: generator 'wrapped' raised StopIteration
      1  PendingDeprecationWarning: globals is deprecated and will be removed in astroid 2.0, use the function 'get_locals()' instead.
      5  PendingDeprecationWarning: instance_attrs is deprecated and will be removed in astroid 2.0, use the function 'get_attributes()' instead.
      1  PendingDeprecationWarning: 'instanciate_class()' is deprecated and will be removed in astroid 2.0, use 'instantiate_class()' instead
     29  PendingDeprecationWarning: locals is deprecated and will be removed in astroid 2.0, use the function 'get_locals()' instead.
```

**Comment by PCManticore** [comment] 2017-07-08 14:42
Since the import errors should not be reproduce any longer, I'm closing this. The deprecations are fine and they'll be gone once we drop 2.7 support (which means we can fix astroid to use the new syntax)

**Closed by PCManticore** 2017-07-08 14:42 UTC
Labels: bug
