### ISSUE TITLE
--output-format=junit does not generates the output

### ISSUE THREAD

**Issue by 81piyush** [PyCQA/pylint#8368] opened 2023-03-02 10:24 UTC
### Bug description
On running pylint (version : **2.16.2**) with parameter `--output-format=junit` does not generates the output.

But running the pylint version **2.14.5** with the same configuration on the same folder/files generates the xml output.

Both executes with below mentioned dependencies (**pylint-junit, junit-xml**) and configuration 

### Configuration
in the **.pylintrc** file:
```
[MAIN]
load-plugins=pylint_junit
```

### Command used
`pylint %cd% --output-format=junit`

### Pylint output
None
![image](https://user-images.githubusercontent.com/57221696/222399095-bd10c5e6-5dbe-4b21-bbec-0bc480ea0614.png)

### Expected behavior
Should generate the xml based results

### Pylint version
pylint 2.16.2
astroid 2.14.2
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]

OS / Environment
Windows10

Additional dependencies
pylint-junit
junit-xml

**Comment by mbyrnepr2** [comment] 2023-03-02 13:23
Thanks @81piyush for the clear report. I can reproduce it and it stopped emitting the xml output in [2.15.0](https://github.com/PyCQA/pylint/milestone/56?closed=1). 
I did some digging around and if I revert [this one](https://github.com/PyCQA/astroid/pull/1514) locally, I begin to see the xml output again. What do you think @jacobtylerwalls?

**Comment by jacobtylerwalls** [comment] 2023-03-02 15:28
I'd be interested to know what `pylint_junit` is doing to produce the output; it could be a downstream issue.

**Comment by Pierre-Sassoulas** [comment] 2023-03-02 15:56
If the issue can be bisected to the commit @mbyrnepr2 linked to, then it probably means that instead of using the proper reporter API ``pylint_junit`` is doing something strange involving capturing stdout and I'm thus tempted to close as won't fix.

**Comment by mbyrnepr2** [comment] 2023-03-03 19:16
The [source code of pylint_junit is in this one module](https://github.com/rasjani/pylint_junit/blob/master/src/pylint_junit/__init__.py). I'm not sure how it may be incorrectly using the pylint reporter API but one thing to note is that there is [an open issue in pylint_junit for this](https://github.com/rasjani/pylint_junit/issues/3) - so perhaps we can close our issue since someone has shared a working solution over there.

**Closed by mbyrnepr2** 2023-03-03 19:16 UTC
Labels: Downstream Bug 🪲

**Comment by MarcSkovMadsen** [comment] 2023-10-12 13:23
Just for the record. I was a pylint2junit user. It had the same problemed introduced in 2.15.

**Comment by Pierre-Sassoulas** [comment] 2023-10-12 14:03
It seems that ``pylint_junit`` is a small reporter class (https://github.com/rasjani/pylint_junit/blob/master/src/pylint_junit/__init__.py) last upgraded 3 years ago. I would integrate the functionality in pylint if someone propose a merge request.

**Comment by MarcSkovMadsen** [comment] 2023-10-12 14:39
Someone just proposed a merge
