### ISSUE TITLE
ImportError: No module named 'conans'

### ISSUE THREAD

**Issue by davnat** [PyCQA/pylint#3833] opened 2020-09-13 20:41 UTC
### TL;DR
It appears that pylint depends on conan, but this dependency is not declared anywhere.

> Is your issue fixed on the preview release?: pip install pylint astroid --pre -U

No

### Steps to reproduce
I use [poetry](https://python-poetry.org) for project management:
1. `$ poetry new demo && cd demo && poetry add --dev pylint`
2. `$ poetry shell` (activates the virtualenv)
3.
```
$ pylint demo
Traceback (most recent call last):
  File "/home/davnat/.cache/pypoetry/virtualenvs/demo-Mc4BfFYU-py3.7/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/davnat/.cache/pypoetry/virtualenvs/demo-Mc4BfFYU-py3.7/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/davnat/.cache/pypoetry/virtualenvs/demo-Mc4BfFYU-py3.7/lib/python3.7/site-packages/pylint/lint/run.py", line 308, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/davnat/.cache/pypoetry/virtualenvs/demo-Mc4BfFYU-py3.7/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 490, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/davnat/.cache/pypoetry/virtualenvs/demo-Mc4BfFYU-py3.7/lib/python3.7/site-packages/astroid/modutils.py", line 203, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/home/davnat/.cache/pypoetry/virtualenvs/demo-Mc4BfFYU-py3.7/lib/python3.7/site-packages/astroid/modutils.py", line 244, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
  File "/usr/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'conans'
```
4. `$ pip install conan`
< ... installation output ... >
5. Now pylint works:
```
$ pylint demo
************* Module demo
demo/__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)

-----------------------------------
Your code has been rated at 0.00/10
```
### pylint --version output
```
pylint 2.6.0
astroid 2.4.2
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0]
```

### Also tried:
Setting `pylint "!=2.6.0` in pyproject.toml installs pylint 2.5.3, but the result is exactly the same

**Comment by dbaty** [comment] 2020-09-14 10:09
pylint does not depend on conan. I cannot reproduce this issue with the provided commands. I am on Linux with these versions:

```
pylint 2.6.0
astroid 2.4.2
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]
```

Based on the traceback, it seems that, in your case, pylint uses a configuration file that has a `load-plugins` option which refers to Conan. Do you have something like that in your `pyproject.toml`? Or perhaps in a global `.pylintrc` that gets picked up by pylint? See [this section in the documentation](http://pylint.pycqa.org/en/latest/user_guide/run.html?highlight=.pylintrc#command-line-options) for a list of configuration files that could be read.

**Comment by davnat** [comment] 2020-09-14 11:30
You are absolutely right: I had a `.pylintrc` in my home with a setting to load a conan pylint plugin.

Maybe the reported error could be more informative than `ImportError: No module named 'conans'`: maybe something like "Error while loading plugins", or even better "Error while loading plugins listed in file ~/.pylintrc"

Thank you, I think this can be closed.

**Comment by hippo91** [comment] 2020-09-14 19:41
@dbaty thanks for your investigation!
@davnat i close this issue but feel free to open another one for suggesting error message improvment.

**Closed by hippo91** 2020-09-14 19:41 UTC
