### ISSUE TITLE
Ignores annotations in else block

### ISSUE THREAD

**Issue by cmhe** [PyCQA/pylint#1566] opened 2017-07-07 08:11 UTC
Version:
```
$ pylint --version
\No config file found, using default configuration
pylint 1.7.2, 
astroid 1.5.3
Python 3.5.3 (default, May 10 2017, 15:05:55) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

Testcase:
```
$ cat test.py
# pylint: disable=missing-docstring
def test(bbb):
    aaa = ''
    if bbb:
        # pylint: disable=no-member
        bbb = aaa.bluber
    else:
        # pylint: disable=no-member
        bbb = aaa.blaber
    return bbb
```

Result:
```
$ pylint test.py
No config file found, using default configuration
************* Module test
E:  9,14: Instance of 'str' has no 'blaber' member (no-member)

------------------------------------------------------------------
Your code has been rated at 1.67/10 (previous run: 1.67/10, +0.00)
```

Expected:
```
$ pylint test.py
No config file found, using default configuration

------------------------------------
Your code has been rated at 10.00/10
```

**Comment by rogalski** [comment] 2017-07-07 12:37
Isn't this duplicate of #872?

**Comment by cmhe** [comment] 2017-07-07 12:50
Yes, seems so. I couldn't find this issue.

**Comment by rogalski** [comment] 2017-07-07 13:14
Closing as a dupe of #872.

**Closed by rogalski** 2017-07-07 13:14 UTC
