### ISSUE TITLE
pylint 2.16 fails on python 3.8.16

### ISSUE THREAD

**Issue by andy-fox-rozettatech** [PyCQA/pylint#8161] opened 2023-02-02 01:40 UTC
### Bug description

pytlint fails itself on python 3.8.     
3.9 and above seem OK

packages/pylint/checkers/imports.py", line 179, in _make_tree_defs
    node[1] += files
TypeError: 'tuple' object does not support item assignment

### Configuration

```ini
github actions (or elsewhere)
python 3.8.16

Collecting pylint
  Downloading pylint-2.16.0-py3-none-any.whl (530 kB)
```

### Command used

```shell
pylint
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/lint/run.py", line 214, in __init__
    score_value = linter.generate_reports()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1149, in generate_reports
    sect = self.make_reports(self.stats, previous_stats)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/reporters/reports_handler_mix_in.py", line 76, in make_reports
    r_cb(report_sect, stats, old_stats)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/checkers/imports.py", line 981, in _report_external_dependencies
    dep_info = _make_tree_defs(self._external_dependencies_info().items())
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/checkers/imports.py", line 179, in _make_tree_defs
    node[1] += files
TypeError: 'tuple' object does not support item assignment
```

### Expected behavior

Not to fail ...

### Pylint version

```shell
pylint 2.16.0
```

### OS / Environment

ubuntu-latest on github actions

but also MacOS 13.2 etc

### Additional dependencies

N/A

**Comment by Pierre-Sassoulas** [comment] 2023-02-02 06:41
Thank you for opening the issue. Can you provide any information about the code pylint was run on when it crashed ?

**Comment by peanutsven** [comment] 2023-02-02 07:16
Same here for python 3.7.3,

**Comment by DanielNoord** [comment] 2023-02-02 07:48
Am I dumb or is this really strange?
https://github.com/PyCQA/pylint/blob/5c0084bb1465fcaed2c977266998360b9f2f5661/pylint/checkers/imports.py#L178-L179

How can `node[1]` be a tuple?

**Comment by MarcSchmitzer** [comment] 2023-02-02 07:56
> How can node[1] be a tuple?

The problem is `node` being a tuple. The `+=` is effectively turned into  
```python
tmp = node[1]
tmp += files
node[1] = tmp
```
and assigning the tuple item does not work.
The code was changed [here](https://github.com/PyCQA/pylint/commit/f29bdd4e04c8c144b378220434646b37a8e7d9a0#diff-7fa3613a0470b923f9ef58f744fbbf64bc7938290be30d5ee58c1f21e0a10bb2) , released in 2.16.

**Comment by DanielNoord** [comment] 2023-02-02 08:04
Yeah that should fix it. Are you able to provide a patch/PR?

**Closed** 2023-02-02 09:33 UTC
Labels: Crash 💥, Needs investigation 🔬

**Comment by Pierre-Sassoulas** [comment] 2023-02-02 09:35
If someone has a reproducer this would still be appreciated as this part of the code is not tested properly right now.

**Comment by MarcSchmitzer** [comment] 2023-02-02 10:32
> If someone has a reproducer this would still be appreciated as this part of the code is not tested properly right now.

I found one. Interestingly, this does not seem related to the interpreter version, but hashseed dependant:

```
$ mkvirtualenv test
created virtual environment CPython3.10.6.final.0-64 in 53ms
...
$ pip install pylint
...
Successfully installed astroid-2.14.1 dill-0.3.6 isort-5.12.0 lazy-object-proxy-1.9.0 mccabe-0.7.0 platformdirs-2.6.2 pylint-2.16.0 tomli-2.0.1 tomlkit-0.11.6 typing-extensions-4.4.0 wrapt-1.14.1
$ touch bar.py
$ echo 'import bar' >foo.py
$ PYTHONHASHSEED='3172416510' pylint --rcfile /dev/null -r y foo.py
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.
************* Module foo
foo.py:1:0: C0104: Disallowed name "foo" (disallowed-name)
foo.py:1:0: W0611: Unused import bar (unused-import)
Traceback (most recent call last):
  File "/home/marc/.venv/test/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/marc/.venv/test/lib/python3.10/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/marc/.venv/test/lib/python3.10/site-packages/pylint/lint/run.py", line 214, in __init__
    score_value = linter.generate_reports()
  File "/home/marc/.venv/test/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1149, in generate_reports
    sect = self.make_reports(self.stats, previous_stats)
  File "/home/marc/.venv/test/lib/python3.10/site-packages/pylint/reporters/reports_handler_mix_in.py", line 76, in make_reports
    r_cb(report_sect, stats, old_stats)
  File "/home/marc/.venv/test/lib/python3.10/site-packages/pylint/checkers/imports.py", line 981, in _report_external_dependencies
    dep_info = _make_tree_defs(self._external_dependencies_info().items())
  File "/home/marc/.venv/test/lib/python3.10/site-packages/pylint/checkers/imports.py", line 179, in _make_tree_defs
    node[1] += files
TypeError: 'tuple' object does not support item assignment
```
