### ISSUE TITLE
pylint major speed regression between Fedora 32 and Fedora 33

### ISSUE THREAD

**Issue by hadess** [PyCQA/pylint#4243] opened 2021-03-17 16:20 UTC
pylint run times increased from tens of seconds to minutes when running the totem test suite after an upgrade from Fedora 32 to Fedora 33.

Using Fedora 32, and `python3-pylint-2.4.4-3.fc32.noarch`

The pylint part of the tests took:
```
5/8 pylint-dbusservice   OK             2.24s
6/8 pylint-opensubtitles OK             24.51s
7/8 pylint-pythonconsole OK             22.69s
8/8 pylint-samplepython  OK             1.49s
```

On my F33 desktop system now (and on the F33 CI runners):
```
 5/10 pylint-dbusservice                   OK             4.45s
 6/10 pylint-opensubtitlesopensubtitles.py TIMEOUT        120.13s
 7/10 pylint-opensubtitleshash.py          OK             6.10s
 8/10 pylint-pythonconsolepythonconsole.py TIMEOUT        120.13s
 9/10 pylint-pythonconsoleconsole.py       OK             56.24s
10/10 pylint-samplepython                  OK             2.92s
```

You can fetch the opensubtitles.py file here for comparison:
https://gitlab.gnome.org/GNOME/totem/-/tree/master/src/plugins/opensubtitles

F32:
```
$ rpm -q pylint python3-pylint
pylint-2.4.4-3.fc32.noarch
python3-pylint-2.4.4-3.fc32.noarch
$ time /usr/bin/pylint-3 -d C0111 -d W0511 -d F0401 -d C0326 -d bad-continuation opensubtitles.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


real	0m1.427s
user	0m1.327s
sys	0m0.059s
```

F33:
```
$ rpm -q pylint python3-pylint
pylint-2.6.0-1.fc33.noarch
python3-pylint-2.6.0-1.fc33.noarch
$ time /usr/bin/pylint-3 -d C0111 -d W0511 -d F0401 -d C0326 -d bad-continuation opensubtitles.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


real	0m12.633s
user	0m12.258s
sys	0m0.288s
```

I filed this bug in the Red Hat bugzilla, but got nowhere:
https://bugzilla.redhat.com/show_bug.cgi?id=1896438

**Comment by Pierre-Sassoulas** [comment] 2021-03-17 21:11
Pylint ``2.7.2`` was included in the latest debian, so this is actually a problem with the latest versions of pylint where there is more checks and poorer performance as a result. I'm going to close as duplicate of #4120 (also related to #4079, #4062, #3982) . We're aware of the situation but there is no silver bullet fix for this.

**Closed by Pierre-Sassoulas** 2021-03-17 21:11 UTC
Labels: topic-performance
