### ISSUE TITLE
Lint all Python files

### ISSUE THREAD

**Issue by AustinScola** [PyCQA/pylint#4289] opened 2021-04-03 13:48 UTC
It would be very convenient to be able to tell pylint to lint all Python files recursively. Maybe with a syntax like `python3 -m pylint .` for example. Instead I often find myself using `find` and piping the files to pylint.

**Comment by Pierre-Sassoulas** [comment] 2021-04-03 14:31
Yes, but it's a duplicate of  the oldest issue in the repo #352

**Closed by Pierre-Sassoulas** 2021-04-03 14:31 UTC
Labels: duplicate

**Comment by AustinScola** [comment] 2021-04-03 14:39
Sorry about that, I did a search but didn't find that one.

**Comment by Pierre-Sassoulas** [comment] 2021-04-03 15:46
No problem :)
