### ISSUE TITLE
Many more no-member warnings with pylint==1.5.2, astroid==1.4.2 and pylint-django==0.7.1

### ISSUE THREAD

**Issue by nedbat** [PyCQA/pylint#754] opened 2015-12-21 12:05 UTC
I'm trying an upgrade of pylint.
Old versions:

```
$ pip freeze | egrep 'astroid|lint'
astroid==1.3.8
edx-lint==0.3.2
pylint==1.4.4
pylint-celery==0.3
pylint-django==0.6.1
pylint-plugin-utils==0.2.3
```

New versions:

```
$ pip freeze | egrep 'astroid|lint'
astroid==1.4.2
edx-lint==0.4.1
pylint==1.5.2
pylint-celery==0.3
pylint-django==0.7.1
pylint-plugin-utils==0.2.3
```

In this repo (https://github.com/edx/edx-platform), I get many more no-member warnings than before.  Lettuce tests show lots:

```
************* Module cms.djangoapps.contentstore.features.component
cms/djangoapps/contentstore/features/component.py:32: [E1101(no-member), see_a_single_step_component] Instance of '_local' has no 'is_css_present' member
cms/djangoapps/contentstore/features/component.py:52: [E1101(no-member), see_a_multi_step_component] Instance of '_local' has no 'wait_for' member
cms/djangoapps/contentstore/features/component.py:52: [E1101(no-member), see_a_multi_step_component.<lambda>] Instance of '_local' has no 'css_find' member
cms/djangoapps/contentstore/features/component.py:63: [E1101(no-member), see_a_multi_step_component] Instance of '_local' has no 'css_html' member
cms/djangoapps/contentstore/features/component.py:66: [E1101(no-member), see_a_multi_step_component] Instance of '_local' has no 'css_text' member
cms/djangoapps/contentstore/features/component.py:73: [E1101(no-member), see_a_problem_component] Instance of '_local' has no 'is_css_present' member
cms/djangoapps/contentstore/features/component.py:79: [E1101(no-member), see_a_problem_component] Instance of '_local' has no 'css_contains_text' member
cms/djangoapps/contentstore/features/component.py:91: [E1101(no-member), delete_all_components] Instance of '_local' has no 'css_find' member
cms/djangoapps/contentstore/features/component.py:97: [E1101(no-member), delete_components] Instance of '_local' has no 'wait_for_xmodule' member
cms/djangoapps/contentstore/features/component.py:103: [E1101(no-member), delete_components] Instance of '_local' has no 'css_click' member
cms/djangoapps/contentstore/features/component.py:105: [E1101(no-member), delete_components] Instance of '_local' has no 'is_css_present' member
cms/djangoapps/contentstore/features/component.py:113: [E1101(no-member), delete_components] Instance of '_local' has no 'css_click' member
cms/djangoapps/contentstore/features/component.py:116: [E1101(no-member), delete_components] Instance of '_local' has no 'is_css_present' member
cms/djangoapps/contentstore/features/component.py:117: [E1101(no-member), delete_components] Instance of '_local' has no 'css_find' member
cms/djangoapps/contentstore/features/component.py:122: [E1101(no-member), see_no_components] Instance of '_local' has no 'is_css_not_present' member
cms/djangoapps/contentstore/features/component.py:127: [E1101(no-member), delete_one_component] Instance of '_local' has no 'css_click' member
cms/djangoapps/contentstore/features/component.py:132: [E1101(no-member), edit_and_save_component] Instance of '_local' has no 'css_click' member
cms/djangoapps/contentstore/features/component.py:133: [E1101(no-member), edit_and_save_component] Instance of '_local' has no 'css_click' member
cms/djangoapps/contentstore/features/component.py:145: [E1101(no-member), duplicated_component] Instance of '_local' has no 'css_click' member
cms/djangoapps/contentstore/features/component.py:153: [E1101(no-member), see_component_in_position.find_problem] Instance of '_local' has no 'css_text' member
cms/djangoapps/contentstore/features/component.py:155: [E1101(no-member), see_component_in_position] Instance of '_local' has no 'wait_for' member
cms/djangoapps/contentstore/features/component.py:161: [E1101(no-member), check_component_display_name] Instance of '_local' has no 'css_html' member
cms/djangoapps/contentstore/features/component.py:167: [E1101(no-member), change_display_name] Instance of '_local' has no 'edit_component_and_select_settings' member
cms/djangoapps/contentstore/features/component.py:168: [E1101(no-member), change_display_name] Instance of '_local' has no 'get_setting_entry_index' member
cms/djangoapps/contentstore/features/component.py:169: [E1101(no-member), change_display_name] Instance of '_local' has no 'set_field_value' member
cms/djangoapps/contentstore/features/component.py:170: [E1101(no-member), change_display_name] Instance of '_local' has no 'save_component' member
cms/djangoapps/contentstore/features/component.py:175: [E1101(no-member), unset_display_name] Instance of '_local' has no 'edit_component_and_select_settings' member
cms/djangoapps/contentstore/features/component.py:176: [E1101(no-member), unset_display_name] Instance of '_local' has no 'revert_setting_entry' member
cms/djangoapps/contentstore/features/component.py:177: [E1101(no-member), unset_display_name] Instance of '_local' has no 'save_component' member
```

Django managers show more:

```
************* Module cms.djangoapps.contentstore.views.tests.test_user
cms/djangoapps/contentstore/views/tests/test_user.py:77: [E1101(no-member), UsersTestCase.test_detail_post] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:92: [E1101(no-member), UsersTestCase.test_detail_post_staff] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:108: [E1101(no-member), UsersTestCase.test_detail_post_staff_other_inst] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:113: [E1101(no-member), UsersTestCase.test_detail_post_staff_other_inst] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:126: [E1101(no-member), UsersTestCase.test_detail_post_instructor] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:151: [E1101(no-member), UsersTestCase.test_detail_post_no_json] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:165: [E1101(no-member), UsersTestCase.test_detail_delete_staff] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:177: [E1101(no-member), UsersTestCase.test_detail_delete_instructor] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:191: [E1101(no-member), UsersTestCase.test_delete_last_instructor] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:206: [E1101(no-member), UsersTestCase.test_post_last_instructor] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:249: [E1101(no-member), UsersTestCase.test_staff_can_delete_self] Instance of 'UserManager' has no 'get' member
cms/djangoapps/contentstore/views/tests/test_user.py:262: [E1101(no-member), UsersTestCase.test_staff_cannot_delete_other] Instance of 'UserManager' has no 'get' member
```

This is a method wrapped with an `@lazy` decorator:

```
************* Module pavelib.assets
pavelib/assets.py:37: [E1101(no-member), configure_paths] Method 'feature_flags' has no 'get' member
pavelib/assets.py:38: [E1101(no-member), configure_paths] Method 'env_tokens' has no 'get' member
pavelib/assets.py:48: [E1101(no-member), configure_paths] Method 'env_tokens' has no 'get' member
pavelib/assets.py:49: [E1136(unsubscriptable-object), configure_paths] Value 'edxapp_env.env_tokens' is unsubscriptable
```

**Comment by PCManticore** [comment] 2015-12-21 16:21
I'm not sure what's happening with UserManager, seems that pylint-django doesn't work anymore?

The issues with ``@lazy`` decorator were fixed with https://github.com/PyCQA/astroid/commit/3a5d8d83c57ef15fae6a5cfc0a2769097090eb32, even though it's an ugly hack, but it will have to do it until we'll implement support for descriptors.

Regarding the problems with _local, they are referring to lettuce.world, which is a threading.local instance. Those missing attributes are added through a decorator, `world.absorb``. I'm not sure how we could infer these changes brought to world.

**Comment by nedbat** [comment] 2016-02-19 18:04
FWIW, this isn't limited to Django and lettuce.  In the same code base, I get this with pylint 1.5.4:
```
common/lib/calc/calc/functions.py:15: [E1101(no-member), sec] Module 'numpy' has no 'cos' member
common/lib/calc/calc/functions.py:22: [E1101(no-member), csc] Module 'numpy' has no 'sin' member
common/lib/calc/calc/functions.py:29: [E1101(no-member), cot] Module 'numpy' has no 'tan' member
common/lib/calc/calc/functions.py:38: [E1101(no-member), arcsec] Module 'numpy' has no 'arccos' member
common/lib/calc/calc/functions.py:45: [E1101(no-member), arccsc] Module 'numpy' has no 'arcsin' member
common/lib/calc/calc/functions.py:52: [E1101(no-member), arccot] Module 'numpy' has no 'real' member
common/lib/calc/calc/functions.py:53: [E1101(no-member), arccot] Module 'numpy' has no 'pi' member
common/lib/calc/calc/functions.py:53: [E1101(no-member), arccot] Module 'numpy' has no 'arctan' member
common/lib/calc/calc/functions.py:55: [E1101(no-member), arccot] Module 'numpy' has no 'pi' member
common/lib/calc/calc/functions.py:55: [E1101(no-member), arccot] Module 'numpy' has no 'arctan' member
common/lib/calc/calc/functions.py:63: [E1101(no-member), sech] Module 'numpy' has no 'cosh' member
common/lib/calc/calc/functions.py:70: [E1101(no-member), csch] Module 'numpy' has no 'sinh' member
common/lib/calc/calc/functions.py:77: [E1101(no-member), coth] Module 'numpy' has no 'tanh' member
common/lib/calc/calc/functions.py:85: [E1101(no-member), arcsech] Module 'numpy' has no 'arccosh' member
common/lib/calc/calc/functions.py:92: [E1101(no-member), arccsch] Module 'numpy' has no 'arcsinh' member
common/lib/calc/calc/functions.py:99: [E1101(no-member), arccoth] Module 'numpy' has no 'arctanh' member
```
The code is not complicated: https://github.com/edx/edx-platform/blob/master/common/lib/calc/calc/functions.py

**Comment by nedbat** [comment] 2016-02-19 18:24
BTW, the numpy failure happens with `unsafe-load-any-extension = yes` in the pylintrc, and with `--extension-pkg-whitelist=numpy` on the command line.

**Comment by PCManticore** [comment] 2016-02-20 22:46
I think I solved your problem with numpy with this change https://github.com/PyCQA/astroid/commit/1d5bf7ec3c74496e2b9b5772cbe953a962ccd3d9. The idea is that we dropped supporting understanding ``__all__``, since it was too hard to keep track of changes brought to it (especially when dynamic modification is involved with globals() and whatnot). Instead, we infer all the public available names when keeping track of the variables of a module, even if this means that some objects are available even though they shouldn't be (because they were not present in ``__all__``)

**Comment by PCManticore** [comment] 2016-02-20 22:48
If my previous comment solves your issue, do you think we should keep this issue open? I don't have an idea how to fix the other two problems, the one with lettuce can be fixed with generated-members, while for Django I have no idea what's happening in pylint-django.

**Comment by nedbat** [comment] 2016-02-21 13:46
Thanks, the astroid change fixes the numpy problem.  The other no-member violations are still present, so I guess this issue should stay open.  The lettuce failures don't point to pylint-django as the problem.  Would it help for me to make a smaller reproducible case?

**Comment by DuncanBetts** [comment] 2017-09-21 09:54
https://github.com/hjwp/book-example/blob/chapter_16_rewrite/lists/views.py#L13
was triggering E1101 (no-member) with pylint==1.7.2, astroid==1.5.3 (and Django==1.11.5).
I installed pylint-django==0.7.2 and added:
let g:ale_python_pylint_options = '--load-plugins pylint_django'
to my vimrc and these E1101 warnings have disappeared.

Thought I'd post here in case this is helpful in moving this along - I can see the title mentions earlier versions of all packages involved.

**Comment by PCManticore** [comment] 2018-01-07 11:42
@nedbat since this is such an old issue, can you still reproduce any of these failures with the latest release? If so, some smaller reproducing cases would be great, as well as separate issues if we identify different causes (e.g if `lettuce` error doesn't seem related to `pylint-django` or Django in general, we could move it into its own issue)

**Comment by PCManticore** [comment] 2018-06-05 15:59
Closing this issue as I'm not sure if these false positives are still happening. Also it would be great to see if `pylint-django` can do something about it. Please reopen if you notice new false positives with Django.

**Closed by PCManticore** 2018-06-05 15:59 UTC
