### ISSUE TITLE
pylint fails in file with DuplicateBaseError

### ISSUE THREAD

**Issue by pmatos** [PyCQA/pylint#1607] opened 2017-08-03 19:45 UTC
### Steps to reproduce
1. Run pylint.
2. Look at result.

### Current behavior

```
$ pylint
...
E:146,30: Value 'self.runs' is unsubscriptable (unsubscriptable-object)
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 26, in cached
    return cache[func]
KeyError: <bound method ClassDef.slots of <ClassDef.JSONOptions l.166 at 0x7f39c320e320>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/cfd-venv/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/checkers/base.py", line 539, in visit_call
    infered = next(node.func.infer())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 138, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/inference.py", line 237, in infer_attribute
    for owner in self.expr.infer(context):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 138, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/inference.py", line 258, in infer_attribute
    for obj in owner.igetattr(self.attrname, context):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 363, in igetattr
    return bases._infer_stmts(self.getattr(name, context),
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 345, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 409, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 172, in _post_build
    self.delayed_assattr(delayed)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 238, in delayed_assattr
    if not _can_assign_attr(inferred, node.attrname):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 81, in _can_assign_attr
    slots = node.slots()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 28, in cached
    cache[func] = result = func(*args, **kwargs)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1745, in slots
    slots = list(grouped_slots())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1730, in grouped_slots
    for cls in self.mro()[:-1]:
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1823, in mro
    return self._compute_mro(context=context)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1808, in _compute_mro
    _verify_duplicates_mro(unmerged_mro, self, context)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 80, in _verify_duplicates_mro
    mros=sequences, cls=cls, context=context)
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (JSONOptions), (CodecOptions, CodecOptions, tuple, object), (CodecOptions) for <ClassDef.JSONOptions l.166 at 0x7f39c320e320>.
```

### pylint --version output

```
No config file found, using default configuration
pylint 1.7.2, 
astroid 1.5.3
Python 3.6.0 (default, Mar 13 2017, 10:26:39) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
```

**Comment by PCManticore** [comment] 2017-08-07 09:49
Hi. Can you add a reproducing example where this fails?

**Comment by pmatos** [comment] 2017-08-09 13:09
@PCManticore Apologies for the delay, reducing the large file took awhile. Here it goes. Put the code in `reduced.py` and run pylint with no other args on it. Versions are as I initally posted. Also, you need latest mongoengine. It seems that it's involved in the failure.

```python
import bson
import mongoengine as me

class Project(me.Document):
    # Model
    name = me.StringField(primary_key=True)
    prjtype = me.StringField(choices=ProjectType.get_available_typenames(), required=True)
    path = me.StringField(required=True)

class ProjectSnapshot(me.Document):
    # Model
    prj = me.ReferenceField(Project, unique_with='revision')
    revision = me.StringField(unique_with='prj')
    selfcheck = me.ReferenceField(TestsuiteRun)
    runs = me.ListField(me.ReferenceField(TestsuiteRun))

    def to_json(self, dereference=True):
        """Return the JSON representation for ProjectSnapshot."""
        if not dereference:
            return super().to_json()

        data = self.to_mongo()
        for i in range(len(data['runs'])):
            data['runs'][i] = self.runs[i].to_mongo()
        return bson.json_util.dumps(data)
```

```bash
$ pylint reduced.py
No config file found, using default configuration
************* Module cfd.reduced
C:  1, 0: Missing module docstring (missing-docstring)
C:  7, 0: Missing class docstring (missing-docstring)
E: 10,37: Undefined variable 'ProjectType' (undefined-variable)
C: 13, 0: Missing class docstring (missing-docstring)
E: 17,34: Undefined variable 'TestsuiteRun' (undefined-variable)
E: 18,42: Undefined variable 'TestsuiteRun' (undefined-variable)
W: 20, 4: Parameters differ from overridden 'to_json' method (arguments-differ)
E: 27,30: Value 'self.runs' is unsubscriptable (unsubscriptable-object)
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 26, in cached
    return cache[func]
KeyError: <bound method ClassDef.slots of <ClassDef.JSONOptions l.166 at 0x7f71d53a70f0>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/cfd-venv/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pylint/checkers/base.py", line 539, in visit_call
    infered = next(node.func.infer())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 138, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/inference.py", line 237, in infer_attribute
    for owner in self.expr.infer(context):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 138, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/inference.py", line 258, in infer_attribute
    for obj in owner.igetattr(self.attrname, context):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 363, in igetattr
    return bases._infer_stmts(self.getattr(name, context),
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 345, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 409, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 172, in _post_build
    self.delayed_assattr(delayed)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 238, in delayed_assattr
    if not _can_assign_attr(inferred, node.attrname):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/builder.py", line 81, in _can_assign_attr
    slots = node.slots()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/decorators.py", line 28, in cached
    cache[func] = result = func(*args, **kwargs)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1745, in slots
    slots = list(grouped_slots())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1730, in grouped_slots
    for cls in self.mro()[:-1]:
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1823, in mro
    return self._compute_mro(context=context)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1808, in _compute_mro
    _verify_duplicates_mro(unmerged_mro, self, context)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 80, in _verify_duplicates_mro
    mros=sequences, cls=cls, context=context)
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (JSONOptions), (CodecOptions, CodecOptions, tuple, object), (CodecOptions) for <ClassDef.JSONOptions l.166 at 0x7f71d53a70f0>.

**Comment by PCManticore** [comment] 2017-08-10 07:16
Thank you @pmatos I think this is a duplicate of https://github.com/PyCQA/pylint/issues/1458, which is already fixed with the latest astroid's code.

**Closed by PCManticore** 2017-08-10 07:16 UTC
Labels: bug, needs_reproduction
