### ISSUE TITLE
Pylint crashes if PySide is loaded with init hook [Regression]

### ISSUE THREAD

**Issue by CarliJoy** [PyCQA/pylint#7616] opened 2022-10-13 16:48 UTC
### Bug description

We are using the `init-hook` to load a venv, so we don't have to install pylint in all project venv and can use pre-commit hooks easier.

Our last pylint version was 
```
pylint 2.13.9
astroid 2.11.7
```

With the update to 
```
pylint 2.15.4
astroid 2.12.11
```
pylint crahses when trying to lint a file that contains a PySide6 import, when adding PySide to `extension-pkg-allow-list`.

To reproduce:

1. Create a venv for your script that contains the required PySide installation.  `python3.10 -m venv qtenv`
```
# pip freeze
PySide6==6.3.2
PySide6-Addons==6.3.2
PySide6-Essentials==6.3.2
shiboken6==6.3.2
```
2. Create a venv with pylint `python3.10 -m venv pylint_env; pylint_env/bin/pip install pylint`
3. Create a simple `testfile.py`
```python
from PySide6.QtCore import Qt
```
4. Try to lint the file (see below)

### Command used

```shell
./pylint_env/bin/pylint --extension-pkg-allow-list=PySide6 --init-hook 'import sys;sys.path.append("/absolute/path/to/qtenv/lib/python3.10/site-packages");sys.path.append("/absolute/path/to/qtenv/lib64/python3.10/site-packages");print(sys.path)'  testfile.py
```

### Pylint output

pylint crashed with a ``AstroidError`` and with the following stacktrace:

```shell
Traceback (most recent call last):
  File "pylint_env/lib64/python3.10/site-packages/astroid/modutils.py", line 590, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, [context])
  File "pylint_env/lib64/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 392, in find_spec
    finder, spec = _find_spec_with_path(
  File "pylint_env/lib64/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 361, in _find_spec_with_path
    raise ImportError(f"No module named {'.'.join(module_parts)}")
ImportError: No module named PySide6.QtCore.Qt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pylint_env/lib64/python3.10/site-packages/pylint/lint/pylinter.py", line 782, in _lint_file
    check_astroid_module(module)
  File "pylint_env/lib64/python3.10/site-packages/pylint/lint/pylinter.py", line 1052, in check_astroid_module
    retval = self._check_astroid_module(
  File "pylint_env/lib64/python3.10/site-packages/pylint/lint/pylinter.py", line 1102, in _check_astroid_module
    walker.walk(node)
  File "pylint_env/lib64/python3.10/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "pylint_env/lib64/python3.10/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "pylint_env/lib64/python3.10/site-packages/pylint/checkers/imports.py", line 523, in visit_importfrom
    self._add_imported_module(node, f"{imported_module.name}.{name}")
  File "pylint_env/lib64/python3.10/site-packages/pylint/checkers/imports.py", line 833, in _add_imported_module
    importedmodname = astroid.modutils.get_module_part(
  File "pylint_env/lib64/python3.10/site-packages/astroid/modutils.py", line 438, in get_module_part
    file_from_modpath(
  File "pylint_env/lib64/python3.10/site-packages/astroid/modutils.py", line 334, in file_from_modpath
    return file_info_from_modpath(modpath, path, context_file).location
  File "pylint_env/lib64/python3.10/site-packages/astroid/modutils.py", line 384, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "pylint_env/lib64/python3.10/site-packages/astroid/modutils.py", line 593, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "pylint_env/lib64/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 392, in find_spec
    finder, spec = _find_spec_with_path(
  File "pylint_env/lib64/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 354, in _find_spec_with_path
    spec = finder_instance.find_module(
  File "pylint_env/lib64/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 203, in find_module
    if util.is_namespace(modname) and modname in sys.modules:
  File "pylint_env/lib64/python3.10/site-packages/astroid/interpreter/_import/util.py", line 42, in is_namespace
    found_spec = _find_spec_from_path(
  File "/usr/lib64/python3.10/importlib/util.py", line 58, in _find_spec_from_path
    return _find_spec(name, path)
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1448, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1222, in __init__
  File "<frozen importlib._bootstrap_external>", line 1238, in _get_parent_path
AttributeError: module 'PySide6.QtCore' has no attribute '__path__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pylint_env/lib64/python3.10/site-packages/pylint/lint/pylinter.py", line 747, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "pylint_env/lib64/python3.10/site-packages/pylint/lint/pylinter.py", line 784, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

Pylint find the import like in the previous version used and does not crash.

### Pylint version

```shell
pylint 2.15.4
astroid 2.12.11
Python 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
```

### OS / Environment

Fedora release 35 (Thirty Five)

## Notes

Using `--unsafe-load-any-extension=y` and/or `--disable=c-extension-no-member` won't crash but it also doesn't find the import and shows.
```
testfile.py:1:0: E0611: No name 'Qt' in module 'PySide6.QtCore' (no-name-in-module)
```

**Comment by CarliJoy** [comment] 2022-10-13 17:02
Installing pylint in the same env as PySide works as expected but this is unfortunately not an option for us.

**Comment by jacobtylerwalls** [comment] 2022-10-14 00:33
Thanks for the report. I'm going to mark this as a duplicate of #7592 because in the next patch release of astroid we're going to include `AttributeError` among the exception types we catch in the relevant portion of `is_namespace`.

**Closed by jacobtylerwalls** 2022-10-14 00:33 UTC
Labels: Crash 💥, Needs investigation 🔬
