### ISSUE TITLE
False positive error reporting for 'async for' statement: cannot understand async generators

### ISSUE THREAD

**Issue by RDobrov** [PyCQA/pylint#2379] opened 2018-08-03 10:30 UTC
### Steps to reproduce
1. Save the following file as `asyncfor.py`
```python
import asyncio

async def a_iter(n):
    """ emits 1 number per second  """
    for i in range(1, n+1):
        yield i
        await asyncio.sleep(1)


async def count_to(n):
    """ counts to n in async manner"""
    async for i in a_iter(n):
        print(i)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    tasks = [loop.create_task(count_to(3)), loop.create_task(count_to(4))]
    loop.run_until_complete(asyncio.wait(tasks))
    loop.close()
```
2. run `pylint asyncfor.py -d C`

### Current behavior
Pylint reports that there is an error:
`asyncfor.py:12:19: E1133: Non-iterable value a_iter(n) is used in an iterating context (not-an-iterable)`

### Expected behavior
No errors for valid async for statements

### pylint --version output
pylint 2.1.0
astroid 2.0.2
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

### Note
Version 2.0.1 doesn't emit any errors for the same code:
```bash
$ pylint asyncfor.py -d C

------------------------------------
Your code has been rated at 10.00/10

$ pylint --version
pylint 2.0.1
astroid 2.0.2
Python 3.6.5 (default, Jun 27 2018, 08:26:32)
[GCC 4.9.2]
```

**Comment by prokher** [comment] 2018-08-07 17:45
I can confirm, we have the same issue with:
```bash
pylint 2.1.1
astroid 2.0.2
Python 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]
```

**Comment by PCManticore** [comment] 2018-08-08 19:09
Hey folks, I can also reproduce this bug. 

The problem is that in 2.1 `pylint` got a bit smarter with respect to `not-an-iterable`, since it can understand when a `for` loop doesn't work with an async iterator and vice versa. But at the same time, it's not yet aware of the fact that `a_iter` is not a normal generator, but rather an async version of it. You can test this problem with the following snippet:

 ```
from astroid import extract_node
n = extract_node('''
async def a_iter(n):
    """ emits 1 number per second  """
    for i in range(1, n+1):
        yield i
        await asyncio.sleep(1)

a_iter(n)
''')
i = next(n.infer())
print(i) # Prints that it's an generator, not an AsyncGenerator
```
In this case, it should infer that the output of `a_iter` is going to be an AsyncGenerator and thus `async for` is perfectly fine for it, but it doesn't do that right now.

**Comment by PCManticore** [comment] 2018-08-16 15:39
This should be fixed with astroid's master.

**Closed** 2018-08-16 15:38 UTC
Labels: astroid, bug
