### ISSUE TITLE
[astroid-error] error when checking type comment like 'type: # comment'

### ISSUE THREAD

**Issue by Ultimanecat** [PyCQA/pylint#7347] opened 2022-08-24 02:09 UTC
### Bug description

Checking the following code would lead to an astroid-error:
```python
a = 1 # type: # any comment
```

This is probably due to a bug in astroid.
In astroid.rebuilder: check_type_comment, when the type comment is parsed as an ast, comment results in a 0-sized body, which leads to an IndexError.

### Command used

```shell
pylint test_crash.py
```

### Pylint output

```shell
Traceback (most recent call last):
  File "d:\codecheck-python\codecheck-pylint13\pylint\lint\pylinter.py", line 1279, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\builder.py", line 133, in file_build
    module, builder = self._data_build(data, modname, path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\builder.py", line 191, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\rebuilder.py", line 279, in visit_module
    [self.visit(child, newnode) for child in node.body],
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\rebuilder.py", line 279, in <listcomp>
    [self.visit(child, newnode) for child in node.body],
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\rebuilder.py", line 624, in visit
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\rebuilder.py", line 825, in visit_assign
    type_annotation = self.check_type_comment(node, parent=newnode)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\astroid-2.11.5-py3.8.egg\astroid\rebuilder.py", line 761, in check_type_comment
    type_object = self.visit(type_comment_ast.body[0], parent=parent)
IndexError: list index out of range
************* Module test_crash
C:\Users\xxx\Desktop\test_crash.py:1:0: F0002: C:\Users\xxx\Desktop\test_crash.py: Fatal error while checking 'C:\Users\xxx\Desktop\test_crash.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\xxx\AppData\Local\pylint\pylint\Cache\pylint-crash-2022-08-24-10.txt'. (astroid-error)
```

### Expected behavior

no crash, no error

### Pylint version

```shell
pylint 2.13.9
astroid 2.11.5
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
```

**Comment by mbyrnepr2** [comment] 2022-08-24 10:06
Thanks @Ultimanecat.

Also reproducible on:
```python
pylint 2.15.0-a0
astroid 2.13.0-dev0
```

**Comment by DanielNoord** [comment] 2022-08-25 09:00
Fixed with https://github.com/PyCQA/astroid/pull/1753.

@Pierre-Sassoulas Since this is a crash should we consider releasing another quick patch version of `astroid` to include this fix in the new `pylint` version?

**Closed** 2022-08-25 09:29 UTC
Labels: Crash 💥, Needs astroid update

**Comment by Pierre-Sassoulas** [comment] 2022-08-25 11:04
Astroid 2.12.4 was released with the fix 🎉

**Comment by DanielNoord** [comment] 2022-08-25 13:26
Thanks for releasing @Pierre-Sassoulas 😄
