### ISSUE TITLE
Crash AttributeInferenceError: 'Value' not found on <ClassDef.Xxx>

### ISSUE THREAD

**Issue by Andrew-Brock** [PyCQA/pylint#6817] opened 2022-06-03 00:09 UTC
### Bug description

Crash when analysing code that had 0 issues detected with pylint 2.13.9 (with some suppressed in both config and comments).

Source code is proprietary so unfortunately can't be shared.

### Configuration

```ini
[FORMAT]
max-args = 10
max-locals = 29
max-statements = 100
max-line-length = 120
max-attributes = 16

[MESSAGES CONTROL]
disable=
    missing-class-docstring,
    missing-function-docstring,
    missing-module-docstring,
    too-few-public-methods,
    use-dict-literal,

[MISCELLANEOUS]
notes=FIXME,XXX

[SIMILARITIES]
min-similarity-lines=8
ignore-comments = yes
ignore-docstrings = yes
ignore-imports = yes
```

### Command used

```shell
cd /app/
pylint my_library
```

### Pylint output

```shell
Exception on node <Attribute.Value l.237 at 0x7f7fd1b669e0> in file '/app/my_library/sub_path/protocol/types/complex.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/astroid/bases.py", line 183, in getattr
    values = self._proxied.instance_attr(name, context)
  File "/usr/local/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2532, in instance_attr
    raise AttributeInferenceError(target=self, attribute=name, context=context)
astroid.exceptions.AttributeInferenceError: 'Value' not found on <ClassDef.TagNumAndValue l.229 at 0x7f7fd1780790>.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pylint/checkers/typecheck.py", line 1086, in visit_attribute
    attr_nodes = owner.getattr(node.attrname)
  File "/usr/local/lib/python3.10/site-packages/astroid/bases.py", line 191, in getattr
    return self._proxied.getattr(name, context, class_context=False)
  File "/usr/local/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2603, in getattr
    raise AttributeInferenceError(
astroid.exceptions.AttributeInferenceError: 'Value' not found on <ClassDef.TagNumAndValue l.229 at 0x7f7fd1780790>.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/usr/local/lib/python3.10/site-packages/pylint/checkers/typecheck.py", line 1099, in visit_attribute
    if not _emit_no_member(
  File "/usr/local/lib/python3.10/site-packages/pylint/checkers/typecheck.py", line 454, in _emit_no_member
    if _enum_has_attribute(owner, node):
  File "/usr/local/lib/python3.10/site-packages/pylint/checkers/typecheck.py", line 589, in _enum_has_attribute
    dunder_new, returned_obj_name.name
AttributeError: 'Call' object has no attribute 'name'
```

### Expected behavior

Not crash. Pylint 2.13.9 gave no issues with the code (with some issues suppressed both in config and with `#pylint: disable=xxx`)

### Pylint version

```shell
pylint 2.14.0
astroid 2.11.5
Python 3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]
```

### OS / Environment

```shell
$ uname -a
Linux 74b741bf413b 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 Linux
```

Running in Docker with `FROM python:3.10.4-alpine`.

### Additional dependencies

astroid==2.11.5
attrs==21.4.0
bandit==1.7.4
black==22.3.0
click==8.1.3
-e/app
coverage==6.4.1
dill==0.3.5.1
flake8==4.0.1
flake8-isort==4.1.1
gitdb==4.0.9
GitPython==3.1.27
iniconfig==1.1.1
isort==5.10.1
lazy-object-proxy==1.7.1
mccabe==0.6.1
mypy==0.960
mypy-extensions==0.4.3
packaging==21.3
pathspec==0.9.0
pbr==5.9.0
platformdirs==2.5.2
pluggy==1.0.0
py==1.11.0
pycodestyle==2.8.0
pyflakes==2.4.0
pylint==2.14.0
pyparsing==3.0.9
pytest==7.1.2
pytest-cov==3.0.0
pytest-mock==3.7.0
PyYAML==6.0
smmap==5.0.0
stevedore==3.5.0
testfixtures==6.18.5
tomli==2.0.1
tomlkit==0.11.0
types-PyYAML==6.0.8
typing_extensions==4.2.0
wrapt==1.14.1

**Comment by jacobtylerwalls** [comment] 2022-06-03 00:14
Thanks for the report. Turns out to be a duplicate of #6805. I'll go try to spruce up the title on the other one :-)

**Closed by jacobtylerwalls** 2022-06-03 00:14 UTC
Labels: needs triage
