### ISSUE TITLE
`no-member` when using class in list comprehension inside compount assignment of list with nesting level of more than 2

### ISSUE THREAD

**Issue by actionless** [PyCQA/pylint#1829] opened 2018-01-09 01:53 UTC
### Steps to reproduce
```python
class Plugin(object):
    name = 'foo'

def main():
    plugins = [Plugin(), Plugin()]
    result = []
    result += [
        [
            [
                plugin.name for plugin in plugins
            ]
        ]
    ]
``` 

### Current behavior
```
E: 17,28: Instance of 'list' has no 'name' member (no-member)
```

### Note
With a less nesting level it's passing pylint check:
```python
class Plugin(object):
    name = 'foo'

def main():
    plugins = [Plugin(), Plugin()]
    result = []
    result += [
        [
            plugin.name for plugin in plugins
        ]
    ]
```

This example also passing pylint check:
```python
class Plugin(object):
    name = 'foo'

def main():
    plugins = [Plugin(), Plugin()]
    result = []
    result2 = [
        [
            [
                plugin.name for plugin in plugins
            ]
        ]
    ]
    result += result2
```

### pylint --version output
```
No config file found, using default configuration
pylint 1.8.1,
astroid 1.6.0
Python 3.6.4 (default, Dec 23 2017, 19:07:07)
[GCC 7.2.1 20171128]
```

**Comment by brycepg** [comment] 2018-01-13 05:15
Similar to #1433

**Comment by actionless** [comment] 2018-01-13 15:00
in my case it's not reproduciable with just compound assignment -- it also depends on nesting level (that aspect is not described in another issue)

**Comment by PCManticore** [comment] 2018-01-19 16:49
Thanks for the report, I can also reproduce the issue

**Comment by mbyrnepr2** [comment] 2022-01-17 18:49
I can't reproduce with the latest Pylint; can be closed?

**Comment by DanielNoord** [comment] 2022-01-17 21:59
Thanks @mbyrnepr2! Closing this :)

**Closed by DanielNoord** 2022-01-17 21:59 UTC
Labels: Bug 🪳
