### ISSUE TITLE
how to raise exceptions within function that also returns something when no exception occurs

### ISSUE THREAD

**Issue by Harish-Sridhar-kpn** [PyCQA/pylint#3946] opened 2020-11-16 22:53 UTC
## Question
how to raise exceptions within function that also returns something when no exception occurs

Lets say i have a function like below:

```
function foo(value):
     if value != "foo":
        raise RuntimeError("expected foo!")
     return "bar"

val = foo("foo")

```
This function is causing pylint to complain that the function doesn`t return anything.
The function returns something, but only under certain situations.
How do we handle this scenario? How to avoid pylint complain here.

**Comment by dbaty** [comment] 2020-11-17 15:20
Your code snippet is not valid Python (because of the `function` word instead of `def`). If I fix it like this:

```
def foo(value):
    if value != "foo":
        raise RuntimeError("expected foo!")
    return "bar"

val = foo("foo")
```

... pylint does **not** emit the `assignment-from-no-return` warning (which, I suppose, is what you are referring to).

Can you provide a valid snippet and the exact error message that you think is incorrect?

**Comment by Harish-Sridhar-kpn** [comment] 2020-11-26 16:53
After i bumped into this, i did some code refactoring and didn't capture the actual code that was causing the issue.
But now, i have once again bumped into this one.

Here is the code snipped where i get this issue

```
import random

class ABC:

    def fetch_message(self, timeout: float = 1.0):
        msg = random.choice(range(1,100))
        if msg is not None and msg % 2 == 0:
            if msg % 4 == 0:
                return None
            else:
                raise ValueError("error fetching message from kafka: {}".format(msg.error()))
        return msg

    def consume(self, timeout=1.0):
        # i get a warning the function fetch_message doesn't return anything.
        msg = self.fetch_message(timeout)
        return msg
```

**Comment by dbaty** [comment] 2020-11-26 17:04
I still cannot reproduce. Here is what the latest version of pylint reports:

```
test.py:10:12: R1705: Unnecessary "else" after "return" (no-else-return)
test.py:7:28: W0613: Unused argument 'timeout' (unused-argument)
test.py:7:4: R0201: Method could be a function (no-self-use)
```

I suppose that you get a `assignment-from-no-return` warning, but I don't.

Can you double-check that pylint reports a warning with this code snippet? If so, can you provide pylint output? Also, please provide the output of `pylint --version`.

**Comment by Harish-Sridhar-kpn** [comment] 2020-11-26 23:58
I think this is not an issue with pylint, but intellij pycharm inspection. 
below is the description of the warning that i get
```
This inspection is similar to pylint inspection E1111. It highlights situations when an assignment is done on a function call but the inferred function doesn't return anything.
```
I overlooked the word `similar to` and i thought pylint is complaining.

Sorry for wasting your time @dbaty

**Comment by dbaty** [comment] 2020-11-27 09:11
That's all right. :)

If the problem is not related to pylint, you may close this issue.

**Comment by Pierre-Sassoulas** [comment] 2020-11-30 17:29
Closing because it's not related to pylint.

**Closed by Pierre-Sassoulas** 2020-11-30 17:29 UTC
Labels: cannot reproduce
