### ISSUE TITLE
report filename being checked

### ISSUE THREAD

**Issue by techtonik** [PyCQA/pylint#1414] opened 2017-04-09 06:52 UTC
For debugging `pylint` crashes and hangs, it is convenient to make it report the filename that is being processed.

http://stackoverflow.com/questions/43076534/report-filename-that-is-being-checked/43084405#43084405

### pylint --version output
(1,4,1)
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/third_party/pylint/__pkginfo__.py

**Comment by rogalski** [comment] 2017-04-10 10:53
Maybe correct approach would be to attach this information as an attribute of exception raised during parsing? Maybe implement custom `__repr__` along with it.

**Comment by The-Compiler** [comment] 2017-04-10 11:48
What exception?

**Comment by techtonik** [comment] 2017-04-10 12:12
In my case `pylint` just hanged on `bdb` files from standard library, so no exceptions was thrown.

**Comment by Pierre-Sassoulas** [comment] 2022-06-29 18:52
Closing as duplicate of https://github.com/PyCQA/pylint/issues/1554

**Closed by Pierre-Sassoulas** 2022-06-29 18:52 UTC
Labels: Enhancement ✨
