### ISSUE TITLE
inconsistent-return-statements with if inside try/except

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#1770] opened 2017-12-15 15:20 UTC
On pylint 1.8.1, astroid 1.6.0 with this file:

```python
def foo(n):
    try:
        if n == 1:
            return 'a'
        elif n == 2:
            return 'b'
        else:
            raise ValueError
    except AssertionError:
        return None
```

I get `inconsistent-return-statements`. Unless I'm missing something, all possible branches either return a value, or raise an exception, right?

(Nice check, by the way! Helped me to spot various places where I used `return` or an implicit return mixed with explicit ones)

cc @hippo91

**Comment by hippo91** [comment] 2017-12-16 09:39
Thanks @The-Compiler!
It seems to be a bug.
I'll check it ASAP.

**Comment by hippo91** [comment] 2017-12-16 09:39
Oups ... i didn't want to close it...

**Closed** 2017-12-28 14:38 UTC
Labels: bug

**Comment by BlitzKraft** [comment] 2019-07-03 07:25
I am using pylint 2.3.1, this bug still exists. I am using a function similar to the example in the first comment (An if-else nested in a try-except). This goes away if I add another return statement outside of the try-except, but inside the function.

**Comment by hippo91** [comment] 2019-07-06 10:07
@BlitzKraft thanks for your remark.
Can you send a precise example of your code please?

**Comment by BlitzKraft** [comment] 2019-07-07 00:23
This is my example:

```python
    def image_serve(request, file=''): 
        filedir = os.path.dirname(os.path.join(settings.MEDIA_ROOT, str(file)))
        real_image= filedir + '/' + file
    ​
        try:
            image_field = Image.open(real_image)
            if image_field:
                image_field = open(real_image, "rb")
                response = HttpResponse(image_field, content_type="image/jpeg")
                response['Content-Disposition'] = 'inline; filename=' + str(real_image)
                return response
            else: 
                return HttpResponse("No such image")
        except IOError:
            return HttpResponse("No such image")
        # uncommenting the following return will get rid of the above pylint warning
        # return HttpResponse("IOError")
```

Functionally identical to the first example in this issue.

**Comment by hippo91** [comment] 2019-07-08 12:25
@BlitzKraft i'm unable to reproduce the bug.
As i do not have Django installed, i tried to reproduce it with the following code :
```
def image_serve(request):
    try:
        answer = request == 4
        if answer:
            return "OK"
        else:
            return "No such file"
    except IOError:
        return "No such file"
```
Could you please try with this piece of code too?
What version of `pylint` do you use?
Thanks in advance

**Comment by BlitzKraft** [comment] 2019-07-09 00:43
I am unable to reproduce the error too. It's possible I was using a wrong virtual env with an old version of pylint. My pylint version is 2.3.1. I thought it was 2.3.1 when I first made the comment. 

Likely the problem is my fault and using the correct version of pylint fixes it. Thank you for the help.

**Comment by hippo91** [comment] 2019-07-09 07:13
@BlitzKraft you'are welcome!

**Comment by eftalgezer** [comment] 2022-09-22 14:55
This bug still exists.

**Comment by DanielNoord** [comment] 2022-09-22 15:04
Without any reproducing code we're unlikely to be able to solve an issue. As this has been closed quite some time ago and new issues didn't actually lead to the return of the issue I think it might be better to open a new issue if you have reproducing code.
