### ISSUE TITLE
Find similarities within files

### ISSUE THREAD

**Issue by dgutson** [PyCQA/pylint#7439] opened 2022-09-09 05:00 UTC
### Current problem

I'm trying to find code clones within a single file, but symilar needs at least two files. Comparing twice the same file brings 100% of duplication, as expected.

### Desired solution

I want to be able to provide a single file in the arguments, meaning that symilar should find similarities within that file.

Tag @qequ .

**Comment by dgutson** [comment] 2022-09-09 05:20
Maybe this could be also a command line flag `--scan-self` and yet provide a list of file names, meaning that similarity scanning will _also_ occur within each provided file

**Comment by mbyrnepr2** [comment] 2022-09-09 06:58
Thanks for the report. It looks like a duplicate of https://github.com/PyCQA/pylint/issues/1457

**Closed** 2022-09-09 07:09 UTC
Labels: Duplicate 🐫
