### ISSUE TITLE
New check suggestion : mutable default values when using typings.NamedTuple

### ISSUE THREAD

**Issue by Lucas-C** [PyCQA/pylint#3764] opened 2020-08-05 18:44 UTC
### Is your feature request related to a problem? Please describe
Consider this code:
```python
from typing import NamedTuple

class Test(NamedTuple):
    mutable : dict = {}

t1 = Test(); t1.mutable[0] = 1
t2 = Test(); print(t2)
```

This code does not behave as it could be expected at first look,
as it displays `Test(mutable={0: 1})`

### Describe the solution you'd like
I suggest a new `forbid-named-tuple-mutable-field` that would check for usage of basic mutable datastructures
(`dict`, `list`) as default values in subclasses of `typing.NamedTuple`.

### Additional context
I'm creating this issue to record the idea and get feedback on it.
I probably won't implement this check myself unless other users are interested.

**Comment by AWhetter** [comment] 2020-09-07 22:38
I think that we can check for this in the existing `dangerous-default-value` message because it describes the same situation. What's written is basically syntactic sugar for `def __init__(self, mutable={}):`, which is what `dangerous-default-value` checks for.

**Comment by AWhetter** [comment] 2020-09-08 05:04
I'm closing this as a duplicate of #3716

**Closed by AWhetter** 2020-09-08 05:04 UTC
Labels: enhancement
