### ISSUE TITLE
E0602 when assigning a lambda with the same name

### ISSUE THREAD

**Issue by cigix** [PyCQA/pylint#931] opened 2016-06-07 10:06 UTC
When creating a function with a lambda, pylint does not consider already defined variables with the same name: 

``` python
def myfunc(x):
    print(x * 2)

myvar = 2

class myclass:
    # E:  8,23: Undefined variable 'myfunc' (undefined-variable)
    myfunc = lambda x: myfunc(x)
    # E:  10,32: Undefined variable 'myvar' (undefined-variable)
    myvar = lambda x: print(x * myvar)

myclass.myfunc(21)
myclass.myvar(333)
```

However this code runs fine.
### pylint --version output

``` bash
$ pylint --version
pylint 1.5.6, 
astroid 1.4.6
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
```

This was encountered alongside, and may be linked with, #848.
This may also be linked to #851.

**Comment by PCManticore** [comment] 2016-06-14 10:45
Yeah, I can reproduce it as well. I'm adding it for 2.1 though (the next milestone after the current one).

**Comment by mbyrnepr2** [comment] 2022-01-16 20:50
I can't reproduce this on the latest pylint; no `undefined-variable` errors are emitted for the reported example code. Perhaps we can close the issue.

**Comment by Pierre-Sassoulas** [comment] 2022-01-16 21:03
I can't reproduce either, thank you @mbyrnepr2

**Closed** 2022-01-16 21:02 UTC
Labels: Bug 🪳
