### ISSUE TITLE
False Error : Undefined Variable in lambda function of another lambda function

### ISSUE THREAD

**Issue by weez15** [PyCQA/pylint#1791] opened 2017-12-22 03:53 UTC
### Steps to reproduce
This line should not report any error but pylint sees it as an error:
`function = lambda a: lambda b: a * b`

### Current behavior
E0602:Undefined variable 'a'

### Expected behavior
No Error

### pylint --version output
No config file found, using default configuration
pylint 1.7.4,
astroid 1.5.3
Python 3.6.4 (default, Dec 19 2017, 15:26:29)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

**Comment by PCManticore** [comment] 2017-12-24 15:56
Duplicate of #760

**Closed by PCManticore** 2017-12-24 15:56 UTC
