### ISSUE TITLE
optional import of subpackages

### ISSUE THREAD

**Issue by svenkreiss** [PyCQA/pylint#4361] opened 2021-04-15 09:05 UTC
### Steps to reproduce

Pylint is happy but `scipy.ndimage` is not imported:

```
try:
    import scipy
except ImportError:
    scipy = None
```

Need the import below to make `scipy.ndimage` available, but pylint complains:

```
try:
    import scipy.ndimage  # <--- need to import ndimage like this otherwise not imported
except ImportError:
    scipy = None
```

Pylint: `C0103: Constant name "scipy" doesn't conform to UPPER_CASE naming style (invalid-name)`

### Expected behavior (updated)

When I run pylint, I want the output to be:

```
```

### Context

I am making scipy an optional dependency in OpenPifPaf: https://github.com/openpifpaf/openpifpaf/pull/390

**Comment by dbaty** [comment] 2021-04-19 14:24
In the second form, you define two different symbols: `scipy.ndimage` if scipy is installed; `scipy` otherwise. How do you cope with this discrepancy in the rest of the module?

I would suggest doing something like this:

```python
try:
    import scipy.ndimage as scipy_ndimage
except ImportError:
    scipy_ndimage = None

def foo():
    if scipy_ndimage:
         return scipy_ndimage.frobulate()
    return 2  # good approximation of the frobulation algorithm without scipy
```

Alternatively:


```python
try:
    import scipy
    import scipy.ndimage
except ImportError:
    scipy = None

def foo():
    if scipy:
         return scipy.ndimage.frobulate()
    return 2  # good approximation of the frobulation algorithm without scipy
```

(It's untested and I hope it's not too far from something that would work!)

**Comment by hippo91** [comment] 2021-05-13 17:22
@svenkreiss thanks for you report.
@dbaty thanks for your research and explanation. 
@svenkreiss are you ok with @dbaty's advice?
If so i will close the issue.

**Comment by svenkreiss** [comment] 2021-05-13 17:36
@dbaty I didn't follow your two different symbols argument. When I import `scipy.ndimage` then that is not just one thing. After the import, I do have access to `scipy` as well:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/2775078/118163285-18a0a100-b422-11eb-8249-83c6031b17de.png">

I'd argue that my original code is valid and should not fail pylint.

**Comment by Pierre-Sassoulas** [comment] 2021-05-14 17:31
I don't understand this issue, what would you want pylint to do exactly ? Not raise a `C0103: Constant name "scipy" doesn't conform to UPPER_CASE naming style` on `scipy = None` ? There is an issue template for a reason.

**Comment by svenkreiss** [comment] 2021-05-17 05:37
Yes, I don't want pylint to raise this C0103. 

I have updated the report with the relevant part from the issue template (apologies @Pierre-Sassoulas ).

**Comment by Pierre-Sassoulas** [comment] 2022-07-01 21:13
Thank you for the clarification @svenkreiss, I'm going to close as duplicate of #3585 .

**Closed by Pierre-Sassoulas** 2022-07-01 21:13 UTC
Labels: Enhancement ✨, False Positive 🦟
