### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by owillebo** [PyCQA/pylint#6796] opened 2022-06-02 11:31 UTC
### Bug description

Running with -j !- 1 results in endless RecursionError stack traces.

pylint -j1 empty.py gives expected output

pylint -j2 empty.py gives endless RecursionError stack traces.

empty.py is an empty file.

### Command used

```shell
pylint -j2 empty.py
```

### Pylint output

```shell
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python39\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\parallel.py", line 61, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "C:\Program Files\Python39\lib\site-packages\dill\_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "C:\Program Files\Python39\lib\site-packages\dill\_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Program Files\Python39\lib\site-packages\dill\_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "C:\Program Files\Python39\lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Program Files\Python39\lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Program Files\Python39\lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python39\lib\multiprocessing\pool.py", line 109, in worker
...
endless
```

### Expected behavior

************* Module empty
empty.py:1:0: C0305: Trailing newlines (trailing-newlines)

### Pylint version

```shell
Bug present in;
pylint 2.14.0 and pylint 2.13.9
astroid 2.11.5
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

Bug NOT present in;
pylint 2.12.2
astroid 2.9.3
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

### OS / Environment

Windows 11 Pro

**Comment by DanielNoord** [comment] 2022-06-02 11:42
Duplicate of https://github.com/PyCQA/pylint/issues/6012.

**Closed by DanielNoord** 2022-06-02 11:42 UTC
Labels: needs triage
