### ISSUE TITLE
Use before assignment not detected

### ISSUE THREAD

**Issue by Hibou57** [PyCQA/pylint#1807] opened 2017-12-31 01:10 UTC
### Steps to reproduce

Check this with Pylint:

    def test(a):
        if a == 1:
            b = 2
        return 3 if b else 4

### Current behavior

Does not warn `b` is used without (very probably) being assigned (more below).

### Expected behavior

Opinions may vary, still here is mine: I know too many false alerts is at the detriment of alerts in the large. I know there use to be a Borland C++ compiler triggering annoying and noisy warnings when an assignment was conditional, which seems to be a case very close to this one. But there is only one condition, so clearly it can’t cover all cases. The probability `b` is not assigned, is high.

### pylint --version output

> pylint 1.7.4, 
> astroid 1.5.3
> Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
> [GCC 5.4.0 20160609]

### Note

I’m not telling about it as a bug, rather a an hint.

**Comment by PCManticore** [comment] 2018-01-03 10:40
This makes sense, but we could only detect it in a sane manner once we land control flow support in pylint.

**Comment by Hibou57** [comment] 2018-01-07 20:31
@PCManticore , don’t worry too much, PyLint is already very clever even without it.

**Comment by jacobtylerwalls** [comment] 2021-12-04 15:44
Duplicate of #1727 and #267.

**Comment by Pierre-Sassoulas** [comment] 2021-12-04 19:25
Closing as a duplicate of #1727, it's old but the discussion happened elsewhere. (Thank you @jacobtylerwalls for helping us cleanup)

**Closed by Pierre-Sassoulas** 2021-12-04 19:25 UTC
Labels: enhancement, topic-control-flow, duplicate
