### ISSUE TITLE
problem with properties

### ISSUE THREAD

**Issue by wrohdewald** [PyCQA/pylint#1334] opened 2017-02-19 23:33 UTC
### Steps to reproduce
1. pylint -E the attached script.

This is a minimal example.

[x.py.txt](https://github.com/PyCQA/pylint/files/786295/x.py.txt)

### Current behavior
E: 11, 8: Method 'a' has no 'save' member (no-member)

### Expected behavior
there is no error. Python3.5.2 cann execute it without error.

### pylint --version output
pylint and astroid are current git master

pylint 2.0.0, 
astroid 1.5.0
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927]

**Comment by PCManticore** [comment] 2017-02-21 15:40
Closing as duplicate of https://github.com/PyCQA/pylint/issues/870. Thanks for the issue!

**Closed by PCManticore** 2017-02-21 15:40 UTC
