### ISSUE TITLE
Recognize ``__init__.pyi`` to lint stub files

### ISSUE THREAD

**Issue by jolaf** [PyCQA/pylint#2873] opened 2019-04-17 12:20 UTC
I'm creating `*.pyi` stubs for large libraries and I'd like to use `pylint` (as well as `mypy`) to make sure the stubs are clean.

The files I'm trying to lint are located in a directory hierarchy having `__init__.pyi` file in each subdirectory. Unfortunately, `pylint` only detects `__init__.py` as a "submodule root" and treats `__init__.pyi` as a regular file, not a submodule root, so it can't properly recognized objects defined in them.

I would suggest the following behaviour:

- If import of an object from a module is located in a `.py` file, the source code for that object should be looked up in a corresponding `__init__.py` file, as it is now.

- If import of an object from a module is located in a `.pyi` file, the source code for that object should be looked up in a corresponding `__init__.pyi` file, not `__init__.py` file, as it is does now.

**Comment by PCManticore** [comment] 2019-07-07 08:00
This probably makes sense. It would require some re-engineering of the import system though so might not be trivial to accomplish.

**Comment by clavedeluna** [comment] 2022-11-08 10:29
Is this issue a duplicate of #4987 , vice versa?

**Comment by Pierre-Sassoulas** [comment] 2022-11-08 11:04
Closing as duplicate of #4987 which is more detailed and pinned, thank you @clavedeluna .

**Closed by Pierre-Sassoulas** 2022-11-08 11:04 UTC
Labels: Enhancement ✨, Astroid, topic-import-system, High priority, Needs PR
