### ISSUE TITLE
wrong 'undefined-variable' in nested lambda

### ISSUE THREAD

**Issue by foreverbell** [PyCQA/pylint#905] opened 2016-05-14 06:37 UTC
The following `python3` code triggers `pylint` to report `E:  1,34: Undefined variable 'v' (undefined-variable)`.

``` python
fs = map(lambda v: (lambda: print(v)), [1,2,3])
for f in fs:
  f()
```

``` bash
$ python3 -m pylint --version
__main__.py 1.5.5, 
astroid 1.4.5
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]
```

**Comment by PCManticore** [comment] 2016-05-15 11:57
Thank you.

**Comment by degustaf** [comment] 2016-12-30 02:36
This appears to be a duplicate of issue #760.

**Comment by PCManticore** [comment] 2017-01-22 09:37
Thank you @degustaf

**Closed by PCManticore** 2017-01-22 09:37 UTC
