### ISSUE TITLE
Flask-SQLAlchemy has no member

### ISSUE THREAD

**Issue by elamje** [PyCQA/pylint#2987] opened 2019-06-30 02:46 UTC
### Steps to reproduce
1. Use SQLAlchemy in Flask App
2. Refer to member of SQLAlchemy

### Current behavior
`[pylint] Instance of 'SQLAlchemy' has no 'Column' member`

### Expected behavior
No error

### pylint --version output
pylint 2.3.1
astroid 2.2.5
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)
[Clang 6.0 (clang-600.0.57)]

**Comment by PCManticore** [comment] 2019-09-26 07:56
Closing as duplicate of https://github.com/PyCQA/pylint/issues/2917. I'm not sure what the purpose of this issue is given the other one, plus it has no reproduction examples at all.

**Closed by PCManticore** 2019-09-26 07:56 UTC
