### ISSUE TITLE
Use case missing for unused-argument check

### ISSUE THREAD

**Issue by sushobhit27** [PyCQA/pylint#2146] opened 2018-05-25 08:43 UTC
### Steps to reproduce
1. $ cat sample1.py
```python
def foo(a, b):
    a = 666
    return a + b
```
2. $ pylint sample1.py --disable=blacklisted-name --enable=unused-argument

### Current behavior
-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 6.67/10, +3.33)

### Expected behavior
There should be a warning that original value from parameter 'a' is not used or overridden.

### pylint --version output
pylint 2.0.0
astroid 1.6.3
Python 3.6.4 (default, Jan  7 2018, 15:53:53)
[GCC 6.4.0]

**Comment by PCManticore** [comment] 2018-05-31 04:07
Makes sense to have this as a check or as an addition to `unused-argument` as it might result in a surprising bug if the function is complicated enough.

**Comment by sushobhit27** [comment] 2018-05-31 04:53
@PCManticore ok I will pick up this issue then.

**Comment by sushobhit27** [comment] 2018-08-02 12:27
@PCManticore Is there something like is_name_used_in_parent_scope in utils, as this functionality will help in resolving both this and #2223

**Comment by clavedeluna** [comment] 2022-11-08 10:08
I believe this is a duplicate of #3102

**Comment by Pierre-Sassoulas** [comment] 2022-11-08 11:33
Closing as duplicate because the discussion in the other issue is more detailed, thank you @clavedeluna .

**Closed by Pierre-Sassoulas** 2022-11-08 11:33 UTC
Labels: Enhancement ✨, Checkers, Needs PR
