### ISSUE TITLE
Pylint underlines @, if it is the first character on the new line

### ISSUE THREAD

**Issue by nazariydolfin** [PyCQA/pylint#2953] opened 2019-06-11 12:05 UTC
### Steps to reproduce
Write code like this:
```
    portfolio_risk = (
        pd.DataFrame.from_dict(
            assets_weights,
            orient="index",
            columns=["Portfolio"],
        ).T
        @ risk
    )
```

### Current behavior
Pylint will underline in red starting from T and ending on the closing ). Even though this is the correct syntax.

### Expected behavior
Does not highlight this portion in red.

### pylint --version output
pylint==2.3.1
astoid==2.2.5

**Comment by nazariydolfin** [comment] 2019-06-14 12:05
Same set up as above, different issue:

```
class RiskEncoder(json.JSONEncoder):
    def default(self, o):
        try:
            return super().default(o)
        except:
            return dict(o)
```

Underlines in red the def method with a message:

`An attribute defined in json.encoder line 158 hides this method pylint (method-hidden)`

for 

`jsonschema==3.0.1`

**Comment by AWhetter** [comment] 2019-06-15 02:46
What do you mean by pylint will underline the code in red? Are you using pylint through an IDE? What warning does pylint show?
I am unable to reproduce the problem with the version of pylint on the master branch. Please could you confirm this.

The second issue is a duplicate of #414

**Comment by nazariydolfin** [comment] 2019-06-17 08:31
Yes, using the VSCode with pylint.

`Unexpected token 'risk' Python(parser-16)`

and on the closing bracket:

`Unexpected token ')' Python(parser-16)`

They are all Python(parser-16), is this actually pylint?

**Comment by PCManticore** [comment] 2019-06-20 09:03
@nazariydolfin The `Unexpected token` doesn't look like a Pylint error. There must be something else going on with your VSCode setup.

**Closed** 2019-07-07 07:29 UTC
