### ISSUE TITLE
Pylint incorrectly interprets defaultdict.default_factory as not callable

### ISSUE THREAD

**Issue by davidjlloyd** [PyCQA/pylint#1814] opened 2018-01-03 16:06 UTC
### Steps to reproduce

Run pylint on the following code with E1102 (not-callable) enabled:

```
from collections import defaultdict

TEST = defaultdict(tuple)

if callable(TEST.default_factory):
	print TEST.default_factory()
```

### Current behavior

Produces the following error:

```
E:  6, 7: DDICT.default_factory is not callable (not-callable)
```

If I define a custom class which behaves like `defaultdict` I do not get this error, so it appears that this issue arises from the fact that `defaultdict` is a builtin.

### Expected behavior

No linting errors.

### pylint --version output

pylint 1.7.1, 
astroid 1.5.3
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]

**Comment by PCManticore** [comment] 2018-01-03 16:39
Duplicate of https://github.com/PyCQA/pylint/issues/436

**Closed by PCManticore** 2018-01-03 16:39 UTC
