### ISSUE TITLE
False positives when inheriting a generic parent class

### ISSUE THREAD

**Issue by julaudo** [PyCQA/pylint#5538] opened 2021-12-16 15:59 UTC
### Bug description

When inheriting a generic parent class, a lot a false positive appear. In my case : 
- missing-function-docstring : in normal case, it's not necessary to docstring overriden methods
- unused-argument: in normal case, unused parameters in overriden methods don't cause this error
- no-self-use : same as unused-argument
- attribute-defined-outside-init : attributes defined in the parent class init are not considered

For example:
```py
"""Module"""
# pylint: disable=too-few-public-methods
from typing import Generic, TypeVar

TYPE = TypeVar("TYPE")


class Base(Generic[TYPE]):
    """Base"""
    def __init__(self, value: TYPE) -> None:
        self.value = value

    def update_value(self, value: str) -> None:
        """update value"""
        self.value = value


class Child(Base[str]):
    """Child"""
    def __init__(self, value: str, child_value: int) -> None:
        super().__init__(value)
        self.child_value = child_value

    def update_value(self, value: str) -> None:
        print('child implementation does not use self')

    def update_value_2(self, value: str) -> None:
        """update value"""
        self.value = value
```
If `class Child(Base[str]):` -> 4 warnings
If `class Child(Base):` -> No warning

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
test.py:24:4: C0116: Missing function or method docstring (missing-function-docstring)
test.py:24:27: W0613: Unused argument 'value' (unused-argument)
test.py:24:4: R0201: Method could be a function (no-self-use)
test.py:29:8: W0201: Attribute 'value' defined outside __init__ (attribute-defined-outside-init)
```

### Expected behavior

No warning

### Pylint version

```shell
pylint 2.12.2
```

**Comment by Pierre-Sassoulas** [comment] 2022-07-06 18:30
Closing as all the warning are now gone in 2.15.0-dev0, or I can't reproduce.

**Closed by Pierre-Sassoulas** 2022-07-06 18:30 UTC
Labels: False Positive 🦟
