### ISSUE TITLE
Useful 'line-too-long' suppression considered useless

### ISSUE THREAD

**Issue by romainletendart** [PyCQA/pylint#3368] opened 2020-01-27 16:35 UTC
### Steps to reproduce
Run `pylint -e useless-suppression --max-line-length=120 toolong.py` where `toolong.py`'s content is:
```python
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789  # pylint: disable=line-too-long
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
``` 

### Current output

```
************* Module toolong
toolong.py:1:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:2:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:4:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:5:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:3:0: I0021: Useless suppression of 'line-too-long' (useless-suppression)
```

### Expected behavior

```
************* Module toolong
toolong.py:1:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:2:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:4:0: C0301: Line too long (146/120) (line-too-long)
toolong.py:5:0: C0301: Line too long (146/120) (line-too-long)
```

### pylint --version output

```
pylint 2.4.4
astroid 2.3.3
Python 3.7.6 (default, Jan  2 2020, 09:57:44) 
[GCC 9.2.0]
```

**Comment by PCManticore** [comment] 2020-02-04 17:18
Thanks for the report!

**Comment by romainletendart** [comment] 2020-07-13 08:21
@PCManticore A TODO in one of our projects reminded me of this issue and it still seems to be around.
Any ideas on how to fix it?

**Comment by romainletendart** [comment] 2020-10-22 15:18
@PCManticore Up ?

**Comment by TiphaineLAURENT** [comment] 2021-06-01 14:36
Any news about it ?

**Comment by Pierre-Sassoulas** [comment] 2021-06-01 14:47
Hello, no one worked on it yet, but contributions are welcome :)

**Comment by DanielNoord** [comment] 2021-09-27 10:29
I think something might have changed in the checker. I now get:

```bash
❯ cat test.py
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789  # pylint: disable=line-too-long
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
❯ pylint -e useless-suppression --max-line-length=120 'test.py'
************* Module test
test.py:3:0: I0021: Useless suppression of 'line-too-long' (useless-suppression)
```

Do we still consider this a false positive?

**Comment by romainletendart** [comment] 2021-09-27 11:48
Hi @DanielNoord,
We should get as many `line-too-long` errors as there are lines without the check disabled i.e. 4 `line-too-long` errors.
On your output we get none so there still is a problem here.

**Comment by clavedeluna** [comment] 2022-11-30 15:49
Output mentioned above
```
************* Module test
test.py:3:0: I0021: Useless suppression of 'line-too-long' (useless-suppression)
```

is the current output, which means this is now:
1.  1 FP useless-suppression
2. 4 FN line-too-long

**Comment by clavedeluna** [comment] 2022-11-30 20:34
I've narrowed down the issue. This only affects modules with no code, only with comments with # or with """. This can be tested by adding any other line that is code to the module, and you'll see the `useless-suppression` goes away.

The issue is triggered to do [this line](https://github.com/PyCQA/pylint/blob/main/pylint/utils/file_state.py#L106). When `node` is a module with no python code and only comments, `node.get_children()` has no children, so we do not enter into `self._set_state_on_block_lines` and a few internal containers are not updated.

Could a maintainer suggest a way to get around this? Either by somehow adding the code "child" to the node via astroid, or by suggesting a way around this. I tried stuff like `node.doc_node` or  `node["__doc__"]` which I see are used in other doc-based checkers, but none worked for this case.

**Comment by DanielNoord** [comment] 2022-11-30 22:52
I haven't looked into this, but this might be unfixable. Children of "empty" modules can't really be made up and I'm not in favour of adding them arbitrarily to Module nodes just so we can fix this edge case.

It would be interesting to know whether this issue also occurs if any actual code is in the module, both before and after the comments.

**Comment by clavedeluna** [comment] 2022-12-01 14:40
> It would be interesting to know whether this issue also occurs if any actual code is in the module, both before and after the comments.

The `useless-suppression` FP does not happen with code before, after, or anywhere in the module. This is decidedly only limited to modules with comments via hash or """ as in one example given in a comment above.

I spent quite a bit of time trying to see how this could reasonably be fixed and I've concluded as you have, it seems unfixable.

I think we could close this issue as won't fix and for documentation purposes, add the FP as a functional test, what do you think?

**Comment by Pierre-Sassoulas** [comment] 2022-12-01 15:45
We can document this in the details.rst of line-too-long too.

**Closed** 2022-12-03 08:21 UTC
Labels: Bug :beetle:, Help wanted 🙏, Checkers, Good first issue, Hacktoberfest, C: line-too-long, Needs PR

**Comment by DanielNoord** [comment] 2022-12-03 14:33
Thanks for fixing this @clavedeluna! I think you found a nice solution here!

**Comment by clavedeluna** [comment] 2022-12-03 15:56
Really satisfying to close this!

**Comment by clavedeluna** [comment] 2022-12-04 11:27
@finite-state-machine Thanks for the test case. What it shows is actually slightly different than the test cases for this issue, which were for comments only. Could you open a separate issue?

**Comment by DanielNoord** [comment] 2022-12-04 11:29
Could this be a duplicate of either https://github.com/PyCQA/pylint/issues/4802 or https://github.com/PyCQA/pylint/issues/3367?

**Comment by clavedeluna** [comment] 2022-12-04 11:30
Maaaybe? Turns out if you run some different commands results vary:
``` pylint test.py --enable=line-too-long,useless-suppression --max-line-length=20```

```
test.py:4:0: C0301: Line too long (25/20) (line-too-long)
test.py:5:0: C0301: Line too long (62/20) (line-too-long)
test.py:6:0: C0301: Line too long (87/20) (line-too-long)
test.py:9:0: C0301: Line too long (26/20) (line-too-long)
test.py:10:0: C0301: Line too long (64/20) (line-too-long)
test.py:14:0: C0301: Line too long (25/20) (line-too-long)
test.py:15:0: C0301: Line too long (33/20) (line-too-long)
```

worth investigating for sure
