### ISSUE TITLE
no-member false positive when using @classmethod constructors

### ISSUE THREAD

**Issue by jnsnow** [PyCQA/pylint#3093] opened 2019-09-06 19:27 UTC
### Steps to reproduce

Given a sample snippet like this:

```python
class Bar:
    @classmethod
    def from_xyz(cls):
        return cls()

class Foo(Bar):
    @classmethod
    def from_xyz(cls):
        return super(Foo, cls).from_xyz()
    def Baz(self):
        print("Hello World!")


x = Foo.from_xyz()
x.Baz()
```

### Current behavior

pylint will print the error:
`lint.py:15:0: E1101: Instance of 'Bar' has no 'Baz' member (no-member)`

### Expected behavior

pylint will either recognize that:
1. The result of calling from_xyz is of type Foo (and has a Baz member), or
2. The result of cls() is indeterminate and checking members is not possible.

and as a result, will not print a false positive.

### pylint --version output

pylint 2.3.1
astroid 2.2.5
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

**Comment by PCManticore** [comment] 2019-09-08 08:17
Yeah, right now `pylint` emits the error as it cannot constrain the result of `from_xyz` to `Foo`. Definitely a bug that's worth fixing.

**Comment by jacobtylerwalls** [comment] 2022-03-31 03:49
Duplicate of #981 and https://github.com/PyCQA/astroid/issues/457

**Closed by jacobtylerwalls** 2022-03-31 03:49 UTC
Labels: Bug 🪳, topic-inference
