### ISSUE TITLE
Error on imports

### ISSUE THREAD

**Issue by ywanHK** [PyCQA/pylint#4475] opened 2021-05-15 20:46 UTC
### Steps to reproduce (3 ways)

1. Given a file `a.py`:
```python
import some_module_that_does_not_exist
```
\
\
\
2. Given multiple files:
```
module.py
a.py
```
content of `module.py`:
```python
def some_function():
        print("a")
```
content of `a.py`:
```python
import module
```
\
\
\
3. Given multiple files:
```
a.py
library\
    abcd.py
```
content of `library/abcd.py`:
```python
def some_function():
        print("a")
```
content of `a.py`:
```python
from library import abcd
```
\
\
\
\
### Current behavior

Result of `pylint a.py`:
```
Exception on node <Module.a l.0 at 0x2251c389760> in file 'D:\projects\test\a.py'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\gcc\msys2\mingw64\lib\python3.8\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\parallel.py", line 69, in _worker_check_single_file
    _worker_linter.check_single_file(name, filepath, modname)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\pylinter.py", line 892, in check_single_file
    self._check_file(
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\pylinter.py", line 933, in _check_file
    check_astroid_module(ast_node)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\pylinter.py", line 1112, in _check_astroid_module
    walker.walk(ast_node)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\utils\ast_walker.py", line 79, in walk
    callback(astroid)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\checkers\imports.py", line 556, in leave_module
    std_imports, ext_imports, loc_imports = self._check_imports_order(node)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\checkers\imports.py", line 728, in _check_imports_order
    import_category = isort_driver.place_module(package)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\utils\utils.py", line 317, in place_module
    return isort.api.place_module(package, self.isort5_config)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\isort\place.py", line 17, in module
    return module_with_reason(name, config)[0]
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\isort\place.py", line 27, in module_with_reason
    or _src_path(name, config)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\isort\place.py", line 89, in _src_path
    _is_module(module_path)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\isort\place.py", line 101, in _is_module
    or any(
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\isort\place.py", line 102, in <genexpr>
    exists_case_sensitive(str(path.with_suffix(ext_suffix)))
  File "D:\gcc\msys2\mingw64\lib\python3.8\pathlib.py", line 870, in with_suffix
    raise ValueError("Invalid suffix %r" % (suffix))
ValueError: Invalid suffix '-cpython-38.dll'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\gcc\msys2\mingw64\lib\python3.8\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\gcc\msys2\mingw64\lib\python3.8\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\GCC\msys2\mingw64\bin\pylint.exe\__main__.py", line 7, in <module>
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\run.py", line 381, in __init__
    linter.check(args)
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\pylinter.py", line 877, in check
    check_parallel(
  File "D:\gcc\msys2\mingw64\lib\python3.8\site-packages\pylint\lint\parallel.py", line 140, in check_parallel
    for (
  File "D:\gcc\msys2\mingw64\lib\python3.8\multiprocessing\pool.py", line 868, in next
    raise value
ValueError: Invalid suffix '-cpython-38.dll'

```

### Expected behavior
- for the first case, it should output `E0401: Unable to import 'some_module_that_does_not_exist' (import-error)`
- for the second and third cases, it should output no warnings or errors (or at least something like `unused import`)
### pylint --version output

Result of `pylint --version` output:

```
pylint 2.8.2
astroid 2.5.6
Python 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)]
```

### Additional information:
- I am running pylint on MSYS2 mingw, Windows 10. I installed it using the pip package `mingw-w64-x86_64-python-pip 21.1.1-1` on MSYS2

**Comment by hippo91** [comment] 2021-05-22 08:41
@ywanHK thanks for the report. However I got some difficulties to understand it. Could you provide the exact snippet that leads to the exception being raised?

**Comment by ywanHK** [comment] 2021-05-22 14:32
I'm not sure what do you mean by "snippet"..... I assume it is the code that causes the error? If that is the case, then simply a .py file containing the line
```python
import some_module_that_does_not_exist
```
should trigger the exception
\
\
\
\
### One important note:
This error does not seem to happen on `[MSC v.1915 64 bit (AMD64)]` with `python 3.7.1`
But it does occur on **MSYS2** with `[GCC 10.2.0 64 bit (AMD64)]` and `python 3.8.9`

**Comment by ywanHK** [comment] 2021-05-22 14:50
When you have two files, named `a.py` and `my_module.py`, in the same directory. If the file `a.py` contains the line 
```python
import my_module
```
, then `pylint a.py` will also trigger the error

**Comment by Pierre-Sassoulas** [comment] 2021-06-16 19:32
Closing because I can't reproduce either and it look like an environment problem:

```bash
echo "import my_module">a.py
touch my_module.py
pylint a.py
```
Result:
```
************* Module a
a.py:1:0: C0114: Missing module docstring (missing-module-docstring)
a.py:1:0: W0611: Unused import my_module (unused-import)

---------------------------------------------------------------------
Your code has been rated at -10.00/10 (previous run: -6.67/10, -3.33)
```

**Closed by Pierre-Sassoulas** 2021-06-16 19:32 UTC
Labels: cannot reproduce, crash, topic-import-system

**Comment by ywanHK** [comment] 2021-06-20 14:51
what environment are you running pylint on?

I am on windows MSYS2 and the pylint I'm using is the mingw package called [mingw-w64-x86_64-python-pylint](https://packages.msys2.org/package/mingw-w64-x86_64-python3-pylint)

**Comment by Pierre-Sassoulas** [comment] 2021-06-20 15:36
You probably need to modify the pythonpath so `a.py` is accessible for pylint.
