### ISSUE TITLE
Override settings from .pylintrc

### ISSUE THREAD

**Issue by bendikro** [PyCQA/pylint#1155] opened 2016-11-02 13:02 UTC
### Steps to reproduce
1. Add to .pylintrc: disable=unused-variable
2. Run: pylint --enable=unused-variable script.py

### Current behavior
Result is that unused-variable is disabled

### Expected behavior
It could be useful to be able to override the defaults specified on the config

### pylint --version output
```
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
```

**Comment by PCManticore** [comment] 2016-11-04 13:15
How does your pylintrc file looks like?

**Comment by bendikro** [comment] 2016-11-04 13:39
It looks like this: https://github.com/bendikro/deluge/blob/develop/.pylintrc

**Comment by moylop260** [comment] 2016-11-04 13:49
What is the file python with unused-variable used here?

**Comment by moylop260** [comment] 2016-11-04 16:21
Using:
pylint -rn -d all --enable=unused-variable [pylint/test/functional/unused_variable.py](https://github.com/PyCQA/pylint/blob/master/pylint/test/functional/unused_variable.py)

Emit messages fine!

You have `jobs=2` in your configuration file.

pylint --jobs=2 -rn -d all --enable=unused-variable [pylint/test/functional/unused_variable.py](https://github.com/PyCQA/pylint/blob/master/pylint/test/functional/unused_variable.py)

Don't emit the messages.

**Comment by moylop260** [comment] 2016-11-04 17:01
Duplicated https://github.com/PyCQA/pylint/issues/374

**Comment by PCManticore** [comment] 2016-11-09 08:36
Thanks @moylop260  This is indeed a duplicate of #374, which we will try to handle before releasing 2.0.

**Closed by PCManticore** 2016-11-09 08:36 UTC
