### ISSUE TITLE
logging checker doesn't recognize Logger subclasses

### ISSUE THREAD

**Issue by glennmatthews** [PyCQA/pylint#960] opened 2016-06-27 13:32 UTC
If I create a subclass of `logging.Logger`, Pylint's `logging` checker does not seem to recognize instances of this class to be checked:
### Steps to reproduce

``` python
# logger.py
import logging

l1 = logging.getLogger('one')

class L(logging.Logger):
    pass

l2 = L('three')
l3 = logging.Logger('two')

l1.info('testing {0}'.format('info'))
l1.info('testing %s' % 'info')
l2.info('testing {0}'.format('info'))
l2.info('testing %s' % 'info')
l3.info('testing {0}'.format('info'))
l3.info('testing %s' % 'info')
```

``` bash
pylint --disable=all --enable=logging-format-interpolation,logging-not-lazy logger.py -rn 
```

At first I thought this might be an issue with `logging-modules` but setting that doesn't seem to help:

``` bash
pylint --disable=all --enable=logging-format-interpolation,logging-not-lazy logger.py -rn --logging-modules=logging,logger
```
### Current behavior

```
No config file found, using default configuration
************* Module logger
W: 11, 8: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
W: 12, 0: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 15, 8: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
W: 16, 0: Specify string format arguments as logging function parameters (logging-not-lazy)
```

Note that the calls to my Logger subclass are not flagged by the logging checker.
### Expected behavior

```
No config file found, using default configuration
************* Module logger
W: 11, 8: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
W: 12, 0: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 13, 8: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
W: 14, 0: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 15, 8: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
W: 16, 0: Specify string format arguments as logging function parameters (logging-not-lazy)
```
### pylint --version output

```
pylint 1.5.6, 
astroid 1.4.6
Python 2.7.11 (default, Mar  5 2016, 01:37:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

**Comment by glennmatthews** [comment] 2016-06-27 13:32
Possibly related to #459?

**Comment by PCManticore** [comment] 2016-06-27 13:35
Thank you for reporting this!

I don't think it is related to #459, just that the way we are determining if an object or not should be analyzed for these errors is hard coded (https://github.com/PyCQA/pylint/blob/master/pylint/checkers/logging.py#L141). Instead, looking in the mro to determine if it is a Logger subclass should improve things significantly.

**Comment by glennmatthews** [comment] 2016-06-27 13:41
Thanks for the fast response!

I would have thought that the line 143 ` any(ancestor.qname() == 'logging.Logger'` would cause my subclass to be detected as a Logger subclass?

By wrapping the `visit_call` method with some debugging code, it looks to me like it's actually failing before it even gets to line 141 - specifically it seems that `for inferred in node.func.infer():` at line 138 may be raising an InferenceError:

```
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroid/bases.py", line 302, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroid/bases.py", line 329, in raise_if_nothing_inferred
    raise exceptions.InferenceError()
```

So maybe this is a bug in astroid rather than pylint? I'm searching blindly in the dark here. :-)

**Comment by PCManticore** [comment] 2016-06-27 13:49
It might actually be in astroid. Here is a small reproducing case:

    from astroid.test_utils import extract_node
    n = extract_node('''
    import logging

    class L(logging.Logger):
        pass

    l2 = L('three')

    l2.info('testing {0}'.format('info'))
    ''')
    f = n.func
    print(f)
    print(f.inferred())

In this case, f should be inferred as a method of L, but it is not.

**Comment by PCManticore** [comment] 2016-06-27 17:16
Okay, I think this is caused by https://github.com/PyCQA/astroid/issues/108.  Removing the context from this call https://github.com/PyCQA/astroid/blob/master/astroid/inference.py#L187 fixes the problem, but causes others as well.
It is a long time wrong behavior that needs to be changed, although I didn't find a good solution just yet. I will assign this issue to a late milestone, since I will probably not have time for including a fix in 2.0.

**Comment by glennmatthews** [comment] 2016-06-27 17:56
Thanks for the investigation!

**Comment by tyarimi** [comment] 2018-02-12 08:03
@PCManticore is this going to get fixed anytime soon?

**Comment by PCManticore** [comment] 2018-02-12 08:32
@tyarimi Probably not, unless someone volunteers for a patch.

**Closed** 2018-09-29 08:47 UTC
Labels: bug
