### ISSUE TITLE
RecursionError with colorama and jobs>1

### ISSUE THREAD

**Issue by haroldmeerwaldt** [PyCQA/pylint#6012] opened 2022-03-28 12:30 UTC
### Bug description

Pylint crashes from a RecursionError inside colorama when run with jobs>1. This happens on any file, e.g. test.py:
```print("test")```

When it is run with jobs=1, it finishes fine. When coloroma is uninstalled, it also works fine.

It appears to be due to the line `obj = StockUnpickler.load(self)` in dill which passes `self`. In colorama, now `self.__wrapped` equals `self` and `getattr` calls itself.

### Configuration

```ini
[MASTER]
jobs=4
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Python399\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python399\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python399\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\pylint\lint\parallel.py", line 61, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Python399\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python399\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python399\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\pylint\lint\parallel.py", line 61, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "C:\Python399\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python399\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python399\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\pylint\lint\parallel.py", line 61, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "C:\Python399\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python399\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python399\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\pylint\lint\parallel.py", line 61, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "C:\Python399\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python399\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python399\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\pylint\lint\parallel.py", line 61, in _worker_initialize
    _worker_linter = dill.loads(linter)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  File "C:\Users\XXX\pylint-test\env\
lib\site-packages\colorama\ansitowin32.py", line 29, in __getattr__
    return getattr(self.__wrapped, name)
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python399\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "C:\Python399\lib\multiprocessing\context.py", line 3, in <module>
    import threading
  File "C:\Python399\lib\threading.py", line 95, in <module>
    class _RLock:
KeyboardInterrupt
```

### Expected behavior

Pylint to run without crashing.

### Pylint version

```shell
pylint 2.13.2
astroid 2.11.2
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
```

### OS / Environment

Windows 10, both git bash and cmd.exe

### Additional dependencies

dill==0.3.4
colorama==0.4.4

**Comment by DanielNoord** [comment] 2022-03-28 12:43
@haroldmeerwaldt I added the dependency on `dill` and didn't there would be issues with `colorama`. I don't use the package myself so I have no immediate solutions here.

That said, I did find this issue https://github.com/tartley/colorama/issues/86. Could you check if this indeed works? If so, we might want to try and get that change to land in a patch version of colorama.

**Comment by haroldmeerwaldt** [comment] 2022-03-28 12:55
I checked the solution in the issue at colorama, and indeed, adding the `__setstate__` and `__getstate__` fixes the issue.

**Comment by Pierre-Sassoulas** [comment] 2022-03-28 17:28
It's unclear for me if we need to do something (stop pickling StreamWrapper ?) or if it's a dill/colorama related problem and we can close as won't fix. What's your opinion ?

**Comment by DanielNoord** [comment] 2022-03-29 06:39
I would like to submit the fix to `colorama` and see if they accept it.

@Pierre-Sassoulas Do we officially support `colorama`? If so we can either 1) revert the `dill` dependency (but that would once again stop the `argparse` migration) or 2) say that we don't support `colorama` on `2.13` and will only do so after `colorama` has this fix...

**Comment by Pierre-Sassoulas** [comment] 2022-03-29 07:47
>  Do we officially support colorama?

I don't understand the question. I suppose it's only used for the colored output (that isn't the default reporter). But we should be able to parse colorama's code without crash.

Let's hope the fix in colorama get merged and released quickly ™️ (say before may) and re-discuss this if it's not.

**Comment by Pierre-Sassoulas** [comment] 2022-03-29 08:23
Maybe we can disable colored output while multiprocessing when colorama Version is < to the next release of colorama? I don't realize the work involved.

**Comment by DanielNoord** [comment] 2022-03-29 09:01
Not sure. Let's wait for a response from the `colorama` maintainers on how long a release might take. The unreleased branch also has support for `3.9` so perhaps that might convince them to move up the release.

**Comment by haroldmeerwaldt** [comment] 2022-03-29 09:36
@DanielNoord No problem! Already great you are picking this up so fast.

I actually have output-format set to text. For all values (text, parseable, colorized, json) the error occurs.

For now my workaround is setting jobs to 1.

**Comment by jackdewinter** [comment] 2022-04-07 05:30
Seeing this also with jobs > 1 and seeing the same output.  Let me know if you want some help testing this.

**Comment by DanielNoord** [comment] 2022-04-07 07:05
I think the best option is to politely ask the `colorama` team if they would consider doing a patch release. We're unable to remove our `dill` dependency as we have now built quite a bit of our configuration handling on top of it so it would be _almost_ impossible to revert it.

**Comment by MarcinGolunski** [comment] 2022-04-12 10:40
Hi,
I have similar problem (when use more jobs than 1 and start from 2.13.0 pylint), but have another error 
My error:
`Traceback (most recent call last):
  File "/usr/local/bin/pylint_runner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pylint_runner/main.py", line 218, in main
    runner.run(output, error)
  File "/usr/local/lib/python3.6/site-packages/pylint_runner/main.py", line 205, in run
    run = pylint.lint.Run(self.args + pylint_files, **exit_kwarg)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1081, in check
    files_or_modules,
  File "/usr/local/lib/python3.6/site-packages/pylint/lint/parallel.py", line 148, in check_parallel
    jobs, initializer=initializer, initargs=[dill.dumps(linter)]
  File "/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/usr/local/lib/python3.6/site-packages/dill/_dill.py", line [27](https://gitlab.devtools.intel.com/cavs_scripts-py/vision_scripts-py/-/jobs/40996212#L27)6, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/usr/local/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/local/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python3.6/pickle.py", line 6[34](https://gitlab.devtools.intel.com/cavs_scripts-py/vision_scripts-py/-/jobs/40996212#L34), in save_reduce
    save(state)
  File "/usr/local/lib/python3.6/pickle.py", line [47](https://gitlab.devtools.intel.com/cavs_scripts-py/vision_scripts-py/-/jobs/40996212#L47)6, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/local/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/local/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.6/pickle.py", line [49](https://gitlab.devtools.intel.com/cavs_scripts-py/vision_scripts-py/-/jobs/40996212#L49)6, in save
    rv = reduce(self.proto)
TypeError: cannot serialize '_io.TextIOWrapper' object`

**Comment by Pierre-Sassoulas** [comment] 2022-05-06 20:11
Closing as won't fix.

**Closed by Pierre-Sassoulas** 2022-05-06 20:11 UTC
Labels: Won't Fix, Crash 💥, Upstream Bug 🪲

**Comment by DanielNoord** [comment] 2022-06-02 13:14
If you turn of the `colorized` reported this should do the trick. We're using `colorama` in the `colorized` reporter on Windows, so just setting the reporter to `text` should fix this.

**Comment by DanielNoord** [comment] 2022-06-02 13:26
> Setting --output-format text does not work.
> 
> 
> 
> Only uninstalling colorama seems to work but that is not an option because so many packages including pylint depend on it.

Hm, then we might need to find a way to not do the import.

That said maybe a comment here could help: https://github.com/tartley/colorama/issues/341

In the end, this is more an issue with colorama than with pylint. We could solve it by just removing our support for colorama completely, but it would be much better if they released a version with the fix.

**Comment by DanielNoord** [comment] 2022-06-02 13:44
> Maybe we could lazy import colorama like we lazyimport enchant ? I'm considering dropping colorama too, coloring is great, but it's been making pylint crash for more than 2 months now and there's still no release in sight. It's also possible to use ansi coloring in the message template if you really want to have color...

We already lazy import it, but it is not lazy enough. That's why I though removing `colorized` would be enough.

It would require some refactoring to fix this: `colorama` is loaded in the `__init__` of the `ColorizedReporter` which is instantiated when we create `PyLinter`. All reporters are instantiated before they are selected. If somebody wants to put the effort into that refactor I'd happily review, but I think it's better spent effort to try and get `colorama` to release.

**Comment by Pierre-Sassoulas** [comment] 2022-06-02 13:51
Lazy loading reporters sounds like the right answer but we have at least five hundred issues that would be more useful than this if only colorama released the fix you provided 2 months ago. Let's wait a little more :)

**Comment by DanielNoord** [comment] 2022-06-02 13:53
For anybody running into this: installing the `master` branch of `colorama` will also solve this issue.

**Comment by Pierre-Sassoulas** [comment] 2022-06-02 14:04
Yeah in fact the solution is to install colorama using:

```bash
pip install git+https://github.com/tartley/colorama.git@51cf5078e3b316d1834f62bd72991aa7ffdee7a5
```

**Comment by DanielNoord** [comment] 2022-06-18 07:13
For anybody following this issue:
`colorama` `0.4.5` has been released this week. We're going to pin it in our dependencies with #6970, but you can upgrade yourself locally right now to fix any issues that were caused by this.

Sorry for the inconveniences and thanks for all the reports!

**Comment by owillebo** [comment] 2022-06-20 07:45
> For anybody following this issue: `colorama` `0.4.5` has been released this week. We're going to pin it in our dependencies with #6970, but you can upgrade yourself locally right now to fix any issues that were caused by this.
> 
> Sorry for the inconveniences and thanks for all the reports!

No problem, you did a good job!
