### ISSUE TITLE
Incorrect work with variable types

### ISSUE THREAD

**Issue by Anjuta** [PyCQA/pylint#1413] opened 2017-04-07 09:28 UTC
```
from typing import Any

a = None    # type: Any
```
If we check this script with pylint 1.6.5, we will get the error "W:  1, 0: Unused Any imported from typing (unused-import)". But this syntax corresponds to [pep 484](https://www.python.org/dev/peps/pep-0484/).

**Comment by degustaf** [comment] 2017-04-07 16:11
This appears to be a duplicate of #1168.

**Comment by PCManticore** [comment] 2017-04-12 06:19
Thanks. I don't consider these two issues duplicated, because one is dealing with pure AST objects (the one mentioned by @degustaf), while this one should be handled by parsing the comments to figure out these imports.

**Comment by PCManticore** [comment] 2017-04-12 14:49
Closed as duplicate of  https://github.com/PyCQA/pylint/issues/1063

**Closed by PCManticore** 2017-04-12 14:49 UTC
Labels: python 3.6
