### ISSUE TITLE
Since 2.12 method-related warnings are too intrusive and hide other issues

### ISSUE THREAD

**Issue by Avasam** [PyCQA/pylint#5799] opened 2022-02-12 02:39 UTC
### Current problem

![image](https://user-images.githubusercontent.com/1350584/153693348-6720dc4a-dad3-4ba0-8728-0c1845d92d92.png)

### Desired solution

To just underline the top of the function. Example:
![image](https://user-images.githubusercontent.com/1350584/153693412-645f70e7-2153-43c0-a1f4-e5c6a36d571d.png)

### Additional context

I do appreciate that issues no longer underline a single character. But some warnings like complexity or statement count are hard to fix immediately. And I don't necessarily want to hide the warning. But in the mean time, it adds any other warning/error and is an eye-sore to work in.

**Comment by Pierre-Sassoulas** [comment] 2022-02-12 09:33
Duplicate of #5466

**Closed by Pierre-Sassoulas** 2022-02-12 09:33 UTC
