### ISSUE TITLE
Runs of pylint on the same codebase produce different results

### ISSUE THREAD

**Issue by simonsmiley** [PyCQA/pylint#1060] opened 2016-08-03 21:01 UTC
Here are two builds once run using my own gitlab runner and on gitlab's shared runners.
My runner results in passing tests, while the shared runner fails. It doesn't seem to related to the runners. Two devs ran the tests locally and they passed, another got the error.
https://gitlab.com/thelinuxguy/hyperkitty/builds/2814491
https://gitlab.com/thelinuxguy/hyperkitty/builds/2814452

Here is the actual code
https://gitlab.com/thelinuxguy/hyperkitty/blob/master/hyperkitty/models/email.py#L208

and this is how we run our tests
https://gitlab.com/thelinuxguy/hyperkitty/blob/master/tox.ini

Since we are using tox, we always use the latest released version of pylint.

**Comment by sebix** [comment] 2016-08-10 19:07
I experience the same issue with some SUSE distros, here are the build logs including diffs:
- OpenSUSE Leap: https://build.opensuse.org/package/live_build_log/home:sebix:branches:devel:languages:python3/python3-pylint/openSUSE_Leap_42.1/i586
- SUSE Linux Enterprise 12: https://build.opensuse.org/package/live_build_log/home:sebix:branches:devel:languages:python3/python3-pylint/SLE_12_SP1/x86_64

**Comment by PCManticore** [comment] 2016-08-11 21:31
Hi, sorry for taking so long to reply.

I will take a look in the following days (currently just triaging some issues).

**Comment by sebix** [comment] 2016-10-08 14:27
Any updates on this?

**Comment by sebix** [comment] 2016-12-18 14:33
Here are new results for 1.4.5 and pytest:

openSUSE Leap 42.1: https://build.opensuse.org/package/live_build_log/home:sebix:branches:devel:languages:python3/python3-pylint/openSUSE_Leap_42.1/i586
openSUSE Tumblweed: https://build.opensuse.org/package/live_build_log/home:sebix:branches:devel:languages:python3/python3-pylint/openSUSE_Tumbleweed/i586

**Comment by GliderGeek** [comment] 2018-11-27 12:59
i am also experiencing differences between results on a gitlab runner and my local pylint run.
any update on this?
@PCManticore: any ways i can help getting closer to a solution?

**Comment by PCManticore** [comment] 2018-11-27 13:03
Sorry @GliderGeek I didn't have time to check this, nor I'll have in the following weeks. If you can investigate from where this difference comes, that will be hopeful. I don't exactly how to verify that, you might put some debugging statements in the visit methods to see if the order of visiting the nodes affect this somehow (although we should probably have consistent visit ordering).

**Comment by Pierre-Sassoulas** [comment] 2022-06-29 20:15
Closing as it's probably related to subtle changes in the environment, the interpreter, installed packages, installed packages versions or a combination of those factors. Please provide a dockerfile so we can reproduce easily and open a new issue if you encounter a similar issue.

**Closed by Pierre-Sassoulas** 2022-06-29 20:15 UTC
Labels: Bug :beetle:

**Comment by sashokbg** [comment] 2024-11-22 19:12
Hello, I was preparing to add a message to this thread since I had the same issue and I found out the culprit !

In my CICD the git worktree was completely clean, since it is a fresh checkout. On my local build however when typing "git status" I saw that I had an "out" directory that I forgot to clean at one point. My pylint was going over it which resulted in lower score since lots of repetitions.

So the solution is to configure an exception in your pylintrc if you have local untracked files
