### ISSUE TITLE
Unused import (false positive?)

### ISSUE THREAD

**Issue by rtfpessoa** [PyCQA/pylint#1314] opened 2017-02-03 17:42 UTC
### Steps to reproduce
1. Run `pylint test.py`

### Current behavior
W:  4, 0: Unused import uuid (unused-import)

### Expected behavior
No problem should be reported

### pylint --version output

No config file found, using default configuration
pylint 1.6.5,
astroid 1.4.9
Python 3.6.0 (default, Dec 24 2016, 08:01:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

### Explanation

Currently I am running Pylint in a file which imports uuid and Pylint detects the import as unused.

The problem seems related to the local variable named also `uuid`.

The file contents are here:
https://raw.githubusercontent.com/LazyHaus/API/d1d2859a717b4326633c456ee15aebb82e7e06db/api/models.py

Any idea what might be the problem?

**Comment by rogalski** [comment] 2017-02-03 18:01
Duplicate of #848

**Closed by rogalski** 2017-02-03 18:01 UTC

**Comment by rtfpessoa** [comment] 2017-02-03 18:03
@rogalski thank you. My search skills are not very good apparently 😞
