### ISSUE TITLE
*args and **kwargs are reported as unused even if added to ignored-argument-names

### ISSUE THREAD

**Issue by karyon** [PyCQA/pylint#2214] opened 2018-06-22 21:00 UTC
### Steps to reproduce
given this function:
```
def frob(arg, *args, **kwargs):
    pass
```
and this setting
```
ignored-argument-names=arg|args|kwargs
```

pylint will report
```
unused-argument / Unused argument 'args'
unused-argument / Unused argument 'kwargs'
```
which i wouldn't expect. weirdly, adding them to `dummy-variables-rgx` actually silences the warning.

using pylint 1.9.2

**Comment by brycepg** [comment] 2018-07-01 02:14
Duplicate of #1992

**Comment by brycepg** [comment] 2018-07-01 03:00
Thanks for the report!

**Closed** 2018-07-03 07:10 UTC
Labels: bug
