### ISSUE TITLE
Regression: PyLint 2 incorrectly errors unexpected-keyword-arg on overloaded methods

### ISSUE THREAD

**Issue by nikhilm** [PyCQA/pylint#2375] opened 2018-08-01 20:09 UTC
(verified this is not fixed in preview 2.1.0 either)

### Steps to reproduce

Requires the typing module (v3.6.2 installed on python3)
File a.py
```python
from b import XYZ

XYZ().overloaded(replace_with="repl")
```

File b.py
``` python
from typing import overload

class XYZ:
    @overload
    def overloaded(self):
        pass

    def overloaded(self, replace_with=None):  # pylint: disable=function-redefined
        pass
```

### Current behavior

```
$ python3 -m pylint a.py
************* Module a
a.py:1:0: C0111: Missing module docstring (missing-docstring)
a.py:3:0: E1123: Unexpected keyword argument 'replace_with' in method call (unexpected-keyword-arg)
```

### Expected behavior
It shouldnt' complain.  Here is the correct behavior in v1.9.0

```
$ python3 -m pylint --version                                                                                                                                                             
No config file found, using default configuration
__main__.py 1.9.1, 
astroid 1.6.5
Python 3.6.5 (default, Jul  2 2018, 12:11:17) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]

$ python3 -m pylint a.py
No config file found, using default configuration
************* Module a
C:  1, 0: Missing module docstring (missing-docstring)
```

### pylint --version output

```
$ python3 -m pylint --version
__main__.py 2.0.1
astroid 2.0.2
Python 3.6.5 (default, Jul  2 2018, 12:11:17) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
```

**Comment by brycepg** [comment] 2018-08-02 20:12
Same as #2336

**Comment by Pierre-Sassoulas** [comment] 2022-06-29 19:44
Closing as I can't reproduce on 2.14.

**Closed by Pierre-Sassoulas** 2022-06-29 19:44 UTC
Labels: Bug :beetle:, Astroid
