### ISSUE TITLE
Pylint doesn't understand imports in "development mode"

### ISSUE THREAD

**Issue by scottgasch** [PyCQA/pylint#7701] opened 2022-11-01 17:37 UTC
If I install a project via pip from PyPi and it is placed under lib/site-packages in my venv, pylint can find/import it just fine:

```
$ pip install pyutils
Installing collected packages: pyutils
Successfully installed pyutils-0.0.1b6

$ pylint ./program.py
program.py:129:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
program.py:175:19: W0703: Catching too general exception Exception (broad-except)
------------------------------------------------------------------
Your code has been rated at 9.88/10 (previous run: 9.88/10, +0.00)

```
But if I install this module from local sources in development mode then pylint can't figure out code that imports it:

```
$ pip uninstall pyutils
Found existing installation: pyutils 0.0.1b6
Uninstalling pyutils-0.0.1b6:
  Would remove:
    /usr/home/scott/py39-venv/lib/python3.9/site-packages/pyutils-0.0.1b6.dist-info/*
    /usr/home/scott/py39-venv/lib/python3.9/site-packages/pyutils/*
Proceed (Y/n)? y
  Successfully uninstalled pyutils-0.0.1b6

$ pip install -e .
Building wheels for collected packages: pyutils
  Building editable for pyutils (pyproject.toml) ... done
  Created wheel for pyutils: filename=pyutils-0.0.1b6-0.editable-py3-none-any.whl size=6552 sha256=4631e0a79f9028f0a38608e51d18af96f8fed902778b38ffba8bde32a0f9c60a
  Stored in directory: /tmp/pip-ephem-wheel-cache-qv2fcy5j/wheels/d1/b8/4e/99b126b6c6fcf38f67396da4748884306f3ca2ac09c5a42df4
Successfully built pyutils
Installing collected packages: pyutils
Successfully installed pyutils-0.0.1b6

$ pylint ./program.py
program.py:15:0: E0401: Unable to import 'pyutils' (import-error)
program.py:16:0: E0401: Unable to import 'pyutils.ansi' (import-error)
program.py:17:0: E0401: Unable to import 'pyutils.datetimes' (import-error)
program.py:18:0: E0401: Unable to import 'pyutils.files' (import-error)
program.py:129:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
program.py:175:19: W0703: Catching too general exception Exception (broad-except)

------------------------------------------------------------------
Your code has been rated at 8.64/10 (previous run: 9.88/10, -1.23)
```

I've tried various workaround involving PYTHONPATH and the system path in pylint's init-hooks and found none that really work well.  Is this a known bug?  Is there another recommended fix or workaround for this?

**Comment by Pierre-Sassoulas** [comment] 2022-11-01 17:41
pylint generally work well with pip editable installs, there's a problem specific to your installation / environnement, that we'll have a hard time debugging without more details.

**Comment by DanielNoord** [comment] 2022-11-01 19:38
Can you reproduce this outside of `PyPy`? There are many variables here that can potentially cause this (`setuptools`, `pip`, `PyPy`, `venv` etc.) Just trying to see what the common factor is

**Comment by scottgasch** [comment] 2022-11-01 20:56
Sorry, I don't understand the request.  My point is that when I install the
pyutils package from PyPi it works and when I install it from a local wheel
in edit mode it doesn't work.  By "reproduce it outside of PyPi" do you
mean: do not install pyutils via PyPi and have it still break?  That's the
status quo.  I don't know how to not install pylint except for via PyPi but
am happy to try that if this is what you meant.  I can also try this
outside of virtual environments if that is helpful.

**Comment by DanielNoord** [comment] 2022-11-01 21:07
Oh my bad, I completely misread you question and thought this was happening on `PyPy`.

I think I actually already know what this issue is, namely:
https://github.com/PyCQA/astroid/pull/1752

This is likely a duplicate of https://github.com/PyCQA/pylint/issues/7306. Could you test with a lower version of `setuptools`?

**Comment by scottgasch** [comment] 2022-11-01 21:18
I pinned setuptools at version 63 (was 65.1) and built a new wheel for the
local package then pip installed -e . again.  pylint still doesn't find the
imports.

$ pip list | grep setuptools
setuptools                        63.0.0

$ pip uninstall pyutils
..

$ python -m build
...
Successfully built pyutils-0.0.1b7.tar.gz and
pyutils-0.0.1b7-py3-none-any.whl

$ pip install -e .
...
Successfully installed pyutils-0.0.1b7

$ pylint ./reminder.py
reminder.py:15:0: E0401: Unable to import 'pyutils' (import-error)
reminder.py:16:0: E0401: Unable to import 'pyutils.ansi' (import-error)
reminder.py:17:0: E0401: Unable to import 'pyutils.datetimes' (import-error)
reminder.py:18:0: E0401: Unable to import 'pyutils.files' (import-error)
...

Should I go back to an even earlier version of setuptools?

Thx,
Scott

**Comment by DanielNoord** [comment] 2022-11-01 21:20
Hm, that's weird. Although I must say I have had many issues while working on that PR with getting stuff to reproduce. `pip` doesn't always seem to use the `setuptools` installation you expect it to.
It seems likely that this is a duplicate, but I can't confirm 100% obviously..

**Comment by scottgasch** [comment] 2022-11-01 21:24
Feel free to close as a dupe.  Is the issue understood?  Under my
site-packages I get a json file that seems to act as a link to the actual
code when I install -e.  Is there another methodology for these development
mode installs that works better?

**Comment by DanielNoord** [comment] 2022-11-01 22:01
Does that also happen with the lower version of `setuptools`?

**Comment by scottgasch** [comment] 2022-11-01 22:19
Yes.  I just installed setuptools==62.0 and rebuilt the wheel package for
pyutils with python -m build.  Then did a pip install -e . to install it.
The state of ~/venv/lib/python3.9/site-packages/pyutils* is the same as
with higher versions of setuptools.  Namely, it seems to have
a direct_url.json file in there that points at where the code lives.
Pylint doesn't work with this 62.0 based install either.

**Comment by DanielNoord** [comment] 2022-11-02 08:01
Hm, I would need to look into that. I'm almost certain we don't support that `json` file, and I wonder how it ends up there. I feel like I saw recent discussion about using `json` files, but maybe `setuptools` also did so on older versions.

**Comment by scottgasch** [comment] 2022-11-09 05:36
Thanks Niander.  Setting that envvar before doing the pip install -e .
works for me too.  Under the venv's site-packages there's an egg-link file
now instead of that directory with a JSON file.

**Comment by Pierre-Sassoulas** [comment] 2022-11-09 08:20
I'm closing as a duplicate of https://github.com/PyCQA/pylint/issues/7306

**Closed by Pierre-Sassoulas** 2022-11-09 08:20 UTC
Labels: Question, Needs reproduction :mag:, Needs investigation 🔬
