### ISSUE TITLE
Support per-module disables

### ISSUE THREAD

**Issue by eddie-dunn** [PyCQA/pylint#871] opened 2016-04-13 08:22 UTC
I would like to disable a set of warnings for modules in a specific 
folder.

Why? We have a Python project laid out like this:

```
    project/
    ├── .pylintrc
    ├── module1.py
    ├── module2.py
    └── tests/
        ├── test_module1.py
        └── test_module2.py
```

Our unit and function tests reside in the folder called `tests/`. When it comes to tests the pylint warnings `missing-docstring`, `invalid-name` and `protected-access` are not relevant. On the other hand, these warnings are very useful for the actual code in the project.

Also, we would like to avoid adding #-disable boilerplate inside every single file; preferably we would like to add the folder-specific disables in the project's pylintrc-file. E.g, something along the lines of

```
 folder-disabled=tests/:invalid-name,protected-access
```

in the pylintrc.

**Comment by kernc** [comment] 2016-04-19 16:44
Blocked on https://github.com/PyCQA/pylint/issues/618 and https://github.com/PyCQA/pylint/issues/175#issuecomment-182689321.

**Comment by AWhetter** [comment] 2016-06-12 19:06
As @kernc mentioned, this is a duplicate of #618. It's actively being worked on so should be solved soon!

**Closed by AWhetter** 2016-06-12 19:06 UTC
