### ISSUE TITLE
Module 'numpy.linalg' has no 'blas' member (no-member)

### ISSUE THREAD

**Issue by afshinfard** [PyCQA/pylint#2839] opened 2019-03-27 05:01 UTC
### Steps to reproduce
1. create a `.py` file:
```
import scipy as sp
import numpy as np
.
.
.
sp.linalg.blas.sgemm(1.0, adj_array, adj_array)`
```
2. Run pylint
` E1101: Module 'numpy.linalg' has no 'blas' member (no-member)`.

Please note that I am calling `sp.linalg` and am receiving an error for `numpy.linalg`.
Also please note that I have tried known solutions in other issues like `extension-pkg-whitelist=numpy` or:
```
[TYPECHECK]
ignored-modules = numpy
ignored-classes= numpy
```
or 
```
[TYPECHECK]
generated-members=numpy.*
```
in `.pylintrc` file

### Current behavior
Errors

### Expected behavior
No errors

### pylint --version output
pylint 2.1.1
astroid 2.0.4
Python 3.7.1
[GCC 5.5.0]

**Comment by PCManticore** [comment] 2019-03-27 11:44
Thanks @afshinfard

**Comment by afshinfard** [comment] 2019-03-29 21:34
no problem, @PCManticore Do you have any suggestions for ignoring this issue temporarily while linting?

**Comment by PCManticore** [comment] 2019-04-03 08:57
@afshinfard For now you can try with `--ignored-modules="numpy.linalg"` until we get this fixed, sorry for the extra inconvenience.

**Comment by afshinfard** [comment] 2019-04-03 18:33
No worries! Thank you so much @PCManticore

**Comment by sjackman** [comment] 2019-04-03 18:35
@afoglia Did `ignored-modules=numpy.linalg` work?

**Comment by afshinfard** [comment] 2019-04-03 18:37
@sjackman Just testing it now

**Comment by sjackman** [comment] 2019-04-03 19:01
It worked! Thanks, Claudiu.

**Comment by hippo91** [comment] 2020-08-19 13:19
@afshinfard sorry for the delay of this answer.
I was trying to work on this issue but have been unable to reproduce it.
It appears that when i try to use `linalg` submodule from `scipy` without explicitly import it i got an error. For example, when running python on :
```
import scipy as sp
import numpy as np

adj_array = np.array([1, 2])
sp.linalg.blas.sgemm(1.0, adj_array, adj_array)
```
i got `AttributeError: module 'scipy' has no attribute 'linalg'`. From `scipy` doc, it appears that if you want to use a submodule you have to explicitly import it.
For example, here `import scipy.linalg as linalg`, thus IMO this issue is no more relevant. I'm closing it but feel free to reopen it if i'm wrong or if you are facing the same problem again.

**Closed by hippo91** 2020-08-19 13:19 UTC
Labels: astroid brain, bug
