### ISSUE TITLE
Pylint still checks for BaseException.args, even if you override the typehint of it

### ISSUE THREAD

**Issue by XaiTV** [PyCQA/pylint#7221] opened 2022-07-22 14:16 UTC
### Bug description

With the following code:

```python3
""" This is a module to test a potential pylint bug """

class TestException(Exception):
    """ An exception to test something """
    args: list[dict]


def main():
    """ Our main testing function """
    try:
        raise TestException({'loc': ['foo', 'bar']})
    except TestException as err:
        for error in err.args:
            print(error['loc'])
```

Pylint seems to ignore the typehint given at line 5

### Configuration

```ini
Empty
```

### Command used

```shell
pylint test_exception.py
```

### Pylint output

```shell
************* Module pylint_test.test_exception
test_exception.py:14:18: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)

-----------------------------------
Your code has been rated at 5.00/10
```

### Expected behavior

I'd expect pylint to see that args is a list of dicts here, so calling `error['loc']` works

### Pylint version

```shell
pylint 2.14.5
astroid 2.11.7
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
```

### OS / Environment

Debian 11 (bullseye)

**Comment by Pierre-Sassoulas** [comment] 2022-07-22 14:43
Duplicate of #4813

**Closed by Pierre-Sassoulas** 2022-07-22 14:43 UTC
Labels: Needs triage :inbox_tray:
