### ISSUE TITLE
Imports of namespaces conflict with some third party libraries

### ISSUE THREAD

**Issue by Gidgidonihah** [PyCQA/pylint#3173] opened 2019-10-08 05:21 UTC
I'm seeing the issues similar to #842 (pylint unable to import namespaces)
in the latest version of pylint and python 3.7.

### Steps to reproduce
1. Create the following directory structure:
    ```
    .
    ├── api
    │   └── noworky.py
    └── main.py
    ```
1. Save the following as main.py:
    ```py
    """ This produces a pylint import-error under certain circumstances """
    from api import noworky

    print(noworky)
    ```
1. `pylint main.py` and observe there is no import-error
1. `pip install googleapis-common-protos==1.6.0`
1. `pylint main.py` and observe there is now an import-error
1. `touch api/__init__.py`
1. `pylint main.py` and observe there are no errors

### Current behavior

Pylint produces the following error:
```
************* Module main
main.py:2:0: E0401: Unable to import 'api' (import-error)

----------------------------------------------------------------------
Your code has been rated at -15.00/10 (previous run: 10.00/10, -25.00)
```

### Expected behavior
No errors:
```
----------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: -15.00/10, +25.00)
```

### pylint --version output
pylint 2.4.2
astroid 2.3.1
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by PCManticore** [comment] 2019-10-09 12:46
Thanks for opening an issue.

**Comment by Oberon00** [comment] 2019-10-09 14:24
This seems to be a duplicate of #2648.

**Comment by domibarton** [comment] 2020-10-22 22:08
@Gidgidonihah I have exactly the same issue with a namespace package and a newer pylint version:

```
pylint 2.6.0
astroid 2.4.2
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)
[Clang 6.0 (clang-600.0.57)]
```

Did you solve yours?

**Comment by Gidgidonihah** [comment] 2020-10-27 18:56
@domibarton I don't recall any resolution aside from the mentioned adding/using `__init__.py`.

**Comment by domibarton** [comment] 2020-10-27 20:04
It was my fault, because I forgot to declare the namespace properly in the namespace package `__init__.py`. This is required for [pkg_resources-style namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages):

```python
__import__('pkg_resources').declare_namespace(__name__)
``````

There's also an alternative for [pkgutil-style namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages):

```python
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
``````

**Comment by domibarton** [comment] 2020-10-27 20:05
@Gidgidonihah this will probably solve your problem as well… :)

**Comment by domibarton** [comment] 2020-10-27 20:14
To clarify, Python 3.3 introduced native namespace packages in [PEP 420](https://www.python.org/dev/peps/pep-0420). However, `pylint` seems to have a problem with that, thus I had to create the `__init__.py` file with the namespace declaration.

There are users experiencing the same, for example @scottschreckengaust in https://github.com/PyCQA/pylint/issues/2862#issuecomment-640871851.

**Comment by DanielNoord** [comment] 2022-04-20 13:48
@Gidgidonihah Can you still reproduce this? I have been trying to reproduce this on `main`, but wasn't able to.

**Comment by jacobtylerwalls** [comment] 2022-07-03 03:21
I also tried to repro and couldn't. Feel free to reopen if you can provide steps to reproduce on a current version. Thanks.

**Closed by jacobtylerwalls** 2022-07-03 03:21 UTC
Labels: Bug :beetle:, topic-import-system, namespace-package
