### ISSUE TITLE
Unable to create cache directory

### ISSUE THREAD

**Issue by GergelyKalmar** [PyCQA/pylint#4964] opened 2021-09-04 13:22 UTC
### Bug description

I have a test that runs a pytest session using [Pytester](https://docs.pytest.org/en/6.2.x/reference.html#pytester) and executes pylint through the pytest-pylint plugin. Under these circumstances I'm getting the following error:
```
tests/pytest_project/test_core.py::test_run_errors Unable to create directory /tmp/pytest-of-user/pytest-1/test_run_errors0/.cache/pylint
Unable to create file /tmp/pytest-of-user/pytest-1/test_run_errors0/.cache/pylint/test_run_errors1.stats: [Errno 2] No such file or directory: '/tmp/pytest-of-user/pytest-1/test_run_errors0/.cache/pylint/test_run_errors1.stats'
```

If I create the `.cache` folder manually it succeeds. However, it would be great if pylint could create the necessary parent folders are well when trying to create the `pylint` folder inside `XDG_CACHE_HOME`.

### Command used

Pylint is invoked indirectly through pytest-pylint.

### Pylint output

See error above.

### Expected behavior

I would expect that the Pylint cache folder creation succeeds even if `XDG_CACHE_HOME` does not exist.

### Pylint version

```shell
pylint 2.10.2
```

**Comment by Pierre-Sassoulas** [comment] 2021-09-07 12:35
Duplicate of #4900

**Closed by Pierre-Sassoulas** 2021-09-07 12:35 UTC
Labels: bug, duplicate
