### ISSUE TITLE
No name 'core' in module 'distutils' 

### ISSUE THREAD

**Issue by YifeiZuo01** [PyCQA/pylint#1691] opened 2017-10-04 10:55 UTC
### Steps to reproduce
`from distutils.core import setup `

### Current behavior
warnings 

### Expected behavior
import without warnings

### pylint --version output
1.7.2

### astroid version
1.5.3

### python version
2.7.9

**Comment by rogalski** [comment] 2017-10-04 12:46
Dupe of #73?

**Comment by PCManticore** [comment] 2017-10-12 07:37
Looks like it.

**Closed by PCManticore** 2017-10-12 07:37 UTC
