### ISSUE TITLE
Single letter classnames wrongly cause C0103 (invalid-name)

### ISSUE THREAD

**Issue by Starwort** [PyCQA/pylint#3324] opened 2019-12-29 15:31 UTC
### Steps to reproduce
1. `from typing import TypeVar`
2. `T = TypeVar('T')`
3. `C0103: Class name "T" doesn't conform to PascalCase naming style (invalid-name)`

### Current behaviour
`C0103: Class name "T" doesn't conform to PascalCase naming style (invalid-name)`

### Expected behaviour
no C0103

### pylint --version output
pylint 2.4.3
astroid 2.3.1
Python 3.8.0 (default, Oct 15 2019, 14:05:58) 
[GCC 7.4.0]

**Comment by PCManticore** [comment] 2019-12-30 15:26
This is a duplicate of https://github.com/PyCQA/pylint/issues/2018. The issue is that the naming styles need at least 3 characters by default so `T` fails the check since it is too short. You can check that yourself by passing `--include-naming-hint=y` which will show the regular expression against which the name is validated.

**Closed by PCManticore** 2019-12-30 15:26 UTC

**Comment by phiresky** [comment] 2022-02-08 10:57
It would be good if there was a way to make pylint recognize this correctly as a type variable instead of a "class name", since the usual convention for type variables is to be single-letter (as opposed to class names).

I don't want to disable the lint for real class names, but I do want to disable it for type vars.

**Comment by DanielNoord** [comment] 2022-02-08 10:58
We're working on this in #5221. It (hopefully) will be part of the next version!

**Comment by phiresky** [comment] 2022-02-08 11:01
Great! I guess this issue is really a dupe of #3401 then instead of #2018 (referencing since I found only this one via google)

**Comment by DanielNoord** [comment] 2022-02-08 11:03
You're right! Thanks for pointing that out 😄
