### ISSUE TITLE
Traceback on every run

### ISSUE THREAD

**Issue by chrisspen** [PyCQA/pylint#1292] opened 2017-01-25 19:03 UTC
### Steps to reproduce
1. Install pylint==1.6.5
2. Run any pylint, e.g. pylint --version
3. Receive error:

    Traceback (most recent call last):
      File "/myproject/.env/bin/pylint", line 11, in <module>
        sys.exit(run_pylint())
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/__init__.py", line 17, in run_pylint
        Run(sys.argv[1:])
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/lint.py", line 1252, in __init__
        linter.load_default_plugins()
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/lint.py", line 491, in load_default_plugins
        checkers.initialize(self)
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 118, in initialize
        register_plugins(linter, __path__[0])
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/utils.py", line 978, in register_plugins
        module = load_module_from_file(join(directory, filename))
      File "/myproject/.env/local/lib/python2.7/site-packages/astroid/modutils.py", line 217, in load_module_from_file
        return load_module_from_modpath(modpath, path, use_sys)
      File "/myproject/.env/local/lib/python2.7/site-packages/astroid/modutils.py", line 180, in load_module_from_modpath
        module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/checkers/design_analysis.py", line 20, in <module>
        from pylint.checkers.utils import check_messages
      File "/myproject/.env/local/lib/python2.7/site-packages/pylint/checkers/utils.py", line 39, in <module>
        astroid.DictComp, astroid.GeneratorExp)
    AttributeError: 'module' object has no attribute 'GeneratorExp'

**Comment by PCManticore** [comment] 2017-01-25 19:14
Thank you for reporting this. What astroid version do you have installed?

**Comment by chrisspen** [comment] 2017-01-25 20:39
Pip reports `astroid==1.4.9`, which is the most recent version available on PyPI.

I've temporarily worked around this issue by downgrading pylint to the previous version.

**Comment by PCManticore** [comment] 2017-01-25 20:44
Just tested with the same versions and it works perfectly. Can you try to see what astroid is pylint importing and if it has a GeneratorExp member? (it should have).

**Comment by PCManticore** [comment] 2017-02-07 17:07
Let's close this, as we cannot reproduce it and don't have enough information for doing it.

**Closed by PCManticore** 2017-02-07 17:07 UTC
