### ISSUE TITLE
pylint crashed with a AstroidError

### ISSUE THREAD

**Issue by owillebo** [PyCQA/pylint#7392] opened 2022-09-01 09:53 UTC
### Bug description

```python
﻿class SomeClass:
    def __init__(self):
        self.someMember = []

    def someFunction(self):
        for c in self.someMember:
            del c

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\lint\pylinter.py", line 769, in _lint_file
    check_astroid_module(module)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\lint\pylinter.py", line 1029, in check_astroid_module
    retval = self._check_astroid_module(
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\lint\pylinter.py", line 1079, in _check_astroid_module
    walker.walk(node)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\utils\ast_walker.py", line 93, in walk
    self.walk(child)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\utils\ast_walker.py", line 93, in walk
    self.walk(child)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\utils\ast_walker.py", line 93, in walk
    self.walk(child)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\utils\ast_walker.py", line 90, in walk
    callback(astroid)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\checkers\modified_iterating_checker.py", line 60, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\checkers\modified_iterating_checker.py", line 66, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\checkers\modified_iterating_checker.py", line 96, in _modified_iterating_check
    args=(iter_obj.name,),
AttributeError: 'Attribute' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\lint\pylinter.py", line 734, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\lint\pylinter.py", line 771, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
pylint okko.py
```

### Pylint output

```shell
************* Module okko
okko.py:1:0: C0114: Missing module docstring (missing-module-docstring)
okko.py:1:0: C0115: Missing class docstring (missing-class-docstring)
okko.py:3:8: C0103: Attribute name "someMember" doesn't conform to snake_case naming style (invalid-name)
okko.py:5:4: C0116: Missing function or method docstring (missing-function-docstring)
okko.py:5:4: C0103: Method name "someFunction" doesn't conform to snake_case naming style (invalid-name)
Exception on node <For l.6 at 0x20a495fc820> in file 'C:\Users\Okko Willeboordse\Desktop\okko.py'
Traceback (most recent call last):
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\utils\ast_walker.py", line 90, in walk
    callback(astroid)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\checkers\modified_iterating_checker.py", line 60, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\checkers\modified_iterating_checker.py", line 66, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "C:\Users\Okko Willeboordse\AppData\Roaming\Python\Python39\site-packages\pylint\checkers\modified_iterating_checker.py", line 96, in _modified_iterating_check
    args=(iter_obj.name,),
AttributeError: 'Attribute' object has no attribute 'name'
okko.py:1:0: F0002: okko.py: Fatal error while checking 'okko.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\Okko Willeboordse\AppData\Local\pylint\pylint\Cache\pylint-crash-2022-09-01-11-48-09.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

No crash

### Pylint version

```shell
pylint 2.15.0
astroid 2.12.5
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

### OS / Environment

Edition	Windows 11 Pro
Version	21H2
Installed on	‎11/‎24/‎2021
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0

**Comment by DanielNoord** [comment] 2022-09-01 09:55
Fixed in #7386 and duplicate of #7380.

I expect a patch release with this fix somewhere this week. Sorry for the inconvenience!

**Closed by DanielNoord** 2022-09-01 09:55 UTC
Labels: Needs triage :inbox_tray:

**Comment by owillebo** [comment] 2022-09-01 10:10
Thanks Daniël,

I only checked open issues not expecting you to fix the issue so fast!

Next time I will check all the issues.

Have a nice day,

Okko

**Comment by Pierre-Sassoulas** [comment] 2022-09-01 10:11
I'm going to release 2.15.1 asap. There is only one real bug fixed but it's a crash and there are some astroid bugs that are fixed automatically upon re installation with the latest astroid too. We might as well release a version that guarantee the right version of astroid being installed.

**Comment by DanielNoord** [comment] 2022-09-01 11:26
> Thanks Daniël, I only checked open issues not expecting you to fix the issue so fast! Next time I will check all the issues. Have a nice day, Okko
> […](#)

No worries! I tend to forget to check closed issues as well 😄
