### ISSUE TITLE
atom reports error of pylint when openning a python source file

### ISSUE THREAD

**Issue by yifannie** [PyCQA/pylint#1769] opened 2017-12-13 20:08 UTC
### Steps to reproduce
1. installed linter-pylint 2.1
2. installed atom 1.3.1
3. installed linter 2.0

### Current behavior
linter-registry.js [sm]:144 [Linter] Error running Pylint Error: Traceback (most recent call last):
  File "/u/nieyifan/anaconda2/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 1222, in __init__
    linter.load_default_plugins()
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 453, in load_default_plugins
    checkers.initialize(self)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 114, in initialize
    register_plugins(linter, __path__[0])
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/utils.py", line 992, in register_plugins
    module = modutils.load_module_from_file(join(directory, filename))
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/modutils.py", line 272, in load_module_from_file
    return load_module_from_modpath(modpath, path, use_sys)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/checkers/python3.py", line 100, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/checkers/python3.py", line 501, in Python3Checker
    'sys.version_info < (3, 0)',
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 624, in repr_tree
    _repr_tree(self, result, set())
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 613, in _repr_node
    depth)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 613, in _repr_node
    depth)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 191, in dispatch
    impl = _find_impl(cls, registry)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 142, in _find_impl
    mro = _compose_mro(cls, registry.keys())
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 130, in _compose_mro
    return _c3_mro(cls, abcs=mro)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 84, in _c3_mro
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 88, in _c3_mro
    [explicit_bases] + [abstract_bases] + [other_bases]
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 39, in _c3_merge
    raise RuntimeError("Inconsistent hierarchy")
RuntimeError: Inconsistent hierarchy
    at Object.<anonymous> (/u/nieyifan/.atom/packages/linter-pylint/lib/main.js:161:17)
    at next (<anonymous>)
    at step (/u/nieyifan/.atom/packages/linter-pylint/lib/main.js:7:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ linter-registry.js [sm]:144
workspace-element.coffee:104 Handling of 'mousewheel' input event was delayed for 826 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

### Expected behavior
execute pylint

### pylint --version output

Traceback (most recent call last):
  File "/u/nieyifan/anaconda2/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 1222, in __init__
    linter.load_default_plugins()
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/lint.py", line 453, in load_default_plugins
    checkers.initialize(self)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 114, in initialize
    register_plugins(linter, __path__[0])
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/utils.py", line 992, in register_plugins
    module = modutils.load_module_from_file(join(directory, filename))
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/modutils.py", line 272, in load_module_from_file
    return load_module_from_modpath(modpath, path, use_sys)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/checkers/python3.py", line 100, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/pylint/checkers/python3.py", line 501, in Python3Checker
    'sys.version_info < (3, 0)',
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 624, in repr_tree
    _repr_tree(self, result, set())
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 613, in _repr_node
    depth)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/astroid/node_classes.py", line 613, in _repr_node
    depth)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 191, in dispatch
    impl = _find_impl(cls, registry)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 142, in _find_impl
    mro = _compose_mro(cls, registry.keys())
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 130, in _compose_mro
    return _c3_mro(cls, abcs=mro)
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 84, in _c3_mro
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 88, in _c3_mro
    [explicit_bases] + [abstract_bases] + [other_bases]
  File "/u/nieyifan/anaconda2/lib/python2.7/site-packages/singledispatch.py", line 39, in _c3_merge
    raise RuntimeError("Inconsistent hierarchy")
RuntimeError: Inconsistent hierarchy

**Comment by PCManticore** [comment] 2018-04-05 05:44
Closed as duplicate of https://github.com/PyCQA/pylint/issues/1388.

**Closed by PCManticore** 2018-04-05 05:44 UTC
Labels: needs-reproduction
