### ISSUE TITLE
Intermediate release before a 2.0 ?

### ISSUE THREAD

**Issue by dzen** [PyCQA/pylint#874] opened 2016-04-15 15:47 UTC
Hello,

We're interested in a new pylint release, with for example the following commit:
https://github.com/PyCQA/pylint/commit/2ec342e612c730a266413783918f4a0d41441ca5

Thank you !

**Comment by moylop260** [comment] 2016-04-17 04:01
@PCManticore 
We are testing pylint-2.0.0 in all our projects and works fine!
Just there is a small issue https://github.com/PyCQA/pylint/issues/875

Now, we are using 2.0.0 version as our official version.
But we are installing with [git+git://github.com/PyCQA/pylint.git@master#egg=pylint](https://github.com/OCA/pylint-odoo/pull/21/files#diff-b4ef698db8ca845e5845c4618278f29aR1)

What about add the pylint-2.0.0.dev1 pre-release?

To install with `pip install --pre pylint>=2.0.0` and avoid use a `master branch` install.
In this case, If you use `pip install pylint` the last stable version will be installed.

```bash
pip install --help | grep "\-\-pre" -A1
  --pre                       Include pre-release and development versions. By default, pip
                              only finds stable versions.
```

**Comment by PCManticore** [comment] 2016-04-18 07:44
Please, don't use the master branch just yet, ergo 2.0! The problem is that 2.0 would be totally backward incompatible with 1.X, but we didn't finish what we were planning for astroid 2.0, which resulted in a stagnant pylint 2.0.  We weren't planning another minor release, but since we have to delay 2.0 even more, now we're in the situation where we need another point release. If you really want to use the next version, try the 1.6 branch instead, not the master.

**Comment by lescobarvx** [comment] 2016-04-18 16:22
@PCManticore 
pylint 1.6 requires astroid >=1.5.0 & <1.6.0 , and this doesn't have these released versions, the max released version is 1.4.5.
Can you release the version 1.5.0 of astroid?

**Comment by PCManticore** [comment] 2016-04-20 10:55
It's not released yet and it will take me a couple of days until it will be production ready (I have to cherry-pick some changes from 2.0 in the mean time, but the idea is that I want this finished until 1 may).  But if you really want to test it, you can work with astroid's master branch (https://github.com/PyCQA/astroid).

**Comment by PCManticore** [comment] 2016-05-09 15:46
For the record, I created a milestone for the next point release, 1.6: https://github.com/PyCQA/pylint/milestones/1.6.0. These are things that I'd like to have solved before releasing a new version, which I'll be trying to have it finished somewhere before the end of the may (the date of the milestone is marked as 8 june mostly for handling the release process, what features to cherry-pick or not). Any help would be appreciated, since it will move this faster. I'm closing this issue for now, we'll use the milestone page for tracking it.

**Closed by PCManticore** 2016-05-09 15:46 UTC
Labels: blocker
