### ISSUE TITLE
pylint segmentation fault with astroid==2.5.0 & tensorflow

### ISSUE THREAD

**Issue by awaizman1** [PyCQA/pylint#4101] opened 2021-02-16 17:29 UTC
### overview
on Feb 15 a new ```astroid==2.5.0``` was released. since then my CI fails on pylint halt.
I succeeded to create a simple example where pylint fails with segmentation fault with ```astroid==2.5.0``` and pass with previous ```astroid==2.4.2```

### Steps to reproduce
1. create a new venv with ```pylint==2.6.0``` and ```tensorflow==2.3.0```
2. make sure transitive ```astroid``` dependency is ```astroid==2.5.0```
3. create a dummy package my_pkg with ```__init__.py``` and the following ```test_utils.py``` file
```
import tensorflow as tf

def create_tf_model() -> tf.keras.models.Model:

    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])

    return model
```
4. run ```pylint --unsafe-load-any-extension=y``` - this will yield segmentation fault
5. now in same venv pip install astroid==2.4.2 and run step 4 again - this will pass

### Current behavior
```
my_venv/bin/pylint --unsafe-load-any-extension=y my_pkg
************* Module my_pkg.test_utils
my_pkg/test_utils.py:31:0: C0301: Line too long (107/100) (line-too-long)
my_pkg/test_utils.py:36:0: C0301: Line too long (118/100) (line-too-long)
my_pkg/test_utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
my_pkg/test_utils.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
Segmentation fault (core dumped)
```

### Expected behavior
same venv with astroid==2.4.2 pass
```
my_venv/bin/pylint --unsafe-load-any-extension=y my_pkg
************* Module my_pkg.test_utils
my_pkg/test_utils.py:31:0: C0301: Line too long (107/100) (line-too-long)
my_pkg/test_utils.py:36:0: C0301: Line too long (118/100) (line-too-long)
my_pkg/test_utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
my_pkg/test_utils.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
2021-02-16 19:19:29.437141: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-02-16 19:19:29.437172: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
my_pkg/test_utils.py:1:0: W0611: Unused Tuple imported from typing (unused-import)
my_pkg/test_utils.py:1:0: W0611: Unused Any imported from typing (unused-import)
my_pkg/test_utils.py:2:0: W0611: Unused import pathlib (unused-import)
my_pkg/test_utils.py:3:0: W0611: Unused numpy imported as np (unused-import)

--------------------------------------------------------------------
Your code has been rated at -1.43/10 (previous run: -1.43/10, +0.00)
```

### pylint --version output
pylint 2.6.0
astroid 2.5
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]

**Comment by Pierre-Sassoulas** [comment] 2021-02-16 19:46
Hello, thank you for the very clear way to reproduce, we're going to use this to check astroid before releasing 2.7. 

Regarding your current problem you can upgrade to pylint `2.6.2` where astroid is fixed to below `2.5` (or fix astroid below 2.5 yourself as you did).

**Comment by Pierre-Sassoulas** [comment] 2021-02-16 20:11
This is fixed on latest master (downloading tensorflow took some time 😄).

**Comment by Pierre-Sassoulas** [comment] 2021-02-16 20:14
Well I'm going to be cautious instead because I was not loading the dynamic lib, so maybe I cannot reproduce:
```
2021-02-16 21:12:36.709184: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-16 21:12:36.709264: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

**Comment by awaizman1** [comment] 2021-02-16 20:18
hi @Pierre-Sassoulas,

the tensorflow "Could not load dynamic library" is ok. it tries to load it and if fail it fallback to cpu (and not GPU) mode. this is not an error. (also the second line says you can safely ignore it)
In my env I get the same message since i'm running on a host without gpu

**Comment by Pierre-Sassoulas** [comment] 2021-02-20 18:53
I'm closing, because it seems like it's fixed.

**Closed by Pierre-Sassoulas** 2021-02-20 18:53 UTC
Labels: cannot reproduce, crash, regression
