### ISSUE TITLE
Display raw score in JSON report

### ISSUE THREAD

**Issue by Sam152** [PyCQA/pylint#4806] opened 2021-08-06 00:07 UTC
### Current problem

In `3.0.0a4`, it's possible to see the score in the JSON report, however it's formatted as a human readable string. 

### Desired solution

Allow the JSON report to include a float of the raw score out of 10 and potentially an extra human readable version too. Maybe something like:

```
{
  'score': 8.51,
  'score_summary': 'Your code has been rated at 8.51/10'
}
```

**Comment by Pierre-Sassoulas** [comment] 2021-08-06 05:14
Duplicate of #4741

**Closed by Pierre-Sassoulas** 2021-08-06 05:14 UTC
Labels: enhancement, needs triage
