### ISSUE TITLE
`redefined-variable-type` when using `enum.Enum`

### ISSUE THREAD

**Issue by Hibou57** [PyCQA/pylint#836] opened 2016-03-07 06:10 UTC
Given this:

    from enum import Enum

    class E(Enum):
        A = 0
        B = 1
        C = 2

    def f(x):
        if x == 0:
            result = E.A
        elif x == 1:
            result = E.B
        elif x == 2:
            result = E.C
        else:
            raise RuntimeError
        return result

PyLint complains `redefined-variable-type` on `result = E.B`. The same if E is of class `IntEnum` instead of `Enum`.

**Comment by The-Compiler** [comment] 2016-03-07 06:32
Closing as a duplicate of #777 - note `redefined-variable-type` will also be an extension (which is disabled by default) in 2.0.

**Closed by The-Compiler** 2016-03-07 06:32 UTC

**Comment by Hibou57** [comment] 2016-03-07 08:57
> note `redefined-variable-type` will also be an extension (which is disabled by default) in 2.0.

I believe this won't hurt when classes and named‑tuples are used like discriminated records (or sum types, are they are formally named). I indeed often end to add `# pylint: disable=redefined-variable-type`.

**Comment by The-Compiler** [comment] 2016-03-07 09:00
yeah, I personally ended up disabling that rule completely :wink:
