### ISSUE TITLE
Pylint 2.8 broke Pylint-quotes

### ISSUE THREAD

**Issue by PhilippeFerreiraDeSousa** [PyCQA/pylint#4411] opened 2021-04-26 16:17 UTC
Hi,
I believe that this repo is also maintaining Pylint-quotes. Pylint-quotes broke with Pylint 2.8, I had to downgrade Pylint to 2.7.4 in my CI:
![image](https://user-images.githubusercontent.com/17492851/116116479-0e378680-a670-11eb-9880-556e089d3d62.png)

Note: I am not sure what pylint-quotes do or why I need it. I apologize if this is a deprecated package that shouldn't be used.

**Comment by Pierre-Sassoulas** [comment] 2021-04-26 16:23
Hello, this is a duplicate of #4407 and should be fixed in pylint ``2.8.2``, we just released it :)  (Do ``pip install -U pylint``)

**Closed by Pierre-Sassoulas** 2021-04-26 16:23 UTC
Labels: duplicate
