### ISSUE TITLE
fatal error for (wrong-import-position) and can't write the issue template for the crash

### ISSUE THREAD

**Issue by songtoy** [PyCQA/pylint#5975] opened 2022-03-25 08:53 UTC
### Bug description

So today I run the style-test of CICD for my on our GitLab site, and it got fatal errors. But locally the test was passed. 

Then I re-ran the style-test task that got passed result two days ago, and it got a failed result!

Therefore,  I figure that I should open an issue for it, as the message suggested.

the code is as follows. (I only add code environment for lines started with '#', due to markdown mechanism.)
--------------------------------------------------------------
```python
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from os import path

# Build paths inside the project like this: BASE_DIR / 'subdir'.`
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production`
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/`

# SECURITY WARNING: keep the secret key used in production secret!`
SECRET_KEY = 'django-insecure-77h-thag_e5k2+s7j!$=iz%a4_6%!_h-7tx8(wp$p2)pxzcu1a'

# SECURITY WARNING: don't run with debug turned on in production!`
DEBUG = True`

ALLOWED_HOSTS = ['*']`
```

### Command used

```shell
pylint backend
```

### Pylint output

```shell
************* Module backend.settings
backend/settings.py:13:0: C0413: Import "from pathlib import Path" should be placed at the top of the module (wrong-import-position)
backend/settings.py:14:0: C0413: Import "from os import path" should be placed at the top of the module (wrong-import-position)
Can't write the issue template for the crash in /opt/app/.cache/pylint/pylint-crash-2022-03-25-08.txt.
backend/settings.py:1:0: F0001: Fatal error while checking 'backend/settings.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/opt/app/.cache/pylint/pylint-crash-2022-03-25-08.txt'. (fatal)
```

### Expected behavior

expected to be normal, with no error.

### Pylint version

```shell
pylint 2.13.0
astroid 2.11.1
Python 3.8.5 (default, Sep 10 2020, 16:47:10)
[GCC 8.3.0]
```

### OS / Environment

Linux version 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 1301:11:19 UTC 2021

### Additional dependencies

asgiref==3.5.0
astroid==2.11.1
backports.zoneinfo==0.2.1
certifi==2021.10.8
charset-normalizer==2.0.12
dill==0.3.4
Django==4.0.3
docker==5.0.3
gunicorn==20.1.0
idna==3.3
isort==5.10.1
lazy-object-proxy==1.7.1
MarkupSafe==2.0.1
mccabe==0.7.0
platformdirs==2.5.1
prometheus-client==0.7.1
pylint==2.13.0
pylint-django==2.5.2
pylint-plugin-utils==0.7
requests==2.27.1
rfc3987==1.3.8
SQLAlchemy==1.3.24
sqlparse==0.4.2
tomli==2.0.1
typing-extensions==4.1.1
urllib3==1.26.9
websocket-client==1.3.1
wrapt==1.14.0

**Comment by DanielNoord** [comment] 2022-03-25 08:56
Likely a duplicate of #5970.

@songtoy Are you able to provide the template that the `pylint` log mentions? That should include the backtrace which shows where `pylint` crashed.

**Comment by songtoy** [comment] 2022-03-25 09:01
I'm sorry but I cannot find the template you mentioned @DanielNoord. 

'Can't write the issue template for the crash in /opt/app/.cache/pylint/pylint-crash-2022-03-25-08.txt.'

this message was included in the log.

**Comment by DanielNoord** [comment] 2022-03-25 09:02
Does it work when you try to run this check locally?

**Comment by songtoy** [comment] 2022-03-25 09:09
Everything looks good locally. The version of pylint is 2.12.2 locally.

**Comment by songtoy** [comment] 2022-03-25 09:11
Oh, I just reinstall the pylint of version 2.12.2 and the error disappear on remote server.

**Comment by DanielNoord** [comment] 2022-03-25 09:11
There is a incompatibility with `pylint` `2.13` and the latest version of `pylint-django`. However, looking at the commits of `pylint-django` I expect a bug fix release of `pylint-django` in a couple of hours (1/2).

So you should be able to upgrade to `2.13` both in CI and locally then.

You can subscribe to #5970 to see when this gets fixed 😄

**Comment by Pierre-Sassoulas** [comment] 2022-03-25 09:13
We're going to fix this in 2.13.1 if it's really a duplicate, you should be able to upgrade pylint again after that. (Or if pylint-django release a new version).

**Comment by songtoy** [comment] 2022-03-25 09:15
So I update pylint locally to 2.13.0, and I reproduce the fatal error. Yeah, I think I met the same problem with #5970.

```
 ```

pylint crashed with a ``TypeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1111, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 78, in walk
    callback(astroid)
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint_django/augmentations/__init__.py", line 770, in wrap_func
    return with_method(orig_method, *args, **kwargs)
  File "/Users/sonterzhou/Software/anaconda3/envs/SoftwareEngineering/lib/python3.9/site-packages/pylint_django/augmentations/__init__.py", line 339, in ignore_import_warnings_for_related_fields
    consumer._atomic = ScopeConsumer(new_things, consumer.consumed, consumer.scope_type)  # pylint: disable=W0212
TypeError: <lambda>() missing 1 required positional argument: 'scope_type'
```

**Comment by songtoy** [comment] 2022-03-25 09:16
Got it. Many Thanks!

**Comment by DanielNoord** [comment] 2022-03-25 09:16
Closing this a duplicate then. Sorry for the inconvenience @songtoy!

**Closed by DanielNoord** 2022-03-25 09:16 UTC
Labels: Duplicate 🐫, Crash 💥
