### ISSUE TITLE
RuntimeError inconsistent hierarchy when "pylint" command is issued

### ISSUE THREAD

**Issue by pradeeps** [PyCQA/pylint#1494] opened 2017-05-23 11:39 UTC
### Steps to reproduce
1.  pip install pylint
2.  run pylint in commandline
3.  RuntimeError: Inconsistent hierarchy

### Current behavior
Results in error: 

> Traceback (most recent call last):
>   File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "c:\python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\python27\scripts\pylint.exe\__main__.py", line 9, in <module>
>   File "c:\python27\lib\site-packages\pylint\__init__.py", line 13, in run_pylint
>     Run(sys.argv[1:])
>   File "c:\python27\lib\site-packages\pylint\lint.py", line 1220, in __init__
>     linter.load_default_plugins()
>   File "c:\python27\lib\site-packages\pylint\lint.py", line 453, in load_default_plugins
>     checkers.initialize(self)
>   File "c:\python27\lib\site-packages\pylint\checkers\__init__.py", line 114, in initialize
>     register_plugins(linter, __path__[0])
>   File "c:\python27\lib\site-packages\pylint\utils.py", line 992, in register_plugins
>     module = modutils.load_module_from_file(join(directory, filename))
>   File "c:\python27\lib\site-packages\astroid\modutils.py", line 272, in load_module_from_file
>     return load_module_from_modpath(modpath, path, use_sys)
>   File "c:\python27\lib\site-packages\astroid\modutils.py", line 233, in load_module_from_modpath
>     module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
>   File "c:\python27\lib\site-packages\pylint\checkers\python3.py", line 100, in <module>
>     class Python3Checker(checkers.BaseChecker):
>   File "c:\python27\lib\site-packages\pylint\checkers\python3.py", line 501, in Python3Checker
>     'sys.version_info < (3, 0)',
>   File "c:\python27\lib\site-packages\astroid\node_classes.py", line 624, in repr_tree
>     _repr_tree(self, result, set())
>   File "c:\python27\lib\site-packages\singledispatch.py", line 210, in wrapper
>     return dispatch(args[0].__class__)(*args, **kw)
>   File "c:\python27\lib\site-packages\astroid\node_classes.py", line 613, in _repr_node
>     depth)
>   File "c:\python27\lib\site-packages\singledispatch.py", line 210, in wrapper
>     return dispatch(args[0].__class__)(*args, **kw)
>   File "c:\python27\lib\site-packages\astroid\node_classes.py", line 613, in _repr_node
>     depth)
>   File "c:\python27\lib\site-packages\singledispatch.py", line 210, in wrapper
>     return dispatch(args[0].__class__)(*args, **kw)
>   File "c:\python27\lib\site-packages\singledispatch.py", line 191, in dispatch
>     impl = _find_impl(cls, registry)
>   File "c:\python27\lib\site-packages\singledispatch.py", line 142, in _find_impl
>     mro = _compose_mro(cls, registry.keys())
>   File "c:\python27\lib\site-packages\singledispatch.py", line 130, in _compose_mro
>     return _c3_mro(cls, abcs=mro)
>   File "c:\python27\lib\site-packages\singledispatch.py", line 84, in _c3_mro
>     other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
>   File "c:\python27\lib\site-packages\singledispatch.py", line 88, in _c3_mro
>     [explicit_bases] + [abstract_bases] + [other_bases]
>   File "c:\python27\lib\site-packages\singledispatch.py", line 39, in _c3_merge
>     raise RuntimeError("Inconsistent hierarchy")
> RuntimeError: Inconsistent hierarchy

### Expected behavior
give usage information or throw too few arguments

### pylint --version output
I get the same error when I try to check pylint version. But it tries to install 1.7.1.

**Comment by rogalski** [comment] 2017-05-23 12:03
Duplicate of #1388

**Closed by rogalski** 2017-05-23 12:03 UTC

**Comment by zeroincombenze** [comment] 2018-11-14 14:09
I met same error when upgrade pylint 1.8.4.
Down upgrade to 1.6.4 and it works.
Warning: if locally installed (pip --user) check for local version
