### ISSUE TITLE
Suspicious state from syntax checker python-pylint/astroid.exceptions.TooManyLevelsError: Relative import with too many levels (1) for module 'flycheck_AUtils'

### ISSUE THREAD

**Issue by qohelet** [PyCQA/pylint#4932] opened 2021-08-30 14:54 UTC
### Bug description

I'm using emacs/flycheck with pylint for my python development. 

When editing a file the messages-buffer constantly shows up and gives me the following message:

Suspicious state from syntax checker python-pylint: Flycheck checker python-pylint returned 1, but its output contained no errors: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/pylint/__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "/usr/lib/python3.9/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/pylint/lint/run.py", line 384, in __init__
    linter.check(args)
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 975, in check
    self._check_files(
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1009, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1035, in _check_file
    check_astroid_module(ast_node)
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1172, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1217, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 74, in walk
    callback(astroid)
  File "/usr/lib/python3.9/site-packages/pylint/checkers/deprecated.py", line 112, in visit_importfrom
    basename = get_import_name(node, basename)
  File "/usr/lib/python3.9/site-packages/pylint/checkers/utils.py", line 1552, in get_import_name
    modname = root.relative_to_absolute_name(
  File "/usr/lib/python3.9/site-packages/astroid/scoped_nodes.py", line 726, in relative_to_absolute_name
    raise TooManyLevelsError(level=level, name=self.name)
astroid.exceptions.TooManyLevelsError: Relative import with too many levels (1) for module 'flycheck_AUtils'
Exception on node <ImportFrom l.15 at 0x7f5ce4f46a30> in file '/home/qohelet/MOP/pyara/flycheck_AUtils.py'
```

All the packages have been upgraded. I googled the error but couldn't find anything related. I asked already at flycheck: https://github.com/flycheck/flycheck/issues/1899
They refer me to pylint and here I am.

### Command used

```shell
pylint-python
(emacs)
```

### Pylint output

```shell
-*- mode: compilation; default-directory: "~/MOP/pytesting/Testing/" -*-
Compilation started at Tue Aug 24 16:18:31

/usr/bin/python3 -c import\ sys\;sys.path.pop\(0\)\;import\ runpy\;runpy.run_module\(\"pylint\"\) --reports\=n --output-format\=json /home/qohelet/MOP/pytesting/Testing/AUTests.py
[
    {
        "type": "convention",
        "module": "AUTests",
        "obj": "",
        "line": 37,
        "column": 0,
        "path": "AUTests.py",
        "symbol": "line-too-long",
        "message": "Line too long (136/100)",
        "message-id": "C0301"
    },
    {
        "type": "convention",
        "module": "AUTests",
        "obj": "",
        "line": 154,
        "column": 0,
        "path": "AUTests.py",
        "symbol": "line-too-long",
        "message": "Line too long (131/100)",
        "message-id": "C0301"
    },
    {
        "type": "convention",
        "module": "AUTests",
        "obj": "",
        "line": 195,
        "column": 0,
        "path": "AUTests.py",
        "symbol": "line-too-long",
        "message": "Line too long (122/100)",
        "message-id": "C0301"
    },
    {
        "type": "convention",
        "module": "AUTests",
        "obj": "",
        "line": 1,
        "column": 0,
        "path": "AUTests.py",
        "symbol": "invalid-name",
        "message": "Module name \"AUTests\" doesn't conform to snake_case naming style",
        "message-id": "C0103"
    },
    {
        "type": "convention",
        "module": "AUTests",
        "obj": "",
        "line": 1,
        "column": 0,
        "path": "AUTests.py",
        "symbol": "missing-module-docstring",
        "message": "Missing module docstring",
        "message-id": "C0114"
    },
.... And so on and so forth...
    {
        "type": "convention",
        "module": "AUTests",
        "obj": "",
        "line": 20,
        "column": 0,
        "path": "AUTests.py",
        "symbol": "ungrouped-imports",
        "message": "Imports from package pyara are not grouped",
        "message-id": "C0412"
    }
]

Compilation exited abnormally with code 30 at Tue Aug 24 16:18:37
```

### Expected behavior

The pop-up almost constantly shows up when I edit something in the code. Red/orange underlining of the problematic lines should be the enough. Also if I specifically call pylint a pop-up is fine. But not on any random input

### Pylint version

```shell
2.10.2
(but the Installation doesn't seem to be required for emacs)
Emacs executes it differently
```

### OS / Environment

Download Fedora 34 Scientific

### Additional dependencies

```
ansible==4.3.0
ansible-core==2.11.3
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
incremental==16.10.1
Jinja2==3.0.1
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
macaroonbakery==1.3.1
MarkupSafe==2.0.1
netifaces==0.10.4
oauthlib==3.1.0
packaging==21.0
pexpect==4.6.0
protobuf==3.6.1
psutil==5.5.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycups==1.9.73
pylint==2.10.2
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.5
python-debian===0.1.36ubuntu1
pytz==2019.3
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
resolvelib==0.5.4
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sos==4.1
ssh-import-id==5.10
systemd-python==234
Twisted==18.9.0
ubuntu-advantage-tools==27.2
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
zope.interface==4.7.1
```

**Comment by DanielNoord** [comment] 2022-01-15 11:54
@qohelet Could you provide the code you're working on and that causes this? Specifically `home/qohelet/MOP/pyara/flycheck_AUtils.py` which seems to be causing the issue. I'm not sure how `flycheck` works but I can do some investigation with a code example.

**Comment by DanielNoord** [comment] 2022-06-09 11:31
We keep moving this on the milestone but do not have a reproducible example. Perhaps we should just close this and reopen if more details are provided? We can't do much with this in its current state.

**Closed** 2022-06-09 11:35 UTC
Labels: Bug 🪳, Cannot Reproduce 🤷, Crash 💥, Waiting For Author
