### ISSUE TITLE
How do I use stub pyi files with pylint

### ISSUE THREAD

**Issue by daltairwalter** [PyCQA/pylint#5007] opened 2021-09-14 16:55 UTC
### Question

I have stub pyi files and pylint doesn't seem to be using them.

I have tried renaming them to py and deleting the pyd files and this mostly works.  One specific problem with this technique though is that I see the error "assignment-from-no-return" on functions.

As an example, if my .pyi file - renamed to .py has the following:
`def getPlatform() -> str: ...`

I see errors for "assignment-from-no-return" in other places for code like this:
`platform = infoModule.getPlatform()`

Is there a better way of using stub pyi files?

### Documentation for future user

I expected to see a section heading about using stubs in the help - or for the stubs to just be used and work.

**Comment by DetachHead** [comment] 2021-11-09 04:03
duplicate of #4987?

**Comment by Pierre-Sassoulas** [comment] 2021-11-09 08:33
Look like this one has better SEO but was created later. I'm going to close as duplicate and change the title of the other one. Thank you @DetachHead (Just curious are you participating in closember ?) !

**Closed by Pierre-Sassoulas** 2021-11-09 08:33 UTC
Labels: question, documentation
