### ISSUE TITLE
unable to install Pylint on 

### ISSUE THREAD

**Issue by aearm** [PyCQA/pylint#3720] opened 2020-07-02 08:05 UTC
### Steps to reproduce
1. Mac 10.15.5 
2.Python 3.8.3
3.PIP 20.1.1

### Current behavior

ERROR: Command errored out with exit status 1:
   ``` command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/3t/wkmnwm7j6310k4493z5s4tfh0000gn/T/tmp23if9vtc
       cwd: /private/var/folders/3t/wkmnwm7j6310k4493z5s4tfh0000gn/T/pip-install-ne_7dzvp/lazy-object-proxy
  Complete output (8 lines):
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 259, in main
      hook_input = read_json(pjoin(control_dir, 'input.json'))
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in read_json
      return json.load(f)
  AttributeError: module 'json' has no attribute 'load'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/3t/wkmnwm7j6310k4493z5s4tfh0000gn/T/tmp23if9vtc Check the logs for full command output. ``` 
### Expected behavior


### pylint --version output

**Comment by dbaty** [comment] 2020-09-06 15:42
The provided output seems to be from the `pip install pylint` command. So I don't think the issue is related to pylint at all.

My guess: you have a "json.py" file in the directory from which you are running `pip`. It gets picked up by `pip` instead of the standard `json` module from Python standard library.

**Comment by AWhetter** [comment] 2020-09-08 05:06
Closing as this looks like an issue on your side @aearm, but let us know if you need any more help.

**Closed by AWhetter** 2020-09-08 05:06 UTC
