### ISSUE TITLE
Incorrect report of undefined variable in nested lambdas

### ISSUE THREAD

**Issue by chrisspen** [PyCQA/pylint#2273] opened 2018-07-11 17:56 UTC
### Steps to reproduce
1. Create a file with the code:

    func = lambda v: lambda: v+1

2. Check with pylint
3. Receive error:

    Undefined variable 'v' (undefined-variable)

### Current behavior

Pylint incorrectly thinks a lambda inside a lambda does not have access to any of the variables in the parent lambda, and so reports any usage of those variables as missing, when they are not.

### Expected behavior

The above code should not trigger an "undefined-variable" error.

### pylint --version output

    pylint 1.9.2

**Comment by brycepg** [comment] 2018-07-11 18:35
Duplicate of #760 
Needs a PR

**Closed by brycepg** 2018-07-11 18:35 UTC

**Comment by brycepg** [comment] 2018-07-12 17:33
@chrisspen I get this fixed on pylint master branch. Thanks for the report

**Comment by chrisspen** [comment] 2018-07-12 17:56
@brycepg Thanks!
