### ISSUE TITLE
Other example of maximum recursion depth

### ISSUE THREAD

**Issue by Rogdham** [PyCQA/pylint#2463] opened 2018-08-31 15:47 UTC
Not sure if it is a duplicate of #2388, feel free to close this issue it if that's the case.

### Steps to reproduce

Run `pylint` on the following code:

```python
import os

ABC = os.path.realpath('abc')
DEF = os.path.realpath(ABC + 'def')
GHI = os.path.join(DEF, 'ghi')
```

### Current behavior

It fails with `RecursionError: maximum recursion depth exceeded`; [full trace here](https://github.com/PyCQA/pylint/files/2340684/trace.txt).

However, it works with the argument `--init-hook="import sys; sys.setrecursionlimit(2000)"` (taken from #2388).

### Expected behavior

Pylint should not crash.

### pylint --version output

```
$ pylint --version
pylint 2.1.1
astroid 2.0.4
Python 3.7.0 (default, Jul 15 2018, 10:44:58)
[GCC 8.1.1 20180531]
```

**Comment by PCManticore** [comment] 2018-08-31 16:53
Is this the exact script that reproduces the problem for you? I cannot reproduce it locally, do you have any local plugins installed?

**Comment by Rogdham** [comment] 2018-08-31 17:31
Here is what I did:

```
$ mkdir /tmp/foo
$ cd /tmp/foo
$ virtualenv venv
Using base prefix '/usr'
New python executable in /tmp/foo/venv/bin/python
Installing setuptools, pip, wheel...done.
$ . ./venv/bin/activate
$ pip install pylint

--snip--

$ cat > a.py << EOF
import os
ABC = os.path.realpath('abc')
DEF = os.path.realpath(ABC + 'def')
GHI = os.path.join(DEF, 'ghi')
EOF
$ pylint a.py
************* Module a
a.py:1:0: C0111: Missing module docstring (missing-docstring)
Traceback (most recent call last):
  File "/tmp/foo/venv/lib/python3.7/site-packages/astroid/__init__.py", line 89, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function register_builtin_transform.<locals>._transform_wrapper at 0x7fc715c7aea0>, <Call l.1044 at 0x7fc7155a87b8>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

--snip, same trace as before--

RecursionError: maximum recursion depth exceeded
$ pylint --version
pylint 2.1.1
astroid 2.0.4
Python 3.7.0 (default, Jul 15 2018, 10:44:58)
[GCC 8.1.1 20180531]
$ pip freeze
astroid==2.0.4
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pylint==2.1.1
six==1.11.0
wrapt==1.10.11
$ python -V
Python 3.7.0
```
If that can help, my OS is ArchLinux.

If I can do anything to help reproduce the issue, let me know.

**Comment by PCManticore** [comment] 2018-12-07 07:52
Thanks folks!

**Comment by PCManticore** [comment] 2019-01-17 14:38
Hey @Rogdham Just closed this one as I cannot reproduce this any longer using pylint's and astroid's master.

**Closed** 2019-01-17 14:38 UTC
Labels: bug, crash

**Comment by Rogdham** [comment] 2019-01-18 08:36
Thank you for the followup! Using pylint's and astroid's master, I confirm that the issue is fixed for the code I posted above (and that you included in the test) :tada: 

However my it still fails with RecursionError on my real code, but I need to dig further to create a reproduction case. @PCManticore if I manage to create some code snipet to replicate the issue, should I post it here or create a new issue?

**Comment by PCManticore** [comment] 2019-01-18 15:33
@Rogdham Here is fine, thanks.
